#+begin_export latex
  This is the entry point for \ty{never} the webserver for the \ty{neighbors} package.
  This webserver hosts the first iteration of \ty{never} \ty{api/v1}, the second iteration
  and its docs, as well as \ty{Vitax}. The idea of this program is to build a basic server structure
  that allows other packages to be registered to it. To begin implementing the server start off with a
  basic program layout.
#+end_export

#+begin_src go <<main.go>>=
package main

import (
 //<<Imports, Pr. \ref{pr:main}>>
)

//<<Types, Pr. \ref{pr:main}>>

//<<Functions, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  We begin with the main function.
  This should take care of any arguments passed when calling the program.
  It should call the register functions of the packages. Define a default route
  and finally start the server.
#+end_export

#+begin_src go <<Functions, Pr. \ref{pr:main}>>=
  func main() {
    //<<Handle io, Pr. \ref{pr:main}>>
    //<<Open databases, Pr. \ref{pr:main}>>
    //<<Register packages, Pr. \ref{pr:main}>>
    //<<Serve Vitax files, Pr. \ref{pr:main}>>
    //<<Define default route, Pr. \ref{pr:main}>>
    //<<Create middleware, Pr. \ref{pr:main}>>
    //<<Start server, Pr. \ref{pr:main}>>
  }
#+end_src

#+begin_export latex
  Handling the input and output of this program should be done by a separate
  function. It's easier to implement this before calling it in main, so we do
  that now. We call this function \ty{ioHandling}. In this we prepare the log,
  implement a usage and parse the call arguments. As we need to define the
  return tuple of this function in its head we need to think about what
  arguments may be parsed and needed within the main function. Most importantly
  we need be able to pass an address and a port for the server to run on. It
  would be nice if we could also define a path for the HTTPS/TLS files i.e. the
  certificate and the private key. Providing extra options for the database
  directory path, a default among the databases of the directory and the date
  file results in a more flexible setup. It should be possible to toggle the
  rate limit for debugging and testing purposes. This results in six strings,
  an integer and a boolean as a return tuple.
#+end_export

#+begin_src go <<Functions, Pr. \ref{pr:main}>>=
  func ioHandling() (string, string, string, string, string, string, int, bool) {
    //<<Prepare log, Pr. \ref{pr:main}>>
    //<<Set usage, Pr. \ref{pr:main}>>
    //<<Parse flags, Pr. \ref{pr:main}>>
  }
#+end_src

#+begin_export latex
  Preparing the log can be easily done via the \ty{util} package. But for this
    we need to import the package first.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "github.com/evolbioinf/never/util"
#+end_src

#+begin_export latex
  Now we may prepare the log.
#+end_export

#+begin_src go <<Prepare log, Pr. \ref{pr:main}>>=
  util.PrepLog("never")
#+end_src

#+begin_export latex
  To set the usage we import the \ty{clio} package from evolbioinf
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "github.com/evolbioinf/clio"
#+end_src

#+begin_export latex
  This usage function expects three arguments. One is an example call, then a
  description of what the program is and does. Lastly a summary of what the
  example call results in.
#+end_export

#+begin_src go <<Set usage, Pr. \ref{pr:main}>>=
  clio.Usage(
    "-o 10.254.1.21 -p 443",
    "This is the webserver never. It hosts the neighbors' REST API" +
      "versions 1 and 2, " +
      "as well as their respective documentation. " +
      "New packages may be added in a similar fashion as seen " +
      "in the main function.",
    "Starts the webserver at specified address with given port.")
#+end_src

#+begin_export latex
  Parsing the flags is best done using the \ty{flag} package.
  We will also need the \ty{os} package.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "flag"
  "os"
#+end_src

#+begin_export latex
  We've already defined what flags we want to use. Now we just need to declare
  them programmatically. As an extra we should declare a version flag. If the
  flag is passed, we print the program's version and stop the program. In every
  other case we return the remaining flags.
#+end_export

#+begin_src go <<Parse flags, Pr. \ref{pr:main}>>=
  cFlag := flag.String("c", "certificates/cert.pem", "certificate")
  dFlag := flag.String("d", "databases", "path to database directory" +
    "relative to current working directory")
  ddFlag := flag.String("D", "neidb", "base name of the database that" +
    "should be used by default.")
  uFlag := flag.String("u", "updated.txt", "path to dateFile" +
    "relative to current working directory")
  kFlag := flag.String("k", "certificates/private_key.pem", "private key")
  oFlag := flag.String("o", "http://localhost", "host address")
  pFlag := flag.Int("p", 8080, "port")
  rFlag := flag.Bool("no-rate-limit", false, "Turn of rate limiting")
  vFlag := flag.Bool("v", false, "print progam info")

  flag.Parse()

  if *vFlag {
    util.PrintInfo()
    os.Exit(0)
  }

  return *cFlag, *dFlag, *ddFlag, *uFlag, *kFlag, *oFlag, *pFlag, *rFlag
#+end_src

#+begin_export latex
  Having implemented \ty{ioHandling} we know how to call it and what it
  returns. So let's do that.
#+end_export

#+begin_src go <<Handle io, Pr. \ref{pr:main}>>=
  certificate,
  dbDirPath,
  defaultDb,
  dateFilePath,
  privateKey,
  host,
  port,
  noRateLimit := ioHandling()
#+end_src

#+begin_export latex
  This server, mainly \ty{apiv2} allows accessing multiple databases. When
  executing \ty{main} we are provided with a directory which includes a set of
  databases. We need to think of a structure for storing these databases and
  their connections. \ty{apiv2} expects the databases to be stored in a map of
  \ty{dbname -> tuple(path, database)}. Why not use this here as well.
#+end_export

#+begin_src go <<Open databases, Pr. \ref{pr:main}>>=
  dbs := make(map[string]apiv2.Database)
#+end_src

#+begin_export latex
  Opening the databases is now about iterating through the files of the
  provided directory and connecting to them. We call a deferred \ty{Close} on
  each of them. The keys of the map should be the basename of each database
  file. Lastly there should be an entry called latest, which always points to
  the latest database.
#+end_export

#+begin_src go <<Open databases, Pr. \ref{pr:main}>>=
  //<<Get files, Pr. \ref{pr:main}>>
  for _, inf := range fileInfos {
    //<<Connect to db, Pr. \ref{pr:main}>>
  }
  //<<Update latest db, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  Our first step is to go through the provided directory and get all its
  entries. We us \ty{ReadDir} for this. Then we iterate over those entries,
  adding them to a list and get the file's information. This includes its name
  as well as modification date. After iteration we sort all the information
  entries by their modification date. This lets us easily determine the latest
  database.
#+end_export

#+begin_src go <<Get files, Pr. \ref{pr:main}>>=
  entries, err := os.ReadDir(dbDirPath)
  if err != nil {
    log.Fatal("error while trying to read database directory", err.Error())
  }
  var fileInfos []fs.FileInfo
  for _, e := range entries {
    info, err := e.Info()
    if err != nil {
      log.Fatal("error while trying to read info", err.Error())
    }
    fileInfos = append(fileInfos, info)
  }
  if len(fileInfos) == 0 {
    log.Fatal(errors.New("No databases in provided directory."))
  }
  slices.SortFunc(fileInfos, func(a, b fs.FileInfo) int {
    return b.ModTime().Compare(a.ModTime())
  })
#+end_src

#+begin_export latex
  We import \ty{errors}, \ty{io/fs} and \ty{slices}.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "errors"
  "io/fs"
  "slices"
#+end_src

#+begin_export latex
  Connecting to the database is rather simple. We define a path for each entry.
  This is composed of the file's name, prepended by the name of the database
  directory. The we open the connection and make a deferred \ty{Close} call. We
  also provide an additional entry for the first database as \ty{latest}. This
  is best done right after adding the first database. For this reason we check
  the map's size rather than loop indices.
#+end_export

#+begin_src go <<Connect to db, Pr. \ref{pr:main}>>=
  n := inf.Name()
  path := dbDirPath + "/" + n
  //<<Check if is db, Pr. \ref{pr:main}>>
  db, err := tdb.OpenTaxonomyDBcheck(path)
  if err != nil {
    log.Fatal(fmt.Sprintf("error while opening database %s: ", path),
      err.Error())
  }
  defer db.Close()
  dbs[n] = apiv2.Database{Path: path, Db: db}
  if len(dbs) == 1 {
    dbs["latest"] = apiv2.Database{Path: path, Db: db}
  }
#+end_src

#+begin_export latex
  We import \ty{tdb}.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "github.com/evolbioinf/neighbors/tdb"
#+end_src

#+begin_export latex
  For now I'm not sure how to check whether a file is a database in an elegant
  way. We do however know that a sqlite database begins with a fixed 16 byte
  header. So we should just open the files read the first 16 bytes a compare
  them to the expected header.
#+end_export

#+begin_src go <<Check if is db, Pr. \ref{pr:main}>>=
  f, err := os.Open(path)
  if err != nil {
    continue
  }
  fileHeader := []byte{0x53, 0x51, 0x4c, 0x69, 0x74, 0x65, 0x20, 0x66, 0x6f,
    0x72, 0x6d, 0x61, 0x74, 0x20, 0x33, 0x00}
  h := make([]byte, 16)
  f.Read(h)
  if !bytes.Equal(h, fileHeader) {
    continue
  }
#+end_src

#+begin_export latex
  We import \ty{bytes}.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "bytes"
#+end_src

#+begin_export latex
  We already added an entry for the latest db based on modification times.
  While this semantically fits really well, it is quite flaky. There is an
  automatic update system, rebuilding the database every night. Some existing
  databases get archived both manually and automatically. Furthermore depending
  on whether databases are linked into the database directory or copied inot it
  influences their modification time as well. All of this shows, that the
  modification time is not totally reliable. Because of that, we use the
  current \ty{latest} databses as a fallback only. We overwrite the \ty{latest}
  entry, if the user provided a different db.
#+end_export

#+begin_src go <<Update latest db, Pr. \ref{pr:main}>>=
  d, ok := dbs[defaultDb]
  if ok {
    dbs["latest"] = d
  } else {
		fmt.Printf("Could not find provided default db: %s, "+
			"falling back to %s (%s) instead.\n", defaultDb,
      filepath.Base(dbs["latest"].Path), dbs["latest"].Path)
  }
#+end_src

#+begin_export latex
  We import \ty{path/filepath}.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "path/filepath"
#+end_src

#+begin_export latex
  The packages we want to register each provide their own register function
  called \ty{registerRoutes}. The packages don't and shouldn't know of each
  others existance. So this task falls to the managing part of the software,
  which is this server. The first step to ensure that this works is preventing
  url clashes. While the packages should not know of each other they also
  should not register to the same routes. We prevent clashes by passing an url
  prefix to each of them. Additionally to the prefix \ty{apiv2} needs to get
  the databases. \ty{neverv1} receives prefixes both for the api and its
  documentation. We further pass the path to the latest database and a path to
  the datefile. \ty{docsv2} gets its prefix. It also needs to know whether it
  is being hosted locally and on what port, so we need to provide data for
  that. Lastly, we need to provide the directory to the databases.
#+end_export

#+begin_src go <<Register packages, Pr. \ref{pr:main}>>=
  docsPref := "/docs"
  apiPref := "/api"
  docsV1Pref := docsPref + apiPref + "/v1"
  docsV2Pref := docsPref + apiPref + "/v2"
  isLocal := host == "http://localhost"

  neverv1.RegisterRoutes(apiPref + "/v1", docsV1Pref, dbs["latest"].Path, dateFilePath)
  apiv2.RegisterRoutes(apiPref + "/v2", host+":"+strconv.Itoa(port), dbs)
  docsv2.RegisterRoutes(docsV2Pref, isLocal, port, dbDirPath)
#+end_src

#+begin_export latex
  We also need to import the registerd packages, as well as \ty{net/http} and \ty{strconv}
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  neverv1 "github.com/evolbioinf/never/api/v1/never"
  apiv2 "github.com/evolbioinf/never/api/v2"
  docsv2 "github.com/evolbioinf/never/docs/v2"
  "net/http"
  "strconv"
#+end_src

#+begin_export latex
  The Vitax files are located in directory \ty{vitax}. We make them
  available by registering a file server to that directory.
#+end_export

#+begin_src go <<Serve Vitax files, Pr. \ref{pr:main}>>=
  vitaxFiles := http.FileServer(http.Dir("vitax"))
  http.Handle("/vitax/", http.StripPrefix("/vitax/", vitaxFiles))
#+end_src

#+begin_export latex
  Whenever the server is called without any route it should redirect to the most current docs. At the moment
  this is \ty{docsv2}. We do this in a well mannered fashion by using http redirect and setting the correct http status, which is 303.
  Go changed its url matching strategies with version 1.22. Using \ty{\{$\}} at the end of a string defines that it should match exactly and only this string.
#+end_export

#+begin_src go <<Define default route, Pr. \ref{pr:main}>>=
  http.HandleFunc("/{$}", func(w http.ResponseWriter, r *http.Request) {
    http.Redirect(w, r, docsV2Pref, http.StatusSeeOther)
  })
#+end_src

#+begin_export latex
  Creating the middleware is a step in which we define functions that are called for all requests handled
  by this server. Whether their logic is applied to a specific route is up to the layer of the middleware.
  One layer of this middleware is made up of a function that takes and returns a \ty{http.Handler}.
  Each layer adds some processing capabilities. The first layer for example is for rate limiting.
  Another layer is for logging requests and responses. We define the functions in the scope of
  the main function in order to get access to local variables, like paths and limiters.
#+end_export

#+begin_src go <<Create middleware, Pr. \ref{pr:main}>>=
  //<<Create logger middleware, Pr. \ref{pr:main}>>
  //<<Create limiter middleware, Pr. \ref{pr:main}>>
  //<<Create caching middleware, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  For creating the logging middleware we use our own logging package.
  This allows us to persist information and warning log entries. For this
  we first need to setup the log. Before exiting this process we
  to stop the logging process.
#+end_export

#+begin_src go <<Create logger middleware, Pr. \ref{pr:main}>>=
  util.SetupLog()
  defer util.StopLogging();
  //<<Write logger middleware, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  We write an outline of the logger middleware and think about how and exactly what
  to log in the next step. A log entry contains data about the response, specifically
  it's size, status code and processing time. Measuring the processing time may be done
  by subtracting a timestamp before passing the request and after getting it's response.
  Obtaining the the response code and size is a bit trickier, as the writer does not give
  access to it's response - probably because it's not yet written... We are going to address
  this in the next step.
#+end_export

#+begin_src go <<Write logger middleware, Pr. \ref{pr:main}>>=
  middlewareLogger := func(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
      bef := time.Now().UnixMilli()
      //<<Pass on request, Pr. \ref{pr:main}>>
      af := time.Now().UnixMilli()
      //<<Log request, Pr. \ref{pr:main}>>
    })
  }
#+end_src

#+begin_export latex
  Measuring time requires importing the \ty{time} package.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "time"
#+end_src

#+begin_export latex
  Back to getting the response data. To obtain this data anyways we wrap the writer,
  into a custom one. This wrapper just saves the status code and bytes it wrote.
  We need to define a type for this and redefine the functions \ty{Write} and
  \ty{WriteHeader}.
#+end_export

#+begin_src go <<Types, Pr. \ref{pr:main}>>=
  type CustomResponseWriter struct {
    http.ResponseWriter
    code,
    size int
  }

  func (w *CustomResponseWriter) Write(b []byte) (int, error)  {
    a, err := w.ResponseWriter.Write(b)
    w.size += a
    return a, err
  }

  func (w *CustomResponseWriter) WriteHeader(statusCode int) {
    w.code = statusCode
    w.ResponseWriter.WriteHeader(statusCode)
  }
#+end_src

#+begin_export latex
  The \ty{CustomResponseWriter} fulfills the \ty{http.ResponseWriter} interface requirements.
  This means we can pass without changing anything in the lower levels of this server.
#+end_export

#+begin_src go <<Pass on request, Pr. \ref{pr:main}>>=
  cw := &CustomResponseWriter{ResponseWriter: w, code: 200, size: 0}
  next.ServeHTTP(cw, r)
#+end_src

#+begin_export latex
  We don't want to log every single request. Parts of the the server, mostly the frontend,
  make a lot of consecutive requests, that aren't worth logging. It's interesting to get
  a log entry, when someone is requesting the docs, but we don't need to log the follow up
  requests for all the css files etc. This means we need to check the request url.
#+end_export

#+begin_src go <<Log request, Pr. \ref{pr:main}>>=
  if r.URL.Path == docsV2Pref ||
    r.URL.Path == docsV1Pref ||
    !strings.Contains(r.URL.Path, docsPref) {
    //<<Write log entry, Pr. \ref{pr:main}>>
  }
#+end_src

#+begin_export latex
  Now we know when to write an entry, but not what to write to it. Looking at our log package
  let's us gain insight on what to log. An \ty{util.InfoEntry} may contain seven properties.
  They hold information on ip, url, method, code, size, processing time and description.
  This is the data we need to provide for logging. Most of this may be retrieved from the
  http.Writer and http.Request objects.
#+end_export

#+begin_src go <<Write log entry, Pr. \ref{pr:main}>>=
  //<<Retrieve remote ip, Pr. \ref{pr:main}>>

  util.LogInfoDef(util.InfoEntry{
    RequestIp: ip,
    RequestUrl: r.URL.String(),
    RequestMethod: r.Method,
    ResponseCode: cw.code,
    ResponseSize: fmt.Sprintf("%db", cw.size),
    ResponseTime: fmt.Sprintf("%dms", int(af - bef)),
    Description: "middleware request log entry",
  })
#+end_src

#+begin_export latex
  The remote ip is stored within the request's \ty{RemoteAddr} field. It may be retrieved
  using the \ty{SplitHostPort} method from the net \ty{package}. We log any errors
  using \ty{util.log}'s \ty{LogWarningDef} method.
#+end_export

#+begin_src go <<Retrieve remote ip, Pr. \ref{pr:main}>>=
  ip, _, err := net.SplitHostPort(r.RemoteAddr)
  if err != nil {
    util.LogWarningDef(
      util.WarningEntry{
        Warning: fmt.Sprintf("Couldn't parse remote address %s during %s request", r.RemoteAddr, r.URL.Path),
    })
  }
#+end_src

#+begin_export latex
  Rate limiting is a technique to restrict the amount of requests a server may handle for a given timeframe.
  We are going to implement a multilevel rate limit, where the first level is a user based limit and the second
  handles across user requests. The per user requests should stop single users from sending too many requests, while
  still allowing other users to work with the api. While the second level hardens against
  a bot attacks. We use go rate package from the time extension pack for this.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "golang.org/x/time/rate"
#+end_src

#+begin_export latex
  We create a new general limiter which follows a token bucket approach. Each token represents a request. Requests are allowed
  as long as there are tokens in the bucket, new tokens are added every second. This rate limit allows for burst.
  The middleware checks against the limiter and passes the request to the next layer if the limiter allows it.
  If the limit is exceeded we write a 429 (too many requests) response stating it's reason.
  We should exclude the docs from beign limited.
#+end_export

#+begin_src go <<Create limiter middleware, Pr. \ref{pr:main}>>=
  generalLimiter := rate.NewLimiter(rate.Limit(10), 100)
  //<<Declare per user limiter, Pr. \ref{pr:main}>>
  //<<Write limiter middleware, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  The per user limiter is actually a map of many limiters. The map has ip adresses as a key
  for user identification and their respective limiter as a value. As the server runs concurrently,
  a mutex is required. We wrap both of them in a struct for better handling.
#+end_export

#+begin_src go <<Types, Pr. \ref{pr:main}>>=
  type SyncMap struct {
    ma map[string]*rate.Limiter
    mu sync.Mutex
  }
#+end_src

#+begin_export latex
  The mutex also requires the sync package.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "sync"
#+end_src

#+begin_export latex
  Declaring the per limiter is now just a matter of creating a variable.
#+end_export

#+begin_src go <<Declare per user limiter, Pr. \ref{pr:main}>>=
  userLimiters := SyncMap{ma: make(map[string]*rate.Limiter)}
#+end_src

#+begin_export latex
  As already stated the middleware is just a function that gets and
  returns an \ty{http.Handler}. Inside we check for a certain condition, which includes
  the requested url and the current limiter state. We either forward the request or
  return an 429 error code, depending on the result.
#+end_export

#+begin_src go <<Write limiter middleware, Pr. \ref{pr:main}>>=
  middlewareLimiter := func(next http.Handler) http.Handler {
    return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
      //<<Check condition, Pr. \ref{pr:main}>>
    })
  }
#+end_src

#+begin_export latex
  First we check whether the requested url is rate limited, i.e. apiv1 or apiv2. We immediately
  call the next handler, if the url is no rate limited. If it is we check the general and user
  limiters. We first check the general limiter, as checking the user limiters requires more
  processing power. If the general limiter allows processing we check the user limiter. If both
  limiters allow processing we call the next handler. We write an error response if either limiter
  denies processing.
#+end_export

#+begin_src go <<Check condition, Pr. \ref{pr:main}>>=
      allowed := noRateLimit || !strings.HasPrefix(r.URL.Path, apiPref)
      if !allowed {
        if generalLimiter.Allow() {
          //<<Check user limiter, Pr. \ref{pr:main}>>
        }
      }

      if !allowed {
        w.WriteHeader(http.StatusTooManyRequests)
        w.Write([]byte("Exceeded rate limit\n"))
      } else {
        next.ServeHTTP(w, r)
      }
#+end_src

#+begin_export latex
  We are working with a custom syncMap - the \ty{sync.Map} advises against it's
  usage unless encoutering two specific scenarios - which requires locking the
  mutex when reading or writing. Locking for a write might suffice, but I
  believe the go spec does not specify whethere a read operation is thread-
  safe. We'd need to lock the map for the next step anyways, as calling the
  \ty{Allow} function entails a state change within the limiter, which wouldn't
  be thread safe. So we lock the mutex get the specific limiter, or add if this
  is the user's first request, and check it.
#+end_export

#+begin_src go <<Check user limiter, Pr. \ref{pr:main}>>=
  ip, _, err := net.SplitHostPort(r.RemoteAddr)
  if err != nil {
    fmt.Printf("Couldn't parse remote address %s\n", r.RemoteAddr)
  }

  userLimiters.mu.Lock()
  lim, ok := userLimiters.ma[ip]
  if !ok {
    lim = rate.NewLimiter(rate.Limit(10), 25)
    userLimiters.ma[ip] = lim
  }

  allowed = lim.Allow()
  userLimiters.mu.Unlock()
#+end_src

#+begin_export latex
  We need to add the strings and net packages, because of the url comparison.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "strings"
  "net"
#+end_src

#+begin_export latex
  Now we are ready to start the server. If no host was provided we serve
  everything locally using http. If a host was specified, we serve at that
  address using HTTPS/TLS. In either case we should report where we are
  serving. We read errros provided by the serve function. If the error is a
  server closed error, we may shutdown gracefully, otherwise we log a fatal
  error. But we need to import \ty{fmt} and \ty{log} first.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "fmt"
  "log"
#+end_src

#+begin_export latex
  Now lets get into starting the server. Here we need to define the
  middleware chain first. Then there is the server object, which needs
  creating. Running the server is the next step. Lastly we need to take care of
  shutting down the server. This entails checking if a termination signal was
  send, passing it down to the server and do some logging.



  In order to do so, we run the server in a subroutine
  and block until we get a terminate signal. After receiving the signal, we
  pass it along to the server and allow it to hadle it's shutdown. We might
  want to add a log entry stating, that the server was shut down.
#+begin_export latex

#+begin_src go <<Start server, Pr. \ref{pr:main}>>=
  handlerChain := middlewareLimiter(middlewareLogger(http.DefaultServeMux))
  //<<Determine server address, Pr. \ref{pr:main}>>
  //<<Create server, Pr. \ref{pr:main}>>
  //<<Run server, Pr. \ref{pr:main}>>
  //<<Block until term signal, Pr. \ref{pr:main}>>
  //<<Pass timed shutdown, Pr. \ref{pr:main}>>
  //<<Log shutdown, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  The server address is just the port, when running locally, while it's the
  full string when deploying.
#+end_export

#+begin_src go <<Determine server address, Pr. \ref{pr:main}>>=
  var addr string
  if isLocal {
    addr = fmt.Sprintf(":%d", port)
  } else {
    addr = fmt.Sprintf("%s:%d", host, port)
  }
#+end_src

#+begin_export latex
  With the address and the chain of handlers declared, we are ready to create
  the server object.
#+end_export

#+begin_src go <<Create server, Pr. \ref{pr:main}>>=
  s := http.Server{
    Addr:    addr,
    Handler: handlerChain,
  }
#+end_src

#+begin_export latex
  The server is ready to run. We should do this inside a subroutine. This
  allows us to listen to signals.
#+end_export

#+begin_src go <<Run server, Pr. \ref{pr:main}>>=
  go func() {
    fmt.Printf("Starting server at %s:%d ...\n", host, port)
    if isLocal {
      err = s.ListenAndServe()
    } else {
      err = s.ListenAndServeTLS(certificate, privateKey)
    }
  }()
#+end_src

#+begin_export latex
  There are two signals we want to listen and act on. The first one is
  \ty{sigterm}. It is send by the os, when it wants to gracefully stop a
  process. \ty{sigint} is sent when the user presses ty{ctrl + c}.
#+end_export

#+begin_src go <<Block until term signal, Pr. \ref{pr:main}>>=
  term, c := signal.NotifyContext(context.Background(), syscall.SIGTERM, syscall.SIGINT)
  defer c()
  <-term.Done()
#+end_src

#+begin_export latex
  We need to import \ty{context}, \ty{os/signal} and \ty{syscall}
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "context"
  "os/signal"
  "syscall"
#+end_src

#+begin_export latex
  If there was a shutdown signal, we create a timed context and pass it on
  to the server.
#+end_export

#+begin_src go <<Pass timed shutdown, Pr. \ref{pr:main}>>=
  fmt.Println("...Stopping server")
  ctx, cancel := context.WithTimeout(context.Background(), 1500*time.Millisecond)
  defer cancel()
  err = s.Shutdown(ctx)
#+end_src

#+begin_export latex
  Logging is a good idea here. We add an entry for a failed shutdown and the
  graceful one.
#+end_export

#+begin_src go <<Log shutdown, Pr. \ref{pr:main}>>=
  if err != nil {
    util.LogInfoDef(util.InfoEntry{Description: "Server shutdown with error: " + err.Error()})
  } else {
    util.LogInfoDef(util.InfoEntry{Description: "Server shutdown gracefully"})
  }
  fmt.Println("Shutdown complete")
#+end_src