#+begin_export latex
  This is the entry point for \ty{never} the webserver for the \ty{neighbors} package.
  This webserver hosts the first iteration of \ty{never} \ty{api/v1}, the second iteration
  and its docs, as well as \ty{Vitax}. The idea of this program is to build a basic server structure
  that allows other packages to be registered to it. To begin implementing the server start off with a
  basic program layout.
#+end_export

#+begin_src go <<main.go>>=
package main

import (
 //<<Imports, Pr. \ref{pr:main}>>
)

//<<Types, Pr. \ref{pr:main}>>

//<<Functions, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  We begin with the main function.
  This should take care of any arguments passed when calling the program.
  It should call the register functions of the packages. Define a default route
  and finally start the server.
#+end_export

#+begin_src go <<Functions, Pr. \ref{pr:main}>>=
  func main() {
    //<<Handle io, Pr. \ref{pr:main}>>
    //<<Register packages, Pr. \ref{pr:main}>>
    //<<Define default route, Pr. \ref{pr:main}>>
    //<<Create middleware, Pr. \ref{pr:main}>>
    //<<Start server, Pr. \ref{pr:main}>>
  }
#+end_src

#+begin_export latex
  Handling the input and output of this program should be done by a separate function.
  Its easier to implement this before calling it in main, so we do that now.
    We call this function \ty{ioHandling}. In this we prepare the log, implement a usage and parse
  the call arguments. As we need to define the return tuple of this function in its head we need to
  think about what arguments may be parsed and needed within the main function. Most importantly we
  need be able to pass an address and a port for the server to run on. It would be nice if we could also
  define a path for the HTTP/TLS files i.e. the certificate and the private key. Providing extra options
  for the database path and the date file results in a more flexible setup.
  This results in five strings and an integer as a return tuple.
#+end_export

#+begin_src go <<Functions, Pr. \ref{pr:main}>>=
  func ioHandling() (string, string, string, string, string, int) {
    //<<Prepare log, Pr. \ref{pr:main}>>
    //<<Set usage, Pr. \ref{pr:main}>>
    //<<Parse flags, Pr. \ref{pr:main}>>
  }
#+end_src

#+begin_export latex
  Preparing the log can be easily done via the \ty{util} package. But for this we need to import the
  package first.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "github.com/evolbioinf/never/util"
#+end_src

#+begin_export latex
  Now we may prepare the log.
#+end_export

#+begin_src go <<Prepare log, Pr. \ref{pr:main}>>=
  util.PrepLog("never")
#+end_src

#+begin_export latex
  To set the usage we import the \ty{clio} package from evolbioinf
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
	"github.com/evolbioinf/clio"
#+end_src

#+begin_export latex
  This usage function expects three arguments. One is an example call, then a
  description of what the program is and does. Lastly a summary of what the example call results in.
#+end_export

#+begin_src go <<Set usage, Pr. \ref{pr:main}>>=
  clio.Usage(
    "-o 10.254.1.21 -p 443",
    "This is the webserver never. It hosts the neighbors' REST API versions 1 and 2, "+
      "as well as their respective documentation. "+
      "New packages may be added in a similar fashion as seen "+
      "in the main function.",
    "Starts the webserver at specified address with given port.")
#+end_src

#+begin_export latex
  Parsing the flags is best done using the \ty{flag} package.
  We will also need the \ty{os} package.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "flag"
  "os"
#+end_src

#+begin_export latex
  We've already defined what flags we want to use. Now we just need to declare them programmatically.
  As an extra we should declare a version flag. If the flag is passed, we print the program's version and stop the program.
  In every other case we return the remaining flags.
#+end_export

#+begin_src go <<Parse flags, Pr. \ref{pr:main}>>=
  cFlag := flag.String("c", "certificates/cert.pem", "certificate")
  dbFlag := flag.String("db", "neidb", "path to database from execution position")
  dFlag := flag.String("d", "updated.txt", "path to dateFile from execution position")
  kFlag := flag.String("k", "certificates/private_key.pem", "private key")
  oFlag := flag.String("o", "", "host address")
  pFlag := flag.Int("p", 8080, "port")

  vFlag := flag.Bool("v", false, "print progam info")

  flag.Parse()

  if *vFlag {
    util.PrintInfo()
    os.Exit(0)
  }

  return *cFlag, *dbFlag, *dFlag, *kFlag, *oFlag, *pFlag
#+end_src

#+begin_export latex
  Having implemented \ty{ioHandling} we know how to call it and what it returns. So let's do that.
#+end_export

#+begin_src go <<Handle io, Pr. \ref{pr:main}>>=
	certificate, dbPath, dateFilePath, privateKey, host, port := ioHandling()
#+end_src

#+begin_export latex
  The packages we want to register each provide their own register function called \ty{registerRoutes}.
  We provide a prefix to that url, in order to prevent url clashing. The packages don't and shouldn't know of each others existance.
  So this task falls to the managing part of the software, which is this server.
  Additionally to the prefix \ty{apiv2} needs to know where the database is located. \ty{neverv1} receives these arguments as well, but it gets
  two prefixes as the package is not divided into api and docs. It also needs to get an extra filepath for the \ty{dateFile}.
  \ty{docsv2} needs to know whether it is being hosted locally and on what port, so we need to provide data for that.
#+end_export

#+begin_src go <<Register packages, Pr. \ref{pr:main}>>=
  docsPref := "/docs"
	apiPref := "/api"
  docsV2Pref := docsPref + apiPref + "/v2"

	neverv1.RegisterRoutes(apiPref + "/v1", docsPref+apiPref + "/v1", dbPath, dateFilePath)
	apiv2.RegisterRoutes(apiPref + "/v2", dbPath)
	docsv2.RegisterRoutes(docsV2Pref, host == "", port)
#+end_src

#+begin_export latex
  We also need to import the registerd packages, as well as \ty{net/http}
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  neverv1 "github.com/evolbioinf/never/api/v1/never"
	apiv2 "github.com/evolbioinf/never/api/v2"
	docsv2 "github.com/evolbioinf/never/docs/v2"

	"net/http"
#+end_src

#+begin_export latex
  Whenever the server is called without any route it should redirect to the most current docs. At the moment
  this is \ty{docsv2}. We do this in a well mannered fashion by using http redirect and setting the correct http status, which is 303.
  Go changed its url matching strategies with version 1.22. Using \ty{\{$\}} at the end of a string defines that it should match exactly and only this string.
#+end_export

#+begin_src go <<Define default route, Pr. \ref{pr:main}>>=
	http.HandleFunc("/{$}", func(w http.ResponseWriter, r *http.Request) {
		http.Redirect(w, r, docsV2Pref, http.StatusSeeOther)
	})
#+end_src

#+begin_export latex
  Creating the middleware is a step in which we define functions that are called for all requests handled
  by this server. Whether their logic is applied to a specific route is up to the layer of the middleware.
  One layer of this middleware is made up of a function that takes and returns a \ty{http.Handler}.
  Each layer adds some processing capabilities. The first layer for example is for rate limiting.
  Another layer is for logging requests and responses. We define the functions in the scope of
  the main function in order to get access to local variables, like paths and limiters.
#+end_export

#+begin_src go <<Create middleware, Pr. \ref{pr:main}>>=
  //<<Create limiter middleware, Pr. \ref{pr:main}>>
  //<<Create logger middleware, Pr. \ref{pr:main}>>
  //<<Create caching middleware, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  Rate limiting is a technique to restrict the amount of requests a server may handle for a given timeframe.
  We are going to implement a multilevel rate limit, where the first level is a user based limit and the second
  handles across user requests. The per user requests should stop single users from sending too many requests, while
  still allowing other users to work with the api. While the second level hardens against
  a bot attacks. We use go rate package from the time extension pack for this.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
	"golang.org/x/time/rate"
#+end_src

#+begin_export latex
  We create a new general limiter which follows a token bucket approach. Each token represents a request. Requests are allowed
  as long as there are tokens in the bucket, new tokens are added every second. This rate limit allows for burst.
  The middleware checks against the limiter and passes the request to the next layer if the limiter allows it.
  If the limit is exceeded we write a 429 (too many requests) response stating it's reason.
  We should exclude the docs from beign limited.
#+end_export

#+begin_src go <<Create limiter middleware, Pr. \ref{pr:main}>>=
	generalLimiter := rate.NewLimiter(rate.Limit(10), 100)
  //<<Declare per user limiter, Pr. \ref{pr:main}>>
  //<<Write limiter middleware, Pr. \ref{pr:main}>>
#+end_src

#+begin_export latex
  The per user limiter is actually a map of many limiters. The map has ip adresses as a key
  for user identification and their respective limiter as a value. As the server runs concurrently,
  a mutex is required. We wrap both of them in a struct for better handling.
#+end_export

#+begin_src go <<Types, Pr. \ref{pr:main}>>=
  type SyncMap struct {
    ma map[string]*rate.Limiter
    mu sync.Mutex
  }
#+end_src

#+begin_export latex
  The mutex also requires the sync package.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "sync"
#+end_src

#+begin_export latex
  Declaring the per limiter is now just a matter of creating a variable.
#+end_export

#+begin_src go <<Declare per user limiter, Pr. \ref{pr:main}>>=
  userLimiters := SyncMap{ma: make(map[string]*rate.Limiter)}
#+end_src

#+begin_export latex
  As already stated the middleware is just a function that gets and
  returns an \ty{http.Handler}. Inside we check for a certain condition, which includes
  the requested url and the current limiter state. We either forward the request or
  return an 429 error code, depending on the result.
#+end_export

#+begin_src go <<Write limiter middleware, Pr. \ref{pr:main}>>=
  middlewareLimiter := func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
      //<<Check condition, Pr. \ref{pr:main}>>
		})
	}
#+end_src

#+begin_export latex
  First we check whether the requested url is rate limited, i.e. apiv1 or apiv2. We immediately
  call the next handler, if the url is no rate limited. If it is we check the general and user
  limiters. We first check the general limiter, as checking the user limiters requires more
  processing power. If the general limiter allows processing we check the user limiter. If both
  limiters allow processing we call the next handler. We write an error response if either limiter
  denies processing.
#+end_export

#+begin_src go <<Check condition, Pr. \ref{pr:main}>>=
			allowed := !strings.HasPrefix(r.URL.Path, apiPref)
			if !allowed {
				if generalLimiter.Allow() {
          //<<Check user limiter, Pr. \ref{pr:main}>>
				}
			}

			if !allowed {
				w.WriteHeader(http.StatusTooManyRequests)
				w.Write([]byte("Exceeded rate limit\n"))
			} else {
				next.ServeHTTP(w, r)
			}
#+end_src

#+begin_export latex
  We are working with a custom syncMap - the \ty{sync.Map} advises against it's usage unless encoutering
  two specific scenarios - which requires locking the mutex when reading or writing. Locking for a
  write might suffice, but I believe the go spec does not specify whethere a read operation is thread-
  safe. We'd need to lock the map for the next step anyways, as calling the \ty{Allow} function
  entails a state change within the limiter, which wouldn't be thread safe. So we lock the mutex
  get the specific limiter, or add if this is the user's first request, and check it.
#+end_export

#+begin_src go <<Check user limiter, Pr. \ref{pr:main}>>=
	ip, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		fmt.Printf("Couldn't parse remote address %s\n", r.RemoteAddr)
	}

	userLimiters.mu.Lock()
	lim, ok := userLimiters.ma[ip]
	if !ok {
		lim = rate.NewLimiter(rate.Limit(10), 25)
		userLimiters.ma[ip] = lim
	}

	allowed = lim.Allow()
	userLimiters.mu.Unlock()
#+end_src

#+begin_export latex
  We need to add the strings and net packages, because of the url comparison.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
	"strings"
	"net"
#+end_src

#+begin_export latex
  TODO
#+end_export

#+begin_src go <<Create logger middleware, Pr. \ref{pr:main}>>=
  util.SetupLog()
  defer util.StopLogging();
	middlewareLogger := func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		util.LogInfoDef(util.InfoEntry{Description: "Incoming request"})
				next.ServeHTTP(w, r)
		})
	}
#+end_src

#+begin_export latex
  Now we are ready to start the server. If no host was provided we serve everything locally using http.
  If a host was specified, we serve at that address using HTTPS/TLS. In either case we should report where we
  are serving. We read errros provided by the serve function. If the error is a server closed error, we may shutdown gracefully,
  otherwise we log a fatal error.
  But we need to import \ty{fmt} and \ty{log} first.
#+end_export

#+begin_src go <<Imports, Pr. \ref{pr:main}>>=
  "fmt"
  "log"
#+end_src

#+begin_export latex
  Now lets get into starting the server. Here we also need to define the middleware chain as a context.
  We also stop the logging process when we stop the server.
#+begin_export latex

#+begin_src go <<Start server, Pr. \ref{pr:main}>>=
  handlerChain := middlewareLimiter(middlewareLogger(http.DefaultServeMux))

	var err error
	if host == "" {
		fmt.Printf("Starting server at http://localhost:%d ...\n", port)
		err = http.ListenAndServe(fmt.Sprintf(":%d", port), handlerChain)
	} else {
		fmt.Printf("Starting server at %s:%d ...\n", host, port)
		err = http.ListenAndServeTLS(fmt.Sprintf("%s:%d", host, port), certificate, privateKey, handlerChain)
	}

	if err != http.ErrServerClosed {
		log.Fatal(err)
	}

	fmt.Println("Stopping server ...")
  util.StopLogging()
	fmt.Println("Shutdown gracefully")
#+end_src
