#+begin_export latex
!Package \ty{util} provides auxiliary functions for the \ty{never}
!package.

Our outline of \ty{util} has hooks for imports, variables, and
functions.  \bpa{util}{pa:uti}
#+end_export
#+begin_src go <<util.go>>=
  package util

  import (
	  //<<Imports, Pa. \ref{pa:uti}>>
  )
  //<<Variables, Pa. \ref{pa:uti}>>
  //<<Functions, Pa. \ref{pa:uti}>>
#+end_src
#+begin_export latex
\epa
\section{\ty{Check}}
!\ty{Check} takes an error as argument. If the error isn't nil, it is
!printed to the standard error stream.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:uti}>>=
  func Check(err error) {
	  if err != nil {
		  fmt.Fprintf(os.Stderr, "ERROR[never]: %s\n", err)
	  }
  }
#+end_src
#+begin_export latex
We import \ty{fmt} and \ty{os}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:uti}>>=
  "fmt"
  "os"
#+end_src
#+begin_export latex
\section{\ty{CheckHTTP}}
!\ty{CheckHTTP} takes as arguments a HTTP respose writer and an
!eror. If the error is not nil, it is printed, unless it corresponds
!to one of the two standard messages that crop up in \ty{never}, in
!which case the error is ignored.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:uti}>>=
  func CheckHTTP(w http.ResponseWriter, err error) {
	  m1 := "sql: Rows closed"
	  m2 := "Empty ID list in tdb.MRCA"
	  if err != nil && err.Error() != m1 &&
		  err.Error() != m2 {
		  http.Error(w, err.Error(),
			  http.StatusInternalServerError)
	  }
  }
#+end_src
#+begin_export latex
We import \ty{http}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:uti}>>=
  "net/http"
#+end_src
#+begin_export latex
\section{\ty{PrepLog}}
! \ty{PrepLog} takes as argument the program name and uses it as
! prefix for the log message.

We also store the program name in the variable \ty{program} to make it
accessible from elsewhere in the package.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:uti}>>=
  func PrepLog(progName string) {
	  log.SetPrefix(progName + ": ")
	  program = progName
  }
#+end_src
#+begin_export latex
We import \ty{log}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:uti}>>=
  "log"
#+end_src
#+begin_export latex
We declare the variable \ty{program}.
#+end_export
#+begin_src go <<Variables, Pa. \ref{pa:uti}>>=
  var program string
#+end_src
#+begin_export latex
  \section{\ty{PrintInfo}}
  ! \ty{PrintInfo} prints information about the version, the
  ! author(s), and the license of \ty{never}.

  We set the author, email, and license.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:uti}>>=
  func PrintInfo() {
	    authors := "Bernhard Haubold,Ben Bahnsen"
	    email := "haubold@evolbio.mpg.de,bahnsen@evolbio.mpg.de"
	    license := "Gnu General Public License, " +
		    "https://www.gnu.org/licenses/gpl.html"
	    clio.PrintInfo(program, version, date,
		    authors, email, license)
	    os.Exit(0)
  }
#+end_src
#+begin_export latex
The date and the version are injected at compile time, so like
\ty{program} we declare them as package variables.
#+end_export
#+begin_src go <<Variables, Pa. \ref{pa:uti}>>=
  var date, version string
#+end_src
#+begin_export latex
  We import \ty{clio}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:uti}>>=
  "github.com/evolbioinf/clio"
#+end_src
#+begin_export latex
\section{\ty{SendGetRequest}}
  !The function \ty{SendGetRequest} takes as argument an address as a string
  !and the program's options and extra arguments as string slices, as well as
  !miscellaneous arguments as a map. It sends a get request using these values
  !and returns the result.

  Inside \ty{SendGetRequest} function,
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:uti}>>=
  func SendGetRequest(address string, options, extraArgs []string, miscArgs map[string]string) string {
    //<<Encode query, Pa. \ref{pa:uti}>>
    //<<Create \ty{get} request, Pa. \ref{pa:uti}>>
    //<<Execute request, Pa. \ref{pa:uti}>>
    //<<Parse response, Pa. \ref{pa:uti}>>
  }
#+end_src
#+begin_export latex
  There may be multiple slices that need to be encoded for a single request.
  This means we should write a function, which handles this url encoding. We
  use the exploded parameters for passing slices via the url. This means we
  need to iterate over each slice and add key value pairs. The values need to
  be encoded. The \ty{net/url} package provides a function for this.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:uti}>>=
  func urlEncodeSlice(qb *strings.Builder, slc []string, paramName string) {
    for _, v := range slc {
      if qb.Len() == 0 {
        qb.WriteRune('?')
      } else {
        qb.WriteRune('&')
      }
      qb.WriteString(paramName)
      qb.WriteRune('=')
      qb.WriteString(url.QueryEscape(v))
    }
  }
#+end_src
#+begin_export latex
  Now all we need to do is call \ty{urlEncodeSlice} for both the options and
  the extra arguments... and encode the miscellaneous arguments further down
  the line.
#+end_export
#+begin_src go <<Encode query, Pa. \ref{pa:uti}>>=
  qb := new(strings.Builder)
  urlEncodeSlice(qb, options, "options")
  urlEncodeSlice(qb, extraArgs, "extra")
  //<<Encode misc args, Pa. \ref{pa:uti}>>
#+end_src
#+begin_export latex
  This requires us to import \ty{net/url} and \ty{strings}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:uti}>>=
  "net/url"
  "strings"
#+end_src
#+begin_export latex
  We iterate over the \ty{miscArgs} encoding both the keys and values.
  Everything else is pretty much the same as encoding a slice.
#+end_export
#+begin_src go <<Encode misc args, Pa. \ref{pa:uti}>>=
  for m, a := range miscArgs {
    if qb.Len() == 0 {
      qb.WriteRune('?')
    } else {
      qb.WriteRune('&')
    }
    qb.WriteString(url.QueryEscape(m))
    qb.WriteRune('=')
    qb.WriteString(url.QueryEscape(a))
  }
#+end_src
#+begin_export latex
  The \ty{net/http} package provides functions for creating requests.
  There is a \ty{Get} function for creating a get request, but it does
  not allow adding headers. We use \ty{NewRequest} instead and define
  the http verb manually.
#+end_export
#+begin_src go <<Create \ty{get} request, Pa. \ref{pa:uti}>>=
  req, err := http.NewRequest(http.MethodGet, address+qb.String(), nil)
  Check(err)
#+end_src
#+begin_export latex
  Http clients provide methods for invoking requests.
  The \ty{http} package uses a default client for this,
  which is public. We are going to use this client as well.
#+end_export
#+begin_src go <<Execute request, Pa. \ref{pa:uti}>>=
  resp, err := http.DefaultClient.Do(req)
  Check(err)
#+end_src
#+begin_export latex
  Laslty we parse the response using the \ty{io} package and
  return the data.
#+end_export
#+begin_src go <<Parse response, Pa. \ref{pa:uti}>>=
  body, err := io.ReadAll(resp.Body)
  Check(err)
  return string(body)
#+end_src
#+begin_export latex
  Though we still need to import \ty{io}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:uti}>>=
  "io"
#+end_src
#+begin_export latex
\section{\ty{SendQueryRequest}}
  !The function \ty{SendQueryRequest} takes as argument an address as a string,
  !program options and extra arguments as a slice of strings, as well as files
  !and stdin. It sends a query request using these values and returns the
  !result.
#+end_export
#+begin_src go <<Functions, Pa. \ref{pa:uti}>>=
  func SendQueryRequest(
    address string,
    options, extraArgs []string,
    miscArgs map[string]string,
    files []*os.File,
    stdin *os.File,
  ) string {
    //<<Encode query, Pa. \ref{pa:uti}>>
    //<<Set \ty{query} form data, Pa. \ref{pa:uti}>>
    //<<Create \ty{query} request, Pa. \ref{pa:uti}>>
    //<<Write \ty{query} headers, Pa. \ref{pa:uti}>>
    //<<Execute request, Pa. \ref{pa:uti}>>
    //<<Parse response, Pa. \ref{pa:uti}>>
  }
#+end_src
#+begin_export latex
  For setting the query form data we use the \ty{multipart} package.
  First we create a new multipart writer. Then we iterate over all
  the files. We create an entry using the writer for each file
  and copy its content. We close the multipart writer at the end.
#+end_export
#+begin_src go <<Set \ty{query} form data, Pa. \ref{pa:uti}>>=
  var b bytes.Buffer
  w := multipart.NewWriter(&b)
  for i, file := range files {
    //<<Create entry in writer, Pa. \ref{pa:uti}>>
    //<<Copy content, Pa. \ref{pa:uti}>>
  }
  //<<Add stdin to writer, Pa. \ref{pa:uti}>>
  w.Close()
#+end_src
#+begin_export latex
  We import \ty{bytes} and \ty{mime/multipart}.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:uti}>>=
  "bytes"
  "mime/multipart"
#+end_src
#+begin_export latex
  When creating an entry with the multipart writer, we create a new form file.
  We need to provide a key for the map of files and the name of the file itself.
  The multipart package takes care of creating the file headers and other meta data.
#+end_export
#+begin_src go <<Create entry in writer, Pa. \ref{pa:uti}>>=
  fw, err := w.CreateFormFile(strconv.Itoa(i), file.Name())
  Check(err)
#+end_src
#+begin_export latex
  We need the \ty{strconv} package for converting integers into strings.
#+end_export
#+begin_src go <<Imports, Pa. \ref{pa:uti}>>=
  "strconv"
#+end_src
#+begin_export latex
  \ty{io.Copy} allows us to copy the file's content to the filewriter.
#+end_export
#+begin_src go <<Copy content, Pa. \ref{pa:uti}>>=
  _, err = io.Copy(fw, file)
  Check(err)
#+end_src
#+begin_export latex
  \ty{stdin} needs a slightly different treatment as it's name might raise
  difficulties.
#+end_export
#+begin_src go <<Add stdin to writer, Pa. \ref{pa:uti}>>=
  if stdin != nil {
    fw, err := w.CreateFormFile("stdin", "stdin")
    Check(err)
	  _, err = io.Copy(fw, stdin)
	  Check(err)
  }
#+end_src
#+begin_export latex
  We create \ty{query} request. Adding the query string is the same
  as for the get request. The body
#+end_export
#+begin_src go <<Create \ty{query} request, Pa. \ref{pa:uti}>>=
  req, err := http.NewRequest("QUERY", address+qb.String(), &b)
  Check(err)
#+end_src
#+begin_export latex
  We use the writer to set the correct content type including boundaries.
#+end_export
#+begin_src go <<Write \ty{query} headers, Pa. \ref{pa:uti}>>=
  req.Header.Set("Content-Type", w.FormDataContentType())
#+end_src
