#+begin_export latex
  \section{api}
  \ty{api} is the backend application for neverV2.
  It implements all the endpoints defined in the
  openApi document. The underlying logic will closely
  resemble neverv1, as the backends don't differ too much.

  \subsection*{Implementation}
  The api backend provides the global RegisterRoutes function just
  like every standalone package used within neverV2. It takes as arguments
  a prefix for the routes and the filepath of the db file.
  \bpr{api}{pr:api}
#+end_export

#+begin_src go <<api.go>>=
  package apiv2
  import (
    //<<Imports, Pa. \ref{pa:api}>>
  )
  //<<Types, Pa. \ref{pa:api}>>
  //<<Methods, Pa. \ref{pa:api}>>
  //<<Variables, Pa. \ref{pa:api}>>
  //<<Content types, Pa. \ref{pa:api}>>
  func RegisterRoutes(pref, dbPath string) {
    //<<Register routes, Pa. \ref{pa:api}>>
  }
  //<<Functions, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
First off we declare the types. This is an easy task as they are already
defined within the openApi document. We can leave out a few \ty{Taxon} types
here by just using the \ty{Taxon} type offering the most attributes and adding
\ty{omitempty} tags for most properties. Every type also needs a \ty{Links}
attribute which is going to be explained later on.
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type Accession struct {
  Accession string `json:"accession"`
  Level     string `json:"level"`
  Links     []Link `json:"links,omitempty"`
}
type GenomeCount struct {
  Level string `json:"level"`
  Count int    `json:"count"`
  Links []Link `json:"links,omitempty"`
}
type Rank struct {
  TaxId int    `json:"tax_id"`
  Rank  string `json:"rank"`
  Links []Link `json:"links,omitempty"`
}
type Image struct {
	Id          int    `json:"id"`
	Url         string `json:"url"`
	Attribution string `json:"attribution"`
}
type Taxon struct {
  TaxId          int           `json:"tax_id"`
  Parent         int           `json:"parent,omitempty"`
  IsLeaf         bool          `json:"is_leaf,omitempty"`
  Name           string        `json:"name,omitempty"`
  CommonName     string        `json:"common_name,omitempty"`
  Rank           string        `json:"rank,omitempty"`
  Accessions     []Accession   `json:"accessions,omitempty"`
  RawGenomeCount []GenomeCount `json:"raw_genome_counts,omitempty"`
  RecGenomeCount []GenomeCount `json:"rec_genome_counts,omitempty"`
  Images         []Image       `json:"images,omitempty"`
  Links          []Link        `json:"links,omitempty"`
}
type TaxonAccession struct {
  TaxId      int         `json:"tax_id"`
  Accessions []Accession `json:"accessions,omitempty"`
  Links      []Link      `json:"links,omitempty"`
}
#+end_src

#+begin_export latex
  These are the types we could infer from the api specification. All of them have some semantical
  meaning in regards of the resources we provide via the api. To really make this API a REST API it
  needs to be hypermedia driven. Therefore each type representing a resource needs to get a \ty{Links}
  attribute. This allows entities to offer further queries against themselves. The top level response
  needs to offer links as well. For this reason we wrap the response into a type with a \ty{Data} field and
  a \ty{Links} field. The \ty{Link} itself is made of four properties: a relation, a hyper reference, which
  is essentially the actual link, an action, otherwise called http method and the content types provided
  by the link. This schema for links is part of Microsofts REST API guidelines.
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type ResponseBody[T any] struct {
  Data  T      `json:"data,omitempty"`
  Links []Link `json:"links,omitempty"`
}
type Link struct {
  Rel    string   `json:"rel"`
  Href   string   `json:"href"`
  Action string   `json:"action"`
  Types  []string `json:"types"`
}
#+end_src

#+begin_export latex
  Handling all of these links is a tedious task. So creating a data structure for working
  with them seems necessary. I thought of a link graph as a well suited structure.
  This link graph is composed of nodes, like any other graph. Each node represents a
  callable endpoint with a template URI. These nodes again contain information about
  the http method and content types. The \ty{Links} attribute is what allows these
  nodes to turn into a graph. This attribute is a map mapping strings to a list of nodes.
  The string is used to model the relation for a set of nodes. We need a set or list of nodes
  for each relation, as some might use the same name, think of the root document for instance.
  Its whole purpose is to provide the links to all services. The relation to each of them is the
  same: "service".
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type Node struct {
	Links    map[string][]Node
  Name     string
	BasePath string
	Action   string
	Types    []contenttype.MediaType
}
#+end_src

#+begin_export latex
  We are using the \ty{contenttype} package for the \ty{Types} here.
  Which means we need to import it. This package is rfc7231 compliant
  and is going to help us in terms of content negotiation.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
	"github.com/elnormous/contenttype"
#+end_src

#+begin_export latex
  With this imported we might as well define the o content types we are going
  to use. As they will be used frequently and should not be redefined over
  the course of this document, we will save them as global variables.
#+end_export

#+begin_src go <<Content types, Pa. \ref{pa:api}>>=
	var jsonCt = contenttype.MediaType{Type: "application", Subtype: "json", Parameters: contenttype.Parameters{"charset": "utf-8"}}
	var graphvizCt = contenttype.MediaType{Type: "text", Subtype: "vnd.graphviz", Parameters: contenttype.Parameters{"charset": "utf-8"}}
	var plainCt = contenttype.MediaType{Type: "text", Subtype: "plain", Parameters: contenttype.Parameters{"charset": "utf-8"}}
#+end_src

#+begin_export latex
  We also need some way of entering he graph. The root document is a perfect
  fit for this.
#+end_export

#+begin_src go <<Variables, Pa. \ref{pa:api}>>=
  var root Node
#+end_src

#+begin_export latex
  Let's also declare a global variable for the route prefix.
#+end_export

#+begin_src go <<Variables, Pa. \ref{pa:api}>>=
  var prefix string
#+end_src

#+begin_export latex
  With the types declared we may begin implementing the \ty{RouteRegistration} function.
  In this we define the Linkgraph and use it's nodes to register the endpoints.
  Luckily the endpoints are already declared within the openApi document
  But before pasting everything into \ty{RegisterRoutes}, we need to think
  about how registration should work. It is reasonable to create a function that handles
  route registration, making things easier for us in the long run. Say we want to
  add a parameter or some specific handling to all our endpoints, we can just add
  it to the registration helper. We call this function \ty{makeRoute}. The function
  needs to take a node, the one to register, as well as a function \ty{fn}
  that is executed when the path is called. \ty{fn} will be wrapped so that we may pass extra arguments.
  However it needs to accept at least the http writer and request. The function may accept more
  arguments, so we make it variadic. Those arguments need to passed from \ty{makeRoute}
  to \ty{fn} somehow, so we make \ty{makeRoute} variadic as well.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func makeRoute(node *Node, fn func(http.ResponseWriter, *http.Request, *Node, ...any), args ...any) {
    http.HandleFunc(node.Action + " " + node.BasePath, func(w http.ResponseWriter, r *http.Request) {
	  		fn(w, r, node, args...)
	  })
  }
#+end_src

#+begin_export latex
  We import the \ty{net/http} package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "net/http"
#+end_src

#+begin_export latex
  All of the endpoints need to access the database.
  So before registering the endpoints we open a connection to
  the database using neighbors' tdb program. We will pass the connection to
  all functions that need it.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  var neidb *tdb.TaxonomyDB
  neidb, err := tdb.OpenTaxonomyDBcheck(dbPath)
  if err != nil {
    log.Fatal("apiV2: error while opening the database: ",  err.Error())
  }
#+end_src

#+begin_export latex
  We need to import the \ty{tdb} and \ty{log} packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "github.com/evolbioinf/neighbors/tdb"
  "log"
#+end_src

#+begin_export latex
  This is a good time to write the prefix to our global function.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  prefix = pref
#+end_src

#+begin_export latex
  This leaves us with the writing the link graph and the actual registration of the
  endpoints.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  //<<Initialize nodes and make routes, Pa. \ref{pa:api}>>
  //<<Link nodes, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  We know all the endpoints as they are defined in the openApi document.
#+end_export

#+begin_src go <<Initialize nodes and make routes, Pa. \ref{pa:api}>>=
  //<<Initialize \ty{rootDocument}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{accessions}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{accession}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxa}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxon}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{ancestors}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{children}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{parent}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{rankDistribution}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{subtree}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxonomy}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxonAccessions}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{fintac}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{mrca}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{neighbors}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{path}, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  The initialization is going to follow a very similar scheme for each endpoint.
  First we define its node with an empty map of links. We write down the endpoints path and
  http attributes, then we call \ty{makeRoute} using the node we just wrote. \ty{makeRoute}
  takes a function as a second argument, which handles the endpoint. These functions are yet
  to be implemented. For now we just write down some well fitting names and implement them later.
  There are a few common http attributes, that we are going to be using for a lot of the nodes.
  We should write them into variables, which makes house keeping easier in the long run.
#+end_export

#+begin_src go <<Initialize \ty{rootDocument}, Pa. \ref{pa:api}>>=
	get := "GET"
	post := "POST"

	rootDocL := Node{
		Links:    make(map[string][]Node),
    Name:     "rootDocument",
		BasePath: prefix,
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&rootDocL, rootDocument, neidb) // new
#+end_src

#+begin_export latex
  Let's register \ty{accessions}.
#+end_export

#+begin_src go <<Initialize \ty{accessions}, Pa. \ref{pa:api}>>=
	accessionsL := Node{
		Links:    make(map[string][]Node),
    Name:     "accessions",
		BasePath: prefix + "/accessions",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&accessionsL, accessions, neidb) // previously known as levels
#+end_src

#+begin_export latex
  \ty{accession} is almost the same as before.
#+end_export

#+begin_src go <<Initialize \ty{accession}, Pa. \ref{pa:api}>>=
	accessionL := Node{
		Links:    make(map[string][]Node),
    Name:     "accession",
		BasePath: prefix + "/accessions/{accession_id}",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&accessionL, accession, neidb) // new
#+end_src

#+begin_export latex
  As does \ty{taxa}.
#+end_export

#+begin_src go <<Initialize \ty{taxa}, Pa. \ref{pa:api}>>=
	taxaL := Node{
		Links:    make(map[string][]Node),
    Name:     "taxa",
		BasePath: prefix + "/taxa",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&taxaL, taxa, neidb) // previously known as taxi
#+end_src

#+begin_export latex
  \ty{taxon} is a subservice of \ty{taxa}.
#+end_export

#+begin_src go <<Initialize \ty{taxon}, Pa. \ref{pa:api}>>=
	taxonL := Node{
		Links:    make(map[string][]Node),
    Name:     "taxon",
		BasePath: prefix + "/taxa/{taxon_id}",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&taxonL, taxon, neidb) // new
#+end_src

#+begin_export latex
  \ty{ancestorsL} is another subservice of \ty{taxa}, but it provides
  plain text instead of json. It does not need a connection to the
  database, but the actual file path instead.
#+end_export

#+begin_src go <<Initialize \ty{ancestors}, Pa. \ref{pa:api}>>=
	ancestorsL := Node{
		Links:    make(map[string][]Node),
    Name:     "ancestors",
		BasePath: prefix + "/taxa/{taxon_id}/ancestors",
		Action:   get,
		Types:    []contenttype.MediaType{plainCt},
	}
	makeRoute(&ancestorsL, ancestors, dbPath) // new - calls ants program
#+end_src

#+begin_export latex
  As is \ty{children}.
#+end_export

#+begin_src go <<Initialize \ty{children}, Pa. \ref{pa:api}>>=
	childrenL := Node{
		Links:    make(map[string][]Node),
    Name:     "children",
		BasePath: prefix + "/taxa/{taxon_id}/children",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&childrenL, children, neidb) // previously just children
#+end_src

#+begin_export latex
  \ty{parent} is yet another subservice of \ty{taxa}. It again responds with taxon entities.
#+end_export

#+begin_src go <<Initialize \ty{parent}, Pa. \ref{pa:api}>>=
	parentL := Node{
		Links:    make(map[string][]Node),
    Name:     "parent",
		BasePath: prefix + "/taxa/{taxon_id}/parent",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&parentL, parent, neidb) // previously known as parent
#+end_src

#+begin_export latex
  \ty{rankDistribution} again provides plain text.
#+end_export

#+begin_src go <<Initialize \ty{rankDistribution}, Pa. \ref{pa:api}>>=
	rankDistL := Node{
		Links:    make(map[string][]Node),
    Name:     "rankDistribution",
		BasePath: prefix + "/taxa/{taxon_id}/rank_distribution",
		Action:   post,
		Types:    []contenttype.MediaType{plainCt},
	}
	makeRoute(&rankDistL, rankDistribution, dbPath) // new - calls ranks program
#+end_src

#+begin_export latex
  \ty{subtree} provides json, graphviz and plain text representations.
#+end_export

#+begin_src go <<Initialize \ty{subtree}, Pa. \ref{pa:api}>>=
	subtreeL := Node{
		Links:    make(map[string][]Node),
    Name:     "subtree",
		BasePath: prefix + "/taxa/{taxon_id}/subtree",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt, graphvizCt, plainCt},
	}
	makeRoute(&subtreeL, subtree, neidb, dbPath) // previously just subtree
#+end_src

#+begin_export latex
  \ty{taxonomy} is a new service. With this we are finally done registering subservices of \ty{taxa}.
#+end_export

#+begin_src go <<Initialize \ty{taxonomy}, Pa. \ref{pa:api}>>=
	taxonomyL := Node{
		Links:    make(map[string][]Node),
    Name:     "taxonomy",
		BasePath: prefix + "/taxonomy",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&taxonomyL, taxonomy, neidb) // new
#+end_src

#+begin_export latex
  \ty{taxonAccessions} is a subservice of \ty{taxonomy} providing json output.
#+end_export

#+begin_src go <<Initialize \ty{taxonAccessions}, Pa. \ref{pa:api}>>=
	taxonAccessionsL := Node{
		Links:    make(map[string][]Node),
    Name:     "taxonAccessions",
		BasePath: prefix + "/taxonomy/accessions",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&taxonAccessionsL, taxonAccessions, neidb) // previously called accessions
#+end_src

#+begin_export latex
  \ty{fintac} is a subservice of \ty{taxonomy} providing plain text.
  It takes a path to the database, as an argument, instead of the database itself.
#+end_export

#+begin_src go <<Initialize \ty{fintac}, Pa. \ref{pa:api}>>=
	fintacL := Node{
		Links:    make(map[string][]Node),
    Name:     "fintac",
		BasePath: prefix + "/taxonomy/fintac",
		Action:   post,
		Types:    []contenttype.MediaType{plainCt},
	}
	makeRoute(&fintacL, fintac, dbPath) // new - calls fintac program
#+end_src

#+begin_export latex
  \ty{mrca} is a subservice of \ty{taxonomy} providing json.
#+end_export

#+begin_src go <<Initialize \ty{mrca}, Pa. \ref{pa:api}>>=
	mrcaL := Node{
		Links:    make(map[string][]Node),
    Name:     "mrca",
		BasePath: prefix + "/taxonomy/mrca",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&mrcaL, mrca, neidb) // previously just mrca
#+end_src

#+begin_export latex
  \ty{neighbors} is another subservice of \ty{taxonomy} providing plain text.
#+end_export

#+begin_src go <<Initialize \ty{neighbors}, Pa. \ref{pa:api}>>=
	neighborsL := Node{
		Links:    make(map[string][]Node),
    Name:     "neighbors",
		BasePath: prefix + "/taxonomy/neighbors",
		Action:   get,
		Types:    []contenttype.MediaType{plainCt},
	}
	makeRoute(&neighborsL, neighbors, dbPath) // new - calls neighbors program
#+end_src

#+begin_export latex
  \ty{path} is our last service.
#+end_export

#+begin_src go <<Initialize \ty{path}, Pa. \ref{pa:api}>>=
	pathL := Node{
		Links:    make(map[string][]Node),
    Name:     "path",
		BasePath: prefix + "/taxonomy/path",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(&pathL, path, neidb) // previously just path
#+end_src

#+begin_export latex
  Now that we are done creating nodes and registering function we may set the links that
  turn the nodes into a graph. The following rules define which links should be part of responses.
  \begin{enumerate}
    \item Every endpoint has a link to itself.
    \item Every endpoint with services has links to its subservices.
    \item An item of a collection has a reference to itself.
    \item A collection has a link to the entities it is made out of.
    \item An entity that is part of a collection has a link to this collection.
    \item A paginated collection should reference it's next and previous page.
    \item Endpoints that provide responses with different attributes should advertise them.
  \end{enumerate}
  We can also enhance this graph with a few specific interservice connections like these:
    \begin{itemize}
    \item mrca -> path (you may want to see the path to the mrca)
    \item parent -> ancestor (view further than the direct parent)
    \item children -> subtree (view further than the direct children)
  \end{enumerate}

  While references of an entity to itself, like the \ty{self} reference or pagination references, are essential
  for the responses, they enhance this graph by any meaningful way. So we might as well omit them here and add
  them to the responses individually.
  A lot of these links will need to be slightly modified, to match the current request/ responds. We may define
  this basic graph now nevertheless.
#+end_export

#+begin_src go <<Link nodes, Pa. \ref{pa:api}>>=
  //<<Link subservices, Pa. \ref{pa:api}>>
  //<<Link collection entities, Pa. \ref{pa:api}>>
  //<<Link entity to collection, Pa. \ref{pa:api}>>
  //<<Interservice links, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  With the subservices we know that, each endpoint should be contained in the links of the \ty{rootDocument}.
  Then there \ty{accession} which is a subservice of \ty{accessions}; \ty{taxon}, \ty{ancestors}, \ty{children},
  \ty{parent}, \ty{rankDistribution} and \ty{subtree} which are subservices
  of \ty{taxa}. Lastly \ty{taxonAccessions}, \ty{fintac}, \ty{mrca}, \ty{neighbors} and \ty{path} are subservices of \ty{taxonomy}.
#+end_export

#+begin_src go <<Link subservices, Pa. \ref{pa:api}>>=
	rootDocL.Links["service"] = append(rootDocL.Links["service"], accessionsL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], accessionL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], taxaL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], taxonL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], ancestorsL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], childrenL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], parentL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], rankDistL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], subtreeL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], taxonomyL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], taxonAccessionsL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], fintacL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], mrcaL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], neighborsL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], pathL)
	accessionsL.Links["service"] = append(accessionsL.Links["service"], accessionL)
	taxaL.Links["service"] = append(taxaL.Links["service"], taxonL)
	taxaL.Links["service"] = append(taxaL.Links["service"], ancestorsL)
	taxaL.Links["service"] = append(taxaL.Links["service"], childrenL)
	taxaL.Links["service"] = append(taxaL.Links["service"], parentL)
	taxaL.Links["service"] = append(taxaL.Links["service"], rankDistL)
	taxaL.Links["service"] = append(taxaL.Links["service"], subtreeL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], taxonAccessionsL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], fintacL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], mrcaL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], neighborsL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], pathL)
#+end_src

#+begin_export latex
  Now to write the entities of the collections. There are basically two entities, which
  are the basis of almost all the collections. \ty{accession} is the base entity of \ty{accessions};
  \ty{taxon} is the base entity of \ty{taxa}, \ty{ancestors}, \ty{children}, \ty{subtree}, \ty{neighbors}
  and \ty{path}.
#+end_export

#+begin_src go <<Link collection entities, Pa. \ref{pa:api}>>=
	accessionsL.Links["entities"] = append(accessionsL.Links["entities"], accessionL)
	taxaL.Links["entities"] = append(taxaL.Links["entities"], taxonL)
	ancestorsL.Links["entities"] = append(ancestorsL.Links["entities"], taxonL)
	childrenL.Links["entities"] = append(childrenL.Links["entities"], taxonL)
	subtreeL.Links["entities"] = append(subtreeL.Links["entities"], taxonL)
	neighborsL.Links["entities"] = append(neighborsL.Links["entities"], taxonL)
	pathL.Links["entities"] = append(pathL.Links["entities"], taxonL)
#+end_src

#+begin_export latex
  We now link the entities to their collections. I believe we should link them to the basic
  collection only, i.e. \ty{taxon} to \ty{taxa}, as \ty{ancestors} for example is basically a filtered
  version of \ty{taxa}. I don't see a reason to link an entity to every specialized sub collection that
  it is part of.
#+end_export

#+begin_src go <<Link entity to collection, Pa. \ref{pa:api}>>=
	accessionL.Links["part-of"] = append(accessionL.Links["part-of"], accessionsL)
	taxonL.Links["part-of"] = append(taxonL.Links["part-of"], taxaL)
#+end_src

#+begin_export latex
  Handling pagination is easy again, as we already found all the collections.
#+end_export

#+begin_src go <<Link pagination, Pa. \ref{pa:api}>>=
	accessionsL.Links["previous"] = append(accessionsL.Links["previous"], accessionsL)
	taxaL.Links["previous"] = append(taxaL.Links["previous"], taxaL)
	ancestorsL.Links["previous"] = append(ancestorsL.Links["previous"], ancestorsL)
	childrenL.Links["previous"] = append(childrenL.Links["previous"], childrenL)
	subtreeL.Links["previous"] = append(subtreeL.Links["previous"], subtreeL)
	neighborsL.Links["previous"] = append(neighborsL.Links["previous"], neighborsL)
	pathL.Links["previous"] = append(pathL.Links["previous"], pathL)

  accessionsL.Links["next"] = append(accessionsL.Links["next"], accessionsL)
	taxaL.Links["next"] = append(taxaL.Links["next"], taxaL)
	ancestorsL.Links["next"] = append(ancestorsL.Links["next"], ancestorsL)
	childrenL.Links["next"] = append(childrenL.Links["next"], childrenL)
	subtreeL.Links["next"] = append(subtreeL.Links["next"], subtreeL)
	neighborsL.Links["next"] = append(neighborsL.Links["next"], neighborsL)
	pathL.Links["next"] = append(pathL.Links["next"], pathL)
#+end_src

#+begin_export latex
  All endpoints that offer different fields with their responses, respond with a taxon entity.
  So we just need to find all that do so and may add another link to themselves.
  The services are \ty{taxa}, \ty{taxon}, \ty{ancestors}, \ty{children}, \ty{parent},
  \ty{subtree}, \ty{mrca} and \ty{path}.
#+end_export

#+begin_src go <<Link entity fields, Pa. \ref{pa:api}>>=
	taxaL.Links["more fields"] = append(taxaL.Links["more fields"], taxaL)
	taxonL.Links["more fields"] = append(taxonL.Links["more fields"], taxonL)
	ancestorsL.Links["more fields"] = append(ancestorsL.Links["more fields"], ancestorsL)
	childrenL.Links["more fields"] = append(childrenL.Links["more fields"], childrenL)
	parentL.Links["more fields"] = append(parentL.Links["more fields"], parentL)
	subtreeL.Links["more fields"] = append(subtreeL.Links["more fields"], subtreeL)
	mrcaL.Links["more fields"] = append(mrcaL.Links["more fields"], mrcaL)
	pathL.Links["more fields"] = append(pathL.Links["more fields"], pathL)
#+end_src

#+begin_export latex
  Lastly we implement the interservice links. These are straightfoward as we specified them above.
  We should set the root variable as well, now that we are done with initializing the link graph.
#+end_export

#+begin_src go <<Interservice links, Pa. \ref{pa:api}>>=
	mrcaL.Links["path"] = append(mrcaL.Links["path"], pathL)
	parentL.Links["all ancestors"] = append(parentL.Links["all ancestors"], ancestorsL)
	childrenL.Links["all descendants"] = append(childrenL.Links["all descendants"], subtreeL)
  root = rootDocL
#+end_src



#+begin_export latex
  \subsection{rootDocument}
  Having declared all the endpoints we need to begin implementing them.
  We start with the \ty{rootDocument}. It just provides links
  to all the endpoints provided by this api.
  This is \ty{rootDocument}'s io:
  Params:
    Path:
      none
    Query:
      none
  Writes:
    \ty{ResponseBody[nil]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func rootDocument(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    out := ResponseBody[*any]{}
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Write \ty{rootDocument}'s links, Pa. \ref{pa:api}>>
    //<<Write output \ty{rootDocument}, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We use the \ty{contenttype} to check whether the server is providing a content type
  that would be accepted by the client. This is just a matter of
  calling the accept method and supplying the types, which are defined within the
  nodes.
#+end_export

#+begin_src go <<Check content types, Pa. \ref{pa:api}>>=
  _, _, err := contenttype.GetAcceptableMediaType(r, selfNode.Types)
  //<<React no match, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  If no type matches the available content types we respond with a 406 (Not Acceptable).
#+end_export

#+begin_src go <<React no match, Pa. \ref{pa:api}>>=
  if err != nil {
    w.WriteHeader(http.StatusNotAcceptable)
		w.Write([]byte("Server does not provide any of the accepted content types."))
    return
  }
#+end_src

#+begin_export latex
  This is a perfect application for the link graph we just created. We just iterate over
  \ty{service} links of root and parse them into the \ty{Link}, which provide json annotation.
  Parsing \ty{Node}s to \ty{Link}s is going to be common issue, so we might as well write a
  function for it. Let's call that function \ty{makeLink} for now and implement it later.
#+end_export

#+begin_src go <<Write \ty{rootDocument}'s links, Pa. \ref{pa:api}>>=
  out.Links = append(out.Links, root.makeLink("self", ""))
  for _, v := range root.Links["service"] {
    out.Links = append(out.Links, v.makeLink("service", ""))
  }
#+end_src

#+begin_export latex
  The \ty{makeLink} function takes a \ty{node}, the relation's name and a \ty{href}. If the \ty{href} is empty it uses the \ty{node}'s
  \ty{href} instead instead.
#+end_export

#+begin_src go <<Methods, Pa. \ref{pa:api}>>=
  func (node *Node) makeLink(rel, href string) Link {
    if href != "" {
      node.BasePath = href
    }
    types := []string{}
    for _, t := range node.Types {
      types = append(types, t.String())
    }
    return Link{
      Rel: rel,
      Href: node.BasePath,
      Action: node.Action,
      Types: types,
    }
  }
#+end_src

#+begin_export latex
  Writing the output is going to be a very common task. Every
  endpoint needs to do so. This function combines the steps
  that turn whatever we want to output into a manageable json.
  Before actually writing the response we should specify
  that we are writing in json format. We do this by setting
  the \ty{Content-type} field of the response header. The
  \ty{net/http} package writes the \ty{Content-Length} field
  on its own, so we don't need to do that.
  For pretty-printing json we need to add a buffer,
  encode the \ty{out} parameter and indent the result.
  We can't use \ty{MarshalIndent}, which does all of these
  steps, because it automatically encodes ampersand. This is a
  problem, when sending links.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func writeJsonOutput(w http.ResponseWriter, out any) {
	  w.Header().Set("Content-Type", jsonCt.String())
	  buf := &bytes.Buffer{}
	  encoder := json.NewEncoder(buf)
	  encoder.SetEscapeHTML(false)
	  encoder.SetIndent("", "  ")
	  err := encoder.Encode(out)
	  util.Check(err)
	  w.Write(buf.Bytes())
  }
#+end_src

#+begin_export latex
  Having implemented \ty{writeJsonOutput} we may use it to
  write the links of \tty{rootDocument}.
#+end_export

#+begin_src go <<Write output \ty{rootDocument}, Pa. \ref{pa:api}>>=
  writeJsonOutput(w, out)
#+end_src



#+begin_export latex
  \subsection{accessions}
  The endpoint \ty{accessions} used to be called levels.
  The following sections will closely resemble neverV1
  In our implementation of \ty{accessions} we extract the accessions, get
  their levels, and write the output.
  This is \ty{accessions}' io:
  Params:
    Query:
      accession_ids []string *required
      page          int
      page_size     int
      plain_data    bool
  Writes:
    ResponseBody[ []Accession ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func accessions(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Check parameters \ty{accessions}, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Extract accessions, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Look up levels, Pa. \ref{pa:api}>>
    //<<Store output \ty{accessions}, Pa. \ref{pa:api}>>
    //<<Add collection links, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  A lot of endpoints that we are defining here allow for or even require parameters.
  We are going to define a function that checks whether the required parameters
  exist.
#+end_export

#+begin_src go <<Check parameters \ty{accessions}, Pa. \ref{pa:api}>>=
  valid := checkParams(w, r, "accession_ids")
  if !valid {
    return
  }
#+end_src

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func checkParams(w http.ResponseWriter, r *http.Request, args ...string) bool {
    for _, arg := range args {
      p := r.URL.Query().Get(arg)
      if p == "" {
        //<<Write bad request, Pa. \ref{pa:api}>>
        return false
      }
    }
    return true
  }
#+end_src

#+begin_export latex
  When writing a bad request response, we want to set the 400 (Bad Request)
  HTTP response code and write some message for elaboration.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func writeBadRequestResp(w http.ResponseWriter, text string) {
    w.WriteHeader(http.StatusBadRequest)
    w.Write([]byte(text))
  }
#+end_src

#+begin_export latex
  In this case we say that the request is missing a required parameter.
#+end_export

#+begin_src go <<Write bad request, Pa. \ref{pa:api}>>=
  writeBadRequestResp(w, "Missing required parameter.")
#+end_src

#+begin_export latex
  The function we are using for the endpoints need to be variadic
  so in order to use the parameters passed to them in an orderly fashion
  we need to assign them and do a type assertion. In this block
  assign the db.
#+end_export

#+begin_src go <<Get db from args, Pa. \ref{pa:api}>>=
  neidb := args[0].(*tdb.TaxonomyDB)
#+end_src

#+begin_export latex
  If the query parameter \ty{plain_data} is passed, we need to change the response structure.
  In order to do that we extract the parameter here and act on it later on.
#+end_export

#+begin_src go <<Get plain param, Pa. \ref{pa:api}>>=
	strPlain := r.URL.Query().Get("plain_data")
	plain, err := strconv.ParseBool(strPlain)
	if err != nil {
		plain = false
	}
#+end_src

#+begin_export latex
  Accessions are passed as a comma-delimited string.
#+end_export

#+begin_src go <<Extract accessions, Pa. \ref{pa:api}>>=
  str := r.URL.Query().Get("accession_ids")
  accessions := strings.Split(str, ",")
#+end_src

#+begin_export latex
  We also need to import \ty{strings} to use \ty{Split}
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "strings"
#+end_src

#+begin_export latex
  Extractig the offset and size about extracting the parameters page
  and page size from the url and calculating the resulting offset.
  As there are a lot of endpoints that provide these parameters, we
  should make a function that does exactly that.
#+end_export

#+begin_src go <<Extract offset and size, Pa. \ref{pa:api}>>=
  offset, size := extractPaging(r)
#+end_src

#+begin_export latex
  Extracting the parameters is done just like any other query parameter.
  We set default values if page or page size are not defined or invalid.
  For conversion we need to import \ty{strconv}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "strconv"
#+end_src

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func extractPaging(r *http.Request) (offset, size int) {
    strPage := r.URL.Query().Get("page")
    strPageSize := r.URL.Query().Get("page_size")

    if strPageSize != "" {
      cSize, err := strconv.Atoi(strPageSize)
      size = cSize
      if err != nil {
        size = -1
      }
    } else {
        size = -1
    }
    if size != -1 && strPage != "" {
      page, err := strconv.Atoi(strPage)
      if err != nil {
        offset = 0
      } else {
        offset = page * size
      }
    } else {
      offset = 0
    }
  return
  }
#+end_src

#+begin_export latex
  We look up the level of each accession and store it.
  Ensuring size and offset of the output would be easiest by
  slicing the accessions at the end. I'm explicitly deciding against
  doing that as using them in compution is more perfomant. Sadly the code
  aesthetic suffers from that decision :(
#+end_export

#+begin_src go <<Look up levels, Pa. \ref{pa:api}>>=
  var data = []Accession{}

  if size == -1 {
    size = len(accessions)
  }
  for i := offset; i < min(offset + size, len(accessions)); i++ {
    accession := accessions[i]
    level, err := neidb.Level(accession)
    if err != nil {
      writeServerError(w, "fn accessions - Error while accessing neidb.Level", err)
      return
    }
    acc := Accession{Accession: accession, Level: level}
    if !plain {
      //<<Add link to accession object, Pa. \ref{pa:api}>>
    }
    data = append(data, acc)
  }
#+end_src

#+begin_export latex
  A server error is a response with a 5XX response code.
  We send it whenever there is an unexpected error on the
  server side. The user does not gain much info out of this,
  but we might, if we log it. So we should send an entry
  to the warning log.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func writeServerError(w http.ResponseWriter, internalMsg string, err error) {
    if err == nil {
      err = errors.New("No error passed")
    }
   	util.LogWarningDef(
		  util.WarningEntry{
			  Warning: fmt.Sprintf("Apiv2: Internal server error.\nMessage: %s\nErr: %s\nTrace: %s", internalMsg, err.Error(), debug.Stack()),
		})
  	w.WriteHeader(http.StatusInternalServerError)
  	w.Write([]byte("Internal server error."))
  }
#+end_src

#+begin_export latex
  We need to import the \ty{errors} and \ty{runtime/debug} packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "errors"
	"runtime/debug"
#+end_src

#+begin_export latex
  We convert our slice of accessions items to JSON and write it as our
  response. For this we need to import a few packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "encoding/json"
  "fmt"
  "github.com/evolbioinf/never/util"
#+end_src

#+begin_export latex
  We store the data in a variable called \ty{out}
#+end_export

#+begin_src go <<Store output \ty{accessions}, Pa. \ref{pa:api}>>=
  out := ResponseBody[[]Accession]{Data: data}
#+end_src

#+begin_export latex
  We need utility functions for working with links. As paths saved in a node are URI templates
  we need a function that exchanges a wildcard for an actual value.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func fillTemplate(node Node, pathParams map[string]string, queryParams map[string]string) string {
    for k := range pathParams {
      node.BasePath = strings.Replace(node.BasePath, "{"+k+"}", pathParams[k], 1)
    }
    i := 0
    for k := range queryParams {
      str := ""
      if i == 0 {
        str += "?"
      } else {
        str += "&"
      }
      node.BasePath = fmt.Sprintf("%s%s%s=%s", node.BasePath, str, k, queryParams[k])
      i++
    }
    return node.BasePath
  }
#+end_src

#+begin_export latex
  We need a function that makes getting nodes from the link graph easier.
  This function is \ty{getService}, which goes through all services and returns
  a pointer to a node with the correct name or nil.
#+end_export

#+begin_src go <<Methods, Pa. \ref{pa:api}>>=
  func (node *Node) getService (name string) *Node {
    services := node.Links["service"]
    idx := slices.IndexFunc(services, func(a Node) bool { return a.Name == name})

    if idx != -1 {
      return &services[idx]
    } else {
      return nil
    }
  }
#+end_src

#+begin_export latex
  We also need to import \ty{slices}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "slices"
#+end_src

#+begin_export latex
  Now we can write the links of the accession entity entity.
#+end_export

#+begin_src go <<Add link to accession object, Pa. \ref{pa:api}>>=
  accNode := *root.getService("accession")
	acc.Links = append(acc.Links, accNode.makeLink("self",
		fillTemplate(accNode, map[string]string{}, map[string]string{})))
#+end_src

#+begin_export latex
  A collection provides multiple links. It shows every of its registered endpoints, as well as
  a prev and next relations, when using pagination. Lastly a self reference is also part of the
  links.
#+end_export

#+begin_src go <<Add collection links, Pa. \ref{pa:api}>>=
  if !plain {
		var links []Link
    //<<Add endpoint's self link, Pa. \ref{pa:api}>>
    //<<Add pagination links, Pa. \ref{pa:api}>>
    //<<Add graph links, Pa. \ref{pa:api}>>
		out.Links = links
  }
#+end_src

#+begin_export latex
  For adding the self link we just take the \ty{self} node
  to make a \ty{Link} with the requested url and append it to the
  links.
#+end_export

#+begin_src go <<Add endpoint's self link, Pa. \ref{pa:api}>>=
    links = append(links, selfNode.makeLink("self", r.URL.String()))
#+end_src

#+begin_export latex
  Appending the graph links is a matter of iterating over the
  \ty{self} nodes and turning them into links using the correct
  relation in the process.
#+end_export

#+begin_src go <<Add graph links, Pa. \ref{pa:api}>>=
		for link := range selfNode.Links {
			for _, node := range selfNode.Links[link] {
				links = append(links, node.makeLink(link, ""))
			}
		}
#+end_src

#+begin_export latex
  Lastly we write the output using the \ty{writeJsonOutput} function.
  Using the plain parameter we decide whether to output the plain data
  or the out struct including all the links.
#+end_export

#+begin_src go <<Write json output, Pa. \ref{pa:api}>>=
  if plain {
    writeJsonOutput(w, out.Data)
  } else {
    writeJsonOutput(w, out)
  }
#+end_src



#+begin_export latex
  \subsection{accession}
  The endpoint \ty{accession} is used to retrieve single
  resources of the accessions collection.
  This is \ty{accession}'s io:
  Params:
    Path:
      none
    Query:
      plain_data bool
    Writes:
     \ty{ResponseBody[Accession]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func accession(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Look up level, Pa. \ref{pa:api}>>
    //<<Store output \ty{accession}, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  Looking up the level is the same as for an array, so we already know how to
  do that.
#+end_export

#+begin_src go <<Look up level, Pa. \ref{pa:api}>>=
  accession := r.PathValue("accession_id")
  level, err := neidb.Level(accession)
  if err != nil {
    writeServerError(w, "fn accession - Error while accessing neidb.Level", err)
    return
  }
  var data Accession
  var links []Link
  data = Accession{Accession: accession, Level: level}
  if !plain {
    //<<Add links \ty{accession}, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_src go <<Add links \ty{accession}, Pa. \ref{pa:api}>>=
  //<<Add endpoint's self link, Pa. \ref{pa:api}>>
  //<<Add graph links, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  We store the data in a variable called \ty{out}.
#+end_export

#+begin_src go <<Store output \ty{accession}, Pa. \ref{pa:api}>>=
  out := ResponseBody[Accession]{Data: data, Links: links}
#+end_src


#+begin_export latex
  \subsection{taxa}
  The enpoint \ty{taxa} takes as input the name of a taxon, whether to use
  the scientific name only, a matching mode, a page number, a page size
  and an identifier for the kind of fields that should be returned. It
  writes as response for each matching taxon the taxon ID, its parent's
  taxon ID, its scientific name and or its common name.

  This is \ty{taxa}'s io:
  Params:
    Path:
      none
    Query:
      name string
      scientific bool
      exact bool
      page []int
      page_size []int
      field_composite string
      plain_data bool
  Writes:
    ResponseBody[ []Partial<Taxon> ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func taxa(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    valid := checkParams(w, r, "name")
    if !valid {
      return
    }
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Extract taxi query, Pa. \ref{pa:api}>>
    //<<Execute taxi query, Pa. \ref{pa:api}>>
    //<<Store taxon output, Pa. \ref{pa:api}>>
    //<<Add taxa links, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We extract the taxon name, whether or not we are matching in exact
  mode and if we are looking for just the scientific name.
  If we are \emph{not} matching in exact mode, we bracket the
  name and the blanks it contains by wildcards.
#+end_export

#+begin_src go <<Extract taxi query, Pa. \ref{pa:api}>>=
  name := r.URL.Query().Get("name")
  strExact := r.URL.Query().Get("exact")
  strScientific := r.URL.Query().Get("scientific")
  //<<Get field composite, Pa. \ref{pa:api}>>

  exact, err := strconv.ParseBool(strExact)
  if err != nil {
    exact = false
  }
  scientific, err := strconv.ParseBool(strScientific)
  if err != nil {
    scientific = false
  }
  if !exact {
    name = strings.ReplaceAll(name, " ", "% %")
    name = "%" + name + "%"
  }
#+end_src

#+begin_export latex
  The field composite is a query parameter which determines
  the fields of the response. We call a function 
  \ty{parseFieldComposite}, to handle setting defaults etc.
  We are going to implement in the next step.
#+end_export

#+begin_src go <<Get field composite, Pa. \ref{pa:api}>>=
  fieldComposite := r.URL.Query().Get("field_composite")
  fieldComposite = parseFieldComposite(fieldComposite)
#+end_src

#+begin_export latex
  This function takes a string, which is supposed to be a field composite 
  descriptor. It checks whether the \ty{arg} matches any of the options 
  and returns \ty{default} if it does not.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func parseFieldComposite(arg string) string {
    availableComps := []string{"all", "default", "gen_count", "gen_count_rec", "id", "rank"}
    sort.Strings(availableComps)
    fmt.Println(availableComps)
    _, found := slices.BinarySearch(availableComps, arg)
    if !found {
      arg = "default"
    }
    return arg
  }
#+end_src

#+begin_export latex
  We iterate over the taxon IDs and for each one construct the taxon
  output and store it in our slice of taxa.
#+end_export

#+begin_src go <<Execute taxi query, Pa. \ref{pa:api}>>=
  var ids []int
  if scientific {
    ids, err = neidb.Taxids(name, size, offset)
    if err != nil {
      writeServerError(w, "fn taxa - Error while accessing neidb.Taxids", err)
      return
    }
  } else {
    ids, err = neidb.CommonTaxids(name, size, offset)
    if err != nil {
      writeServerError(w, "fn taxa - Error while accessing neidb.CommonTaxids", err)
      return
    }
  }
  data := []Taxon{}
  for _, id := range ids {
    //<<Construct taxon output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  Getting the data of a taxon is something we are doing frequently.
  This means we write a function for this behaviour. \ty{getTaxonData}
  takes an id, whether the data should be plain, i.e. without links
  and the composite to create.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func getTaxonData(id int, plain bool, fieldComposite string, neidb *tdb.TaxonomyDB) (tax Taxon, err error) {
    tax.TaxId = id
    if fieldComposite == "gen_count" || fieldComposite == "all" {
      //<<Get raw genome counts, Pa. \ref{pa:api}>>
    }
    if fieldComposite == "gen_count_rec" || fieldComposite == "all" {
      //<<Get rec genome counts, Pa. \ref{pa:api}>>
    }
    if fieldComposite == "rank" || fieldComposite == "all" {
      //<<Retrieve rank fields, Pa. \ref{pa:api}>>
    }
    if fieldComposite == "default" || fieldComposite == "all" {
      //<<Retrieve default fields, Pa. \ref{pa:api}>>
    }
    if fieldComposite == "all" {
      //<<Retrieve all remaining fields, Pa. \ref{pa:api}>>
    }
    if !plain {
      //<<Add entity Link, Pa. \ref{pa:api}>>
    }
    return
  }
#+end_src

#+begin_src go <<Get raw genome counts, Pa. \ref{pa:api}>>=
  var raw []GenomeCount
  for _, level := range tdb.AssemblyLevels() {
    count, err := neidb.NumGenomes(id, level)
    if err != nil {
      writeServerError(w, "Error while executing neidb.NumGenomes", err)
      return
    }
    gc := GenomeCount{Count: count, Level: level}
    raw = append(raw, gc)
  }
  tax.RawGenomeCount = raw
#+end_src

#+begin_export latex
  We look up the recursive genome counts across the assembly
  levels.
#+end_export

#+begin_src go <<Get rec genome counts, Pa. \ref{pa:api}>>=
  var rec []GenomeCount
  for _, level := range tdb.AssemblyLevels() {
    count, err := neidb.NumGenomesRec(id, level)
    if err != nil {
      writeServerError(w, "Error while executing neidb.NumGenomesRec", err)
      return
    }
    gc := GenomeCount{Count: count, Level: level}
    rec = append(rec, gc)
  }
  tax.RecGenomeCount = rec
#+end_src

#+begin_export latex
  We get the rank specific data.
#+end_export

#+begin_src go <<Retrieve rank fields, Pa. \ref{pa:api}>>=
  rank, err := neidb.Rank(id)
  if err != nil {
    writeServerError(w, "Error while executing neidb.Rank", err)
    return
  }
  tax.Rank = rank
#+end_src

#+begin_export latex
  We get the default data.
#+end_export

#+begin_src go <<Retrieve default fields, Pa. \ref{pa:api}>>=
  //<<Get names, Pa. \ref{pa:api}>>
  //<<Get parent, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  We look up the taxon's scientific and common names with error
  checking.
#+end_export

#+begin_src go <<Get names, Pa. \ref{pa:api}>>=
  sciName, err := neidb.Name(id)
  if err != nil {
    writeServerError(w, "Error while executing neidb.Name", err)
    return
  }
  tax.Name = sciName
  comName, err := neidb.CommonName(id)
  if err != nil {
    writeServerError(w, "Error while executing neidb.CommonName", err)
    return
  }
  tax.CommonName = comName
#+end_src

#+begin_export latex
  We look up the parent taxon and check the error.
#+end_export

#+begin_src go <<Get parent, Pa. \ref{pa:api}>>=
  parent, err := neidb.Parent(id)
  if err != nil {
    writeServerError(w, "Error while executing neidb.Parent", err)
    return
  }
  tax.Parent = parent
#+end_src

#+begin_export latex
  We get the all the remaining data.
#+end_export

#+begin_src go <<Retrieve all remaining fields, Pa. \ref{pa:api}>>=
  //<<Is the taxon a leaf? Pa. \ref{pa:api}>>
  //<<Get images, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  We determine whether the taxon is a leaf.
#+end_export

#+begin_src go <<Is the taxon a leaf? Pa. \ref{pa:api}>>=
  isLeaf, err := neidb.IsLeaf(id)
  if err != nil {
    writeServerError(w, "Error while executing neidb.isLeaf", err)
    return
  }
  tax.IsLeaf = isLeaf
#+end_src

#+begin_export latex
  We look up the raw genome counts across the assembly
  levels.
#+end_export

#+begin_export latex
  We look up the images associated with the taxon.
#+end_export

#+begin_src go <<Get images, Pa. \ref{pa:api}>>=
  var neiImages []Image
  images, err := neidb.Images(id)
  if err != nil {
    writeServerError(w, "Error while executing neidb.Images", err)
    return
  }
  for _, image := range images {
    i := Image{Id: image.Id,
      Url: image.Url,
      Attribution: image.Attribution}
    neiImages = append(neiImages, i)
  }
#+end_src

#+begin_export latex
  Lastly we add the self link of the entity. We search the link graph for the
  \ty{taxon} service, and replace the \ty{taxon_id} and \ty{field_composite}
  with their current values.
#+end_export

#+begin_src go <<Add entity Link, Pa. \ref{pa:api}>>=
	taxNode := *root.getService("taxon")
	tax.Links = append(tax.Links, taxNode.makeLink("self", fillTemplate(
		taxNode,
		map[string]string{"taxon_id": strconv.Itoa(id)},
		map[string]string{"field_composite": fieldComposite},
	)))
#+end_src

#+begin_export latex
  We call get \ty{getTaxonData}, to get data on our taxon
  using the correct composite of fields and links.
#+end_export

#+begin_src go <<Construct taxon output, Pa. \ref{pa:api}>>=
  tax, err := getTaxonData(id, plain, fieldComposite, neidb)
  if err != nil {
    writeServerError(w, "Error from getTaxonData", err)
    return
  }
  data = append(data, tax)
#+end_src

#+begin_export latex
  We store the data in \ty{out}.
#+end_export

#+begin_src go <<Store taxon output, Pa. \ref{pa:api}>>=
  out := ResponseBody[[]Taxon]{Data: data}
#+end_src

#+begin_export latex
  \ty{taxa} gets a self link, pagination, links to its services
  and a link for all other available composites.
#+end_export

#+begin_src go <<Add taxa links, Pa. \ref{pa:api}>>=
  if !plain {
		var links []Link
    //<<Add endpoint's self link, Pa. \ref{pa:api}>>
    //<<Add pagination links, Pa. \ref{pa:api}>>
    //<<Add graph links, Pa. \ref{pa:api}>>
    //<<Add field composite links, Pa. \ref{pa:api}>>
		out.Links = links
  }
#+end_src

#+begin_export latex
  Every endpoint returning taxon entities is faced with
  adding links for the available composites.
  This means we write a function that does this for us.
  The function \ty{getTaxonCompositeLinks} takes the node
  of the endpoint, the \ty{fieldComposite} currently in use
  and the request. It defines all available composites,
  iterates through them and creates a matching link.
  We use a dereferenced variable to access the \ty{url},
  so we don't alter the passed parameter.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func getTaxonCompositeLinks(node *Node, fieldComposite string, r *http.Request) (links []Link) {
    available := []string{"id", "rank", "gen_count", "gen_count_rec", "default", "all"}
    queryName := "field_composite"
    u := *r.URL
    for _, v := range available {
      if v != fieldComposite {
        //<<Create composite link, Pa. \ref{pa:api}>>
      }
    }
    return
  }
#+end_src

#+begin_export latex
  When creating the new link, we want to keep the requested
  Link as it is, except for the \ty{field_composite} parameter
  of the query. We can make use of the \ty{Query} map used in
  the request. By setting and resetting the \ty{field_composite}
  parameter, we can render the link exactly as it was before,
  except for the swapped \ty{field_composite}.
#+end_export

#+begin_src go <<Create composite link, Pa. \ref{pa:api}>>=
	q := u.Query()
	q.Set(queryName, v)
	u.RawQuery = q.Encode()
  links = append(links, node.makeLink("more fields", u.String()))
#+end_src

#+begin_export latex
  Now we need to call the function we just implemented.
#+end_export

#+begin_src go <<Add field composite links, Pa. \ref{pa:api}>>=
  links = append(links, getTaxonCompositeLinks(selfNode, fieldComposite, r)...)
#+end_src



#+begin_export latex
  \subsection{taxon}
  The enpoint \ty{taxon} takes as input the taxon id of a taxon and
  an identifier for the kind of fields that should be returned. It
  writes as response for each matching taxon the taxon ID, its parent's
  taxon ID, its scientific name and or its common name.

  This is \ty{taxon}'s io:
  Params:
    Path:
      taxon_id id
    Query:
      field_composite string
      plain_data bool
  Writes:
    ResponseBody[ Partial<Taxon> ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func taxon(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Get field composite, Pa. \ref{pa:api}>>
    //<<Get taxon data, Pa. \ref{pa:api}>>
    //<<Add links taxon entity, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  Getting the taxon data is easy with the \ty{getTaxonData}
  function. We don't want links for single entity responses
  so we just pass a \ty{true} instead of \ty{plain} to
  \ty{getTaxonData}.
#+end_export

#+begin_src go <<Get taxon data, Pa. \ref{pa:api}>>=
  //<<Parse taxon id, Pa. \ref{pa:api}>>
  tax, err := getTaxonData(taxId, true, fieldComposite, neidb)
  if err != nil {
    writeServerError(w, "fn taxon - Error from getTaxonData", err)
    return
  }
  var out ResponseBody[Taxon]
  out.Data = tax
#+end_src

#+begin_export latex
  We extract the taxon id as a string via the \ty{PathValue}
  function. Expecting an integer, we convert the string and
  return an error response, if it was malformed.
#+end_export

#+begin_src go <<Parse taxon id, Pa. \ref{pa:api}>>=
  taxIdStr := r.PathValue("taxon_id")
  taxId, err := strconv.Atoi(taxIdStr)
  if err != nil {
    writeBadRequestResp(w, "Taxon id is not an integer.")
    return
  }
#+end_src

#+begin_export latex
  We also wrote a function for adding links to taxa entities, so this
  is easy as well.
#+end_export

#+begin_src go <<Add links taxon entity, Pa. \ref{pa:api}>>=
  var links []Link
  links = append(links, getTaxonCompositeLinks(selfNode, fieldComposite, r)...)
  //<<Add endpoint's self link, Pa. \ref{pa:api}>>
  //<<Add graph links, Pa. \ref{pa:api}>>
  out.Links = links
#+end_src



#+begin_export latex
  \subsection{ancestors}
  The endpoint \ty{ancestors} runs \ty{ants} as if it were a system call. 
  Given the id of a taxon, \ty{ants} retrieves all ancestors of a taxon. 
  The program does not provide a wide variety in call arguments, so 
  the only thing we need to pass is the taxon's id.

  This is \ty{ancestors}' io:
  Params:
    Path:
      taxon_id id
    Query:
      none
  Writes:
    string

#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func ancestors(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get taxon id, Pa. \ref{pa:api}>>
    //<<Get db path, Pa. \ref{pa:api}>>
    //<<Run \ty{ants}, Pa. \ref{pa:api}>>
    //<<Write plain output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  The taxon's id is stored in as a path parameter.
  A system call takes only strings as input, so we
  don't need to convert the path parameter.
#+end_export

#+begin_src go <<Get taxon id, Pa. \ref{pa:api}>>=
  taxIdStr := r.PathValue("taxon_id")
#+end_src

#+begin_export latex
  The programs, or rather packages, we are calling use a custom 
  cli centric error handling. While this is good for the programs,
  it is not great for web interfaces. We should check datastructures
  of inputs and such, to use our own error handling instead of 
  the packages. For this we create functions that check whether
  a parameter is of a certain datatype. First up are integers.
  We need them to check taxon ids with the \ty{ants} call.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func checkParamInt(w http.ResponseWriter, param string) bool {
    _, err := strconv.Atoi(param)
    if err != nil {
      writeBadRequestResp(w, "Malformed integer.")
    }
    return err != nil
  }
#+end_src

#+begin_export latex
  Now we call \ty{checkParamInt}
#+end_export

#+begin_src go <<Validate user input \ty{ancestors}, Pa. \ref{pa:api}>>=
  valid := checkParamInt(w, taxIdStr)
  if !valid {
    return
  }
#+end_src

#+begin_export latex
  As \ty{ancestors} is one of the endpoints that don't need the
  database - not making any calls to it, it instead receives the
  path to the database file.
#+end_export

#+begin_src go <<Get db path, Pa. \ref{pa:api}>>=
  dbPath := args[0].(string)
#+end_src

#+begin_export latex
  The programs, rather packages, are called via their \ty{Run} function.
  Running a program this way is a bit obscure, but it is much safer, than
  calling it via the shell. To bundle everything a call like this needs
  to do, which is quite a lot, we wrap it in a function that we are going
  to implement in a moment.
#+end_export

#+begin_src go <<Run \ty{ants}, Pa. \ref{pa:api}>>=
  callArgs := []string{"./ants", taxIdStr, dbPath}
  out, errMsg := callPackage(callArgs, ants.Run)
  if len(errMsg) > 0 {
    writeServerError(w, "fn ancestors - Error while calling package ants: " + string(errMsg), nil)
    return
  }
#+end_src

#+begin_export latex
  We need to import \ty{ants}
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "github.com/evolbioinf/neighbors/ants"
#+end_src

#+begin_export latex
  Calling a \ty{neighbors} program/ package via \ty{Run} needs some
  prerequisites. The packages depent on call arguments, as does the
  \ty{flag} package they are using. So we need to provide those.
  Then we also need to redefine \ty{stdout} and \ty{stderr}, to get
  the package's output. Lastly we need to wrap all of it in a mutex.
  This is necessary as we read, set and reset server wide variables
  during these calls.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func callPackage(callArgs []string, runFn func()) (out, errMsg []byte) {
    //<<Lock program mutex, Pa. \ref{pa:api}>>
    //<<Set call args, Pa. \ref{pa:api}>>
    //<<Set flag commandline, Pa. \ref{pa:api}>>
    //<<Set stdout and stderr, Pa. \ref{pa:api}>>
    //<<Call program, Pa. \ref{pa:api}>>
    //<<Reset stdout and stderr, Pa. \ref{pa:api}>>
    //<<Reset flag commandline, Pa. \ref{pa:api}>>
    //<<Reset call args, Pa. \ref{pa:api}>>
    //<<Unlock program mutex, Pa. \ref{pa:api}>>
    return
  }
#+end_src

#+begin_export latex
  First we need to import the \ty{sync} package
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "sync"
#+end_src

#+begin_export latex
  Then we declare a mutex for program calls.
#+end_export

#+begin_src go <<Variables, Pa. \ref{pa:api}>>=
  var progMu sync.Mutex
#+end_src

#+begin_export latex
  Now we may lock it on entering the function.
#+end_export

#+begin_src go <<Lock program mutex, Pa. \ref{pa:api}>>=
  progMu.Lock()
#+end_src

#+begin_export latex
  We should save the current call arguments
  before setting the new ones.
#+end_export

#+begin_src go <<Set call args, Pa. \ref{pa:api}>>=
  serverArgs := os.Args
  os.Args = callArgs
#+end_src

#+begin_export latex
  The same goes for the current \ty{flag.CommandLine}
#+end_export

#+begin_src go <<Set flag commandline, Pa. \ref{pa:api}>>=
  oldFlags := flag.CommandLine
  flag.CommandLine = flag.NewFlagSet(os.Args[0], flag.ContinueOnError)
#+end_src

#+begin_export latex
  Using \ty{flag} requires importing it.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "flag"
#+end_src

#+begin_export latex
  We create pipes for redirecting \ty{stdout} and \ty{stderr}.
  This again allows us to read whatever the packages write
  as if we were doing system calls. We first save the old
  pointers for \ty{stdout} and \ty{stderr}. Creating a new pipe
  lets us set new ones. We report an error if it occurs.
#+end_export

#+begin_src go <<Set stdout and stderr, Pa. \ref{pa:api}>>=
	prevOut := os.Stdout
	rOut, wOut, err := os.Pipe()
	if err != nil {
		errMsg = append(errMsg, []byte("Error while creating stdout pipe: " + err.Error())...)
	} else {
	  os.Stdout = wOut
  }

  prevErr := os.Stderr
	rErr, wErr, err := os.Pipe()
	if err != nil {
		errMsg = append(errMsg, []byte("Error while creating stderr pipe: " + err.Error())...)
	}
	os.Stderr = wErr
#+end_src

#+begin_export latex
  Now we may call the program, if there is no error. 
  The program call is already nicely wrapped for us in the \ty{runFn} function.
#+end_export

#+begin_src go <<Call program, Pa. \ref{pa:api}>>=
  if err == nil {
    runFn()
  }
#+end_src

#+begin_export latex
  We begin resetting everything. First up the \ty{stdout} and \ty{stderr}.
  After resetting them, we may read their outputs.
#+end_export

#+begin_src go <<Reset stdout and stderr, Pa. \ref{pa:api}>>=
  os.Stdout = prevOut
  os.Stderr = prevErr
  if wOut != nil {
    err = wOut.Close()
    if err != nil {
      errMsg = append(errMsg, []byte("Error while closing stdout pipe: " + err.Error())...)
    }
  }
  if wErr != nil {
    wErr.Close()
    if err != nil {
      errMsg = append(errMsg, []byte("Error while closing stderr pipe: " + err.Error())...)
    }
  }

  var outBuf, errBuf bytes.Buffer
	_, err = io.Copy(&outBuf, rOut)
	_, err = io.Copy(&errBuf, rErr)
	out = outBuf.Bytes()
	errMsg = append(errMsg, errBuf.Bytes()...)
#+end_src

#+begin_export latex
  We need to import \ty{io} for copying
  the data to a buffer.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "io"
#+end_src

#+begin_export latex
  Resetting the \ty{flag.CommandLine} is less effort.
#+end_export

#+begin_src go <<Reset flag commandline, Pa. \ref{pa:api}>>=
	flag.CommandLine = oldFlags
#+end_src

#+begin_export latex
  Then we reset the call arguments.
#+end_export

#+begin_src go <<Reset call args, Pa. \ref{pa:api}>>=
  os.Args = serverArgs
#+end_src

#+begin_export latex
  Lastly we unlock the mutex.
#+end_export

#+begin_src go <<Unlock program mutex, Pa. \ref{pa:api}>>=
  progMu.Unlock()
#+end_src


#+begin_export latex
  We need to implement a new function for writing plain data.
  Let's call it \ty{writePlainOutput}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func writePlainOutput(w http.ResponseWriter, out []byte) {
    w.Header().Set("Content-Type", plainCt.String())
    fmt.Fprintf(w, "%s", out)
  }
#+end_src

#+begin_src go <<Write plain output, Pa. \ref{pa:api}>>=
  writePlainOutput(w, out)
#+end_src



#+begin_export latex
  \subsection{children}
  The service \ty{children} takes as argument a taxon id and returns its
  children as a slice of their taxon id. We implement the service by
  first getting the taxon id and the corresponding children.
  Then we iterate over the children and construct the output object
  for each one, before we write the output.

  This is \ty{children}'s io:
  Params:
    Path:
      taxon_id int
    Query:
      field_composite string
      page            int
      page_size       int
      plain_data      bool
  Writes:
    ResponseBody[ []Partial<Taxon> ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func children(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Parse taxon id, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Get field composite, Pa. \ref{pa:api}>>
    //<<Execute children query, Pa. \ref{pa:api}>>
    //<<Store taxon output, Pa. \ref{pa:api}>>
    //<<Define link parameters, Pa. \ref{pa:api}>>
    //<<Add filled taxa links, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  There is a function called \ty{Children} in \ty{tdb}, which returns
  a slice of integers containing taxon ids. We need to account for
  pagination, so we add the limit and offset into the loop.
#+end_export

#+begin_src go <<Execute children query, Pa. \ref{pa:api}>>=
    children, err := neidb.Children(taxId)
	  if err != nil {
      writeServerError(w, "fn children - Error while executing neidbChildren", err)
      return
    }
    if size == -1 {
      size = len(children)
    }
    data := []Taxon{}
    for i := offset; i < min(offset + size, len(children)); i++ {
      id := children[i]
		  //<<Construct taxon output, Pa. \ref{pa:api}>>
	  }
#+end_src

#+begin_export latex
  While we don't have any query parameters we need to add to the
  template, there is a path parameter that needs handling.
#+end_export

#+begin_src go <<Define link parameters, Pa. \ref{pa:api}>>=
  pathParams := map[string]string{"taxon_id": taxIdStr}
  queryParams := map[string]string{}
#+end_src

#+begin_export latex
  Now we need to add our usual links, keeping in mind to fill
  the templates with the requested parameters.
#+end_export

#+begin_src go <<Add filled taxa links, Pa. \ref{pa:api}>>=
  if !plain {
		var links []Link
    //<<Add endpoint's self link, Pa. \ref{pa:api}>>
    //<<Add pagination links, Pa. \ref{pa:api}>>
    for link := range selfNode.Links {
			for _, node := range selfNode.Links[link] {
				links = append(links, node.makeLink(link, fillTemplate(node, pathParams, queryParams)))
			}
		}
    //<<Add field composite links, Pa. \ref{pa:api}>>
		out.Links = links
  }
#+end_src



#+begin_export latex
  \subsection{parent}
  The service \ty{parent} takes as argument a taxon id and returns its
  parent.

  This is \ty{parent}'s io:
  Params:
    Path:
      taxon_id int
    Query:
      field_composite string
      plain_data bool
  Writes:
    ResponseBody[ []Partial<Taxon> ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func parent(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Parse taxon id, Pa. \ref{pa:api}>>
    //<<Get field composite, Pa. \ref{pa:api}>>
    //<<Execute parent query, Pa. \ref{pa:api}>>
    //<<Add links taxon entity, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We call the \ty{Parent} function from \ty{tdb} and
  use its response to get the requested data on the parent.
#+end_export

#+begin_src go <<Execute parent query, Pa. \ref{pa:api}>>=
  parent, err := neidb.Parent(taxId)
  tax, err := getTaxonData(parent, true, fieldComposite, neidb)
  if err != nil {
    writeServerError(w, "fn parent - Error from getTaxonData", err)
    return
  }
  var out ResponseBody[Taxon]
  out.Data = tax
#+end_src



#+begin_export latex
  \subsection{rankDistribution}
  The service \ty{rankDistribution} takes as argument a taxon id and returns the
  distribution of genomes among taxonomic ranks. \ty{rankDistribution} executes a
  system call to the \ty{ranks} program. This program takes the options \ty{-L}
  which provides a list of assembly-levels and \ty{-g} which provides a file
  of genome accessions. \ty{rankDistribution} writes its response in plain text.

  This is \ty{rankDistribution}'s io:
  Params:
    Path:
      taxon_id int
    Query:
      assembly_levels []string
      list_genomes    bool
      tabular_output  bool
  Body:
    File
  Writes:
    string
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func rankDistribution(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get taxon id, Pa. \ref{pa:api}>>
    //<<Handle arguments \ty{rankDistribution}, Pa. \ref{pa:api}>>
    //<<Validate user input \ty{rankDistribution}, Pa. \ref{pa:api}>>
    //<<Call \ty{rankDistribution}, Pa. \ref{pa:api}>>
    //<<Write plain output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  Handling the arguments is about checking the data submitted via the form
  and via the query parameters. We need to get all this data, combine and
  prepare it, so we can use it, as if all it were local.
#+end_export

#+begin_src go <<Handle arguments \ty{rankDistribution}, Pa. \ref{pa:api}>>=
  //<<Get db path from parameters, Pa. \ref{pa:api}>>
  //<<Retrieve query parameters \ty{rankDistribution}, Pa. \ref{pa:api}>>
  //<<Handle file, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  \ty{ranks} takes the parameters \ty{L}, \ty{g}, \ty{l} and \ty{t}.
  We retrieve \ty{L}, \ty{l} and \ty{t} from the query of the url and add them to the
  call arguments, if they exist. The data for \ty{g} is not contained in the query.
  We are going to retrieve it later on.
#+end_export

#+begin_src go <<Retrieve query parameters \ty{rankDistribution}, Pa. \ref{pa:api}>>=
	ranksArgs := []string{"./ranks"}
	levels := r.URL.Query().Get("assembly_levels")
  if levels != "" {
		ranksArgs = append(ranksArgs, "-L", levels)
  }

	listStr := r.URL.Query().Get("list_genomes")
	l, err := strconv.ParseBool(listStr)
  if listStr != "" && err != nil {
    writeBadRequestResp(w, "list_genomes argument is not a bool.")
    return
  } else if l {
		ranksArgs = append(ranksArgs, "-l")
  }

  tabStr := r.URL.Query().Get("tabular_output")
	t, err := strconv.ParseBool(tabStr)
  if tabStr != "" && err != nil {
    writeBadRequestResp(w, "tabular_output argument is not a bool.")
    return
  } else if t {
		ranksArgs = append(ranksArgs, "-t")
  }
#+end_src

#+begin_export latex
  When calling \ty{ranks} remotely we want to use the database.
  In order to do so we need to specify it via a call argument.
  The path of the database is specified as the first parameter
  passed to this function.
#+end_export

#+begin_src go <<Get db path from parameters, Pa. \ref{pa:api}>>=
  dbPath := args[0].(string)
#+end_src

#+begin_export latex
  Handling files is a quite tedious process, which we need to do
  for at least one more service. This means we should write a function
  for this behaviour. The services take a different amount of files.
  We should add a parameters that check for these bounds.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func filesFromFormData(w http.ResponseWriter, r *http.Request, minFiles, maxFiles int) (paths []string, err error) {
    //<<Validate form, Pa. \ref{pa:api}>>
    //<<Sort files, Pa. \ref{pa:api}>>
    //<<Create temporary files, Pa. \ref{pa:api}>>
    return
  }
#+end_src

#+begin_export latex
  There are two steps in validating the content of a multipart form.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func validateMultipartForm(w http.ResponseWriter, r *http.Request, minFiles, maxFiles int) (err error) {
    //<<Parse form data, Pa. \ref{pa:api}>>
    //<<Check for files, Pa. \ref{pa:api}>>
    return nil
  }
#+end_src

#+begin_export latex
  Accessing the data of a multipart form request, requires
  a parsing step. In this the format of provided is checked
  and loaded into memory. We may define the amount space
  we are willing to allocate for this data, I've decided
  on 3MB, the remaining data will be stored on the hard
  drive. We return a 400 (Bad Request) if the data is
  malformed.
#+end_export

#+begin_src go <<Parse form data, Pa. \ref{pa:api}>>=
	err = r.ParseMultipartForm(3_000_000)
	if err != nil {
    writeBadRequestResp(w, "Malformed multipart form request.")
		return err
	}
#+end_src

#+begin_export latex
  We return a 400 (Bad Request), if the number of files
  exceeds or falls short of the required range.
#+end_export

#+begin_src go <<Check for files, Pa. \ref{pa:api}>>=
	if len(r.MultipartForm.File) < minFiles {
    writeBadRequestResp(w, fmt.Sprintf("Provide at least %d file(s).", minFiles))
		return errors.New("not enough files in body")
	}
  if maxFiles != -1 && len(r.MultipartForm.File) > maxFiles {
    writeBadRequestResp(w, fmt.Sprintf("Too many files. This service takes a maximum of %d file(s) per request.", maxFiles))
		return errors.New("too many files in body")
	}
#+end_src

#+begin_export latex
  Now we may just call the validation function to check
  the incoming form. The validation function already
  writes an error response, so in case of an error
  we simply stop processing here. We also do this, if
  there are no files within the request.
#+end_export

#+begin_src go <<Validate form, Pa. \ref{pa:api}>>=
  err = validateMultipartForm(w, r, minFiles, maxFiles)
  if err != nil || len(r.MultipartForm.File) == 0 {
    return
  }
#+end_src

#+begin_export latex
  The files should be sorted by some criterium.
  We use the keys that indicate the files to do so.
#+end_export

#+begin_src go <<Sort files, Pa. \ref{pa:api}>>=
	keys := []string{}
	for key := range r.MultipartForm.File {
		keys = append(keys, key)
	}
	sort.Strings(keys)
#+end_src

#+begin_export latex
  We need to import the \ty{sort} package for this.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "sort"
#+end_src

#+begin_export latex
  The local programs take filenames as input. This means
  we have to have files to make the program call. For this I
  thought of the following: We extract the file data from
  the request, create a temporary file and save it's path,
  write the data to this temporary file, use the paths for
  the program call and remove the temporary files afterwards.
  So these are the steps we are going to follow.
#+end_export

#+begin_src go <<Create temporary files, Pa. \ref{pa:api}>>=
  for i, key := range keys {
		files := r.MultipartForm.File[key]
		if len(files) > 0 {
	  //<<Extract request's file data, Pa. \ref{pa:api}>>
	  //<<Open temporary file, Pa. \ref{pa:api}>>
	  //<<Write to temporary file, Pa. \ref{pa:api}>>
		}
	}
#+end_src

#+begin_export latex
  We expect that each key contains exactly one file. When
  accesing the \ty{files} variable, we get pointers to the
  header of a file. Now working with this is rather similar
  to working with any other file. We may open the file via
  the header, read it's data to a byte slice and close it again.
#+end_export

#+begin_src go <<Extract request's file data, Pa. \ref{pa:api}>>=
	h := *files[0]
  var rf multipart.File
	rf, err = h.Open()
  if err != nil {
    writeServerError(w, "Error while opening multipart file", err)
    return
  }
	b := make([]byte, h.Size)
	rf.Read(b)
	rf.Close()
#+end_src

#+begin_export latex
  We need to import \ty{mime/multipart}
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
	"mime/multipart"
#+end_src

#+begin_export latex
  In order to open a file we need to define where this file
  should be stored. This name should include the name of the
  package, a \ty{temp} marker and postpend something making
  the filename unique. We are going to postpend a timestamp.
  Making this file temporary is necessary
  to avoid flooding the hard drive. Sadly we can't make a
  deferred remove call right now, as we are in a subfunction.
  This means the calling function needs to take care of the
  file removal.
  To open/create the file we call \ty{os.Open} adding
  the create and write only flags. The \ty{0644} defines unix
  permissions for a file. \ty{0644} means the owner may execute
  read and write operation, while everyone else has read only rights.
#+end_export

#+begin_src go <<Open temporary file, Pa. \ref{pa:api}>>=
	path := "apiv2_temp_" + strconv.Itoa(i) + strconv.Itoa(time.Now().Nanosecond())
  paths = append(paths, path)
	var tf * os.File
  tf, err = os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0644)
  if err != nil {
    writeServerError(w, "Error while opening temporary file", err)
    return
  }
#+end_src

#+begin_export latex
  We need to import the \ty{os} and \ty{time} packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "os"
  "time"
#+end_src

#+begin_export latex
  We create a new buffer storing the bytes we just read,
  write them to our temporary file and close the file afterwards.
  It's necessary to close the file right now, instead of deferring it,
  so that other processes may read it.
#+end_export

#+begin_src go <<Write to temporary file, Pa. \ref{pa:api}>>=
	buffer := bytes.NewBuffer(b)
	buffer.WriteTo(tf)
	tf.Close()
#+end_src

#+begin_export latex
  The buffers require importing the \ty{bytes} package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "bytes"
#+end_src

#+begin_export latex
  We need to do this file handling whenever the requests conten type is
  \ty{multipart/form-data}. Checking against this requires creating a
  struct containing the content types information. We are going to use
  this more than once, so we add it to the globally defined content types.
#+end_export

#+begin_src go <<Content types, Pa. \ref{pa:api}>>=
  var multipartCt = contenttype.MediaType{Type: "multipart", Subtype: "form-data"}
#+end_src

#+begin_export latex
  Now we can call \ty{filesFromFormData}, if the content type requires it.
  We also need to make a deferred call to \ty{os.Remove} to make the
  files temporary.
#+end_export

#+begin_src go <<Handle file, Pa. \ref{pa:api}>>=
	ct, err := contenttype.GetMediaType(r)
	if ct.EqualsMIME(multipartCt) {
    paths, err := filesFromFormData(w, r, 0, 1)
    if err != nil {
      return
    }
    if len(paths) > 0 {
	  	ranksArgs = append(ranksArgs, "-g", paths[0])
      for _, p := range paths {
        defer os.Remove(p)
      }
    }
	}
#+end_src

#+begin_export latex
  We pass a taxon id, the assembly levels and a bunch of bools to \ty{ranks}.
  We already wrote a function for validating integers like a taxon id. The assembly
  levels are defined by a set of strings we should check against. If one of the
  passed parameters is not part of the available levels, we return an error response.
  The bools don't need extra checking, as the input never actually reaches arguments.
#+end_export

#+begin_src go <<Validate user input \ty{rankDistribution}, Pa. \ref{pa:api}>>=
  valid := checkParamInt(w, taxIdStr)
  if !valid {
    return
  }
  valid = checkParamLevels(w, levels)
  if !valid {
    return
  }
#+end_src

#+begin_export latex
  We iterate over all passed levels and check whether they are contained
  by the assembly levels available at \ty{tdb}. We use a binary search
  to check for containment. The amount of available levels is constant, 
  which makes the total containment check run in O(N) anyways, but 
  using a binary search might still reduce the total processing time.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func checkParamLevels(w http.ResponseWriter, levels string) bool {
    if levels != "" {
	    levelsSplit := strings.Split(levels, ",")
      availableLevels := tdb.AssemblyLevels()
      sort.Strings(availableLevels)
      for _, level := range levelsSplit {
        _, found := slices.BinarySearch(availableLevels, level)
        if !found {
          writeBadRequestResp(w, "Malformed assembly level.")
          return false
        }
      }
    }
    return true
  }
#+end_src

#+begin_export latex
  We already know how to call one of the neigbors programs. But the
  call arguments are still missing the taxon id
  and the database path.
#+end_export

#+begin_src go <<Call \ty{rankDistribution}, Pa. \ref{pa:api}>>=
	ranksArgs = append(ranksArgs, taxIdStr, dbPath)
  out, errMsg := callPackage(ranksArgs, ranks.Run)
  if len(errMsg) > 0 {
    writeServerError(w, "Error while calling package ranks: " + string(errMsg), nil)
    return
  }
#+end_src

#+begin_export latex
  Now we need to import \ty{ranks}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
	"github.com/evolbioinf/neighbors/ranks"
#+end_src



#+begin_export latex
  \subsection{subtree}
  The endpoint \ty{subtree} returns all taxa in a subtree, including the
  root. It provides two response structures: plain text and json.
  When requesting plain text we respond with the result of \ty{dree},
  we use our usual response schemes if json was requested.

  This is \ty{subtree}'s io:
  Params:
    Path:
      taxon_id int
    Query:
      assembly_levels []string
      field_composite string
      genomes_only     bool
      max_depth       int
      page            int
      page_size       int
      plain_data      bool
      print_names     bool
    Writes:
      string
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func subtree(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Get content type, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Parse taxon id, Pa. \ref{pa:api}>>
    //<<Act on content type, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We use the \ty{contenttype} to get to do content negotiation.
  If the server is providing a content type, that the client is requesting
  we act on the requested content type.
#+end_export

#+begin_src go <<Get content type, Pa. \ref{pa:api}>>=
  ct, _, err := contenttype.GetAcceptableMediaType(r, selfNode.Types)
  //<<React no match, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  We need to change our logic depending on the content type requested by the client.
  We follow our usual scheme of writing taxa with composite fields, if the client
  requests \ty{application/json} format. When they request \ty{text/plain},
  we make a system call to dree instead.
#+end_export

#+begin_src go <<Act on content type, Pa. \ref{pa:api}>>=
  if ct.EqualsMIME(jsonCt) {
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Get field composite, Pa. \ref{pa:api}>>
    //<<Execute subtree query, Pa. \ref{pa:api}>>
    //<<Store taxon output, Pa. \ref{pa:api}>>
    //<<Add taxa links, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  } else if ct.EqualsMIME(plainCt) || ct.EqualsMIME(graphvizCt) {
    //<<Handle arguments \ty{dree}, Pa. \ref{pa:api}>>
    //<<Validate user input \ty{dree}, Pa. \ref{pa:api}>>
    //<<Call \ty{dree}, Pa. \ref{pa:api}>>
    //<<Write output \ty{dree}, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  When executing the subtree query, we call the corresponding
  \ty{tdb} function. Each taxon is then handled as usual.
#+end_export

#+begin_src go <<Execute subtree query, Pa. \ref{pa:api}>>=
  taxa, err := neidb.Subtree(taxId)
  if err != nil {
    writeServerError(w, "fn subtree - Error while executing neidb.Subtree", err)
    return
  }

  if size == -1 {
    size = len(taxa)
  }

  data := []Taxon{}
  for i := offset; i < min(offset + size, len(taxa)); i++ {
    id := taxa[i]
    //<<Construct taxon output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  \ty{dree} takes five arguments: \ty{L}, \ty{g}, \ty{l}, \ty{m} and
  \ty{n}. We already listed their api counterparts in \ty{subtree}'s io,
  except for \ty{l} which is determined by the accepted media type.
  Each of these arguments needs to be extracted, some validated and then
  appended to the call arguments.
#+end_export

#+begin_src go <<Handle arguments \ty{dree}, Pa. \ref{pa:api}>>=
  dreeArgs := []string{"./dree"}
	levels := r.URL.Query().Get("assembly_levels")
  if levels != "" {
		dreeArgs = append(dreeArgs, "-L", levels)
  }

  genStr := r.URL.Query().Get("genomes_only")
	g, err := strconv.ParseBool(genStr)
  if genStr != "" && err != nil {
    writeBadRequestResp(w, "genomes_only argument is not a bool.")
    return
  } else if g {
		dreeArgs = append(dreeArgs, "-g")
  }

  namesStr := r.URL.Query().Get("print_names")
	n, err := strconv.ParseBool(namesStr)
  if namesStr != "" && err != nil {
    writeBadRequestResp(w, "print_names argument is not a bool.")
    return
  } else if n {
		dreeArgs = append(dreeArgs, "-n")
  }

  depthStr := r.URL.Query().Get("max_depth")
  if depthStr != "" {
		dreeArgs = append(dreeArgs, "-m", depthStr)
  }

  if ct.EqualsMIME(plainCt) {
		dreeArgs = append(dreeArgs, "-l")
  }
#+end_src

#+begin_export latex
  We pass assembly levels, three bools and an integer to \ty{dree}.
  We've already got functions for those.
#+end_export

#+begin_src go <<Validate user input \ty{dree}, Pa. \ref{pa:api}>>=
  valid := checkParamLevels(w, levels)
  if !valid {
    return
  }
  valid = checkParamInt(w, depthStr)
  if !valid {
    return
  }
#+end_src

#+begin_export latex
  We run \ty{dree} with the call arguments.
  The call arguments are still missing the taxon id and the path
  to the database. As this endpoint uses both the db and it's path
  the path is not located at args[0], but args[1].
#+end_export

#+begin_src go <<Call \ty{dree}, Pa. \ref{pa:api}>>=
  dbPath := args[1].(string)
  dreeArgs = append(dreeArgs, taxIdStr, dbPath)
  out, errMsg := callPackage(dreeArgs, dree.Run)
  if len(errMsg) > 0 {
    writeServerError(w, "Error while calling package dree: " + string(errMsg), nil)
    return
  }
#+end_src

#+begin_export latex
  We need to import \ty{dree}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
	"github.com/evolbioinf/neighbors/dree"
#+end_src

#+begin_export latex
  Just like we decided whether to use the list or tree output
  of \ty{dree}, we need to decide which media type we are sending
  as a response.
#+end_export

#+begin_src go <<Write output \ty{dree}, Pa. \ref{pa:api}>>=
  if ct.EqualsMIME(plainCt) {
    //<<Write plain output, Pa. \ref{pa:api}>>
  } else {
    //<<Write graphviz output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  This is similar to writing a plain response.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func writeGraphvizOutput(w http.ResponseWriter, out []byte) {
    w.Header().Set("Content-Type", graphvizCt.String())
    fmt.Fprintf(w, "%s", out)
  }
#+end_src

#+begin_export latex
  Now we just call the function to write our output.
#+end_export

#+begin_src go <<Write graphviz output, Pa. \ref{pa:api}>>=
  writeGraphvizOutput(w, out)
#+end_src


#+begin_export latex
  \subsection{taxonomy}
  \subsection{taxonomy} is an endpoint grouping a set of rather
  miscellaneous services. These services are related to taxa, but
  rather than being tied to a single taxon, like the subservices of
  \ty{taxa}, these services are a concern of multiple taxa. Requesting
  \ty{taxonomy} returns an object of links to its subservices.
  This is taxonomy's io:
  Params:
    Path:
      none
    Query:
      none
  Writes:
    \ty{ResponseBody[nil]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func taxonomy(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    out := ResponseBody[*any]{}
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Write \ty{taxonomy}'s links, Pa. \ref{pa:api}>>
    writeJsonOutput(w, out)
  }
#+end_src

#+begin_export latex
  We already know how to add links of a service grouping other services;
  \ty{rootDocument} does the same.
#+end_export

#+begin_src go <<Write \ty{taxonomy}'s links, Pa. \ref{pa:api}>>=
  var links []Link
  //<<Add endpoint's self link, Pa. \ref{pa:api}>>
  //<<Add graph links, Pa. \ref{pa:api}>>
  out.Links = links
#+end_src



#+begin_export latex
  \subsection{taxonAccessions}
  The endpoint \ty{taxonAccessions} finds all the accessions
  associated with the given taxa.

  This is \ty{taxonAccessions}'s io:
  Params:
    Path:
      none
    Query:
      page      int
      page_size int
      taxon_ids []int *required
    Writes:
      ResponseBody[ []TaxonAccession ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func taxonAccessions(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Parse taxon ids, Pa. \ref{pa:api}>>
    //<<Look up accessions, Pa. \ref{pa:api}>>
    //<<Add collection links, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We declare a slice of \ty{TaxonAccession} for storing. We get the accessions 
  for a taxon, then add it's children. We do this as long as there are unprocessed
  taxa without exceeding the page .
#+end_export

#+begin_src go <<Look up accessions, Pa. \ref{pa:api}>>=
  data := []TaxonAccession{}
  //<<Get link nodes, Pa. \ref{pa:api}>>
  for len(taxIds) > 0 && (size == -1 || len(data) < size) {
    taxId := taxIds[0]
    taxIds = taxIds[1:]
    accs, err := neidb.Accessions(taxId)
    if err != nil {
      writeServerError(w, "fn taxonAccessions - Error while executing neidb.Accessions", err)
      return
    }
    if len(accs) > 0 {
      //<<Store accessions, Pa. \ref{pa:api}>>
    }
    //<<Get children, Pa. \ref{pa:api}>>
  }
  out := ResponseBody[[]TaxonAccession]{Data: data}
#+end_src



#+begin_export latex
  We are going to use the \ty{Taxon} and \ty{Accession} nodes while creating
  the data. We should get those nodes before looping to avoid indexing
  the graph unnecessarily.
#+end_export

#+begin_src go <<Get link nodes, Pa. \ref{pa:api}>>=
  taxNode := *root.getService("taxon")
  accNode := *root.getService("accession")

#+end_src

#+begin_export latex
  We declare a variable of type \ty{TaxonAccession} based on the \ty{taxId} and
  store it in our output slice. Then we complete the taxon's accessions by
  adding their levels before storing them. If we've not yet reached the pagination
  offset, we decrement the offset instead of storing the accession.
#+end_export

#+begin_src go <<Store accessions, Pa. \ref{pa:api}>>=
  if offset > 0 {
    offset--
  } else {
    d := TaxonAccession{TaxId: taxId}
    //<<Add taxon link, Pa. \ref{pa:api}>>
    for _, acc := range accs {
      level, err := neidb.Level(acc)
      if err != nil {
        writeServerError(w, "fn taxonAccessions - Error while executing neidb.Level", err)
        return
      }
      accession := Accession{Accession: acc, Level: level}
      //<<Add accession link, Pa. \ref{pa:api}>>
      d.Accessions = append(d.Accessions, accession)
    }
    data = append(data, d)
  }
#+end_src

#+begin_export latex
  Each \ty{TaxonAccession} is related to taxon and accession entities.
  We may add the taxon link to the mid layer struct, i.e. the \ty{TaxonAccession},
  as it is associated with exactly one taxon. The accessions should be referenced
  per accession entry.
#+end_export

#+begin_src go <<Add taxon link, Pa. \ref{pa:api}>>=
	if !plain {
    d.Links = append(d.Links, taxNode.makeLink("taxon", fillTemplate(
	  	taxNode,
	  	map[string]string{"taxon_id": strconv.Itoa(taxId)},
	  	map[string]string{},
	  )))
  }
#+end_src

#+begin_export latex
  Now to add the accession link.
#+end_export

#+begin_src go <<Add accession link, Pa. \ref{pa:api}>>=
	if !plain {
    accession.Links = append(accession.Links, taxNode.makeLink("self", fillTemplate(
	  	accNode,
	  	map[string]string{"accession_id": acc},
	  	map[string]string{},
	  )))
  }
#+end_src

#+begin_export latex
  We retrieve the children of the current taxon and store them in our
  slice of taxa, ready for the next iteration.
#+end_export

#+begin_src go <<Get children, Pa. \ref{pa:api}>>=
  children, err := neidb.Children(taxId)
  if err != nil {
    writeServerError(w, "fn taxonAccessions - Error while executing neidb.Children", err)
    return
  }
  for _, child := range children {
    taxIds = append(taxIds, child)
  }
#+end_src



#+begin_export latex
  \subsection{fintac}
  The endpoint \ty{fintac} executes a system call. We use this endpoint
  to call the \ty{fintac} program via this api. In order to do so we
  need to recreate the io of the program excluding the obvious \ty{-h},
  \ty{-v} and \ty{-H}, where \ty{-h} is the path to a database. \ty{fintac}
  allows to pass files as arguments, this creates the need for some new handling.

  This is \ty{fintac}'s io:
  Params:
    Path:
      none
    Query:
      all_splits bool
      neighbor string
      target string
      unknown string
    Body:
      Files
    Writes:
      string
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func fintac(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Check multipart content types, Pa. \ref{pa:api}>>
    //<<Handle arguments \ty{fintac}, Pa. \ref{pa:api}>>
    //<<Call \ty{fintac}, Pa. \ref{pa:api}>>
    //<<Write plain output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  After checking whether the client is going to accept our response format,
  we need to check, whether the request is using the correct media type. We
  do this by extracting the request's media type and running \ty{EqualsMIME}
  against \ty{multipart/form-data}. If the types don't equal we return a
  415 (Unsupported Media Type).
#+end_export

#+begin_src go <<Check multipart content types, Pa. \ref{pa:api}>>=
	ct, err := contenttype.GetMediaType(r)
	if !ct.EqualsMIME(multipartCt) {
		w.WriteHeader(http.StatusUnsupportedMediaType)
		w.Write([]byte("Use multipart/form-data"))
		return
	}
#+end_src

#+begin_export latex
  Handling the arguments is about checking the data submitted via the form
  and via the query parameters. We need to get all this data, combine and
  prepare it, so we can use it, as if all it were local.
#+end_export

#+begin_src go <<Handle arguments \ty{fintac}, Pa. \ref{pa:api}>>=
  //<<Retrieve query parameters \ty{fintac}, Pa. \ref{pa:api}>>
  //<<Add db parameter \ty{fintac}, Pa. \ref{pa:api}>>
  //<<Handle files \ty{fintac}, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  \ty{fintac} takes the parameters \ty{a}, \ty{n}, \ty{t} and \ty{u}.
  We retrieve them from the query of the url and add them to the
  call arguments, if they exist.
#+end_export

#+begin_src go <<Retrieve query parameters \ty{fintac}, Pa. \ref{pa:api}>>=
	fintacArgs := []string{"./fintac"}
	aStr := r.URL.Query().Get("all_splits")
  if aStr != "" {
  	a, err := strconv.ParseBool(aStr)
    if err != nil {
	    writeBadRequestResp(w, "all_splits argument is not a bool.")
      return
    }
    if a {
	  	fintacArgs = append(fintacArgs, "-a")
	  }
  }
	n := r.URL.Query().Get("neighbor")
	t := r.URL.Query().Get("target")
	u := r.URL.Query().Get("unknown")
	if n != "" {
		fintacArgs = append(fintacArgs, "-n", n)
	}
	if t != "" {
		fintacArgs = append(fintacArgs, "-t", t)
	}
	if u != "" {
		fintacArgs = append(fintacArgs, "-u", u)
	}
#+end_src

#+begin_export latex
  When calling \ty{fintac} remotely we want to use the database.
  In order to do so we need to specify it via a call argument.
  The path of the database is specified as the first parameter
  passed to this function.
#+end_export

#+begin_src go <<Add db parameter \ty{fintac}, Pa. \ref{pa:api}>>=
  dbPath := args[0].(string)
	fintacArgs = append(fintacArgs, "-H", dbPath)
#+end_src

#+begin_export latex
  We implemented the function \ty{filesFromFormData} earlier
  Calling it with the range [1,) of files handles all of the
  file extraction for us. We need to remove the temporary files,
  before leaving this current function.
#+end_export

#+begin_src go <<Handle files \ty{fintac}, Pa. \ref{pa:api}>>=
  paths, err := filesFromFormData(w, r, 1, -1)
  if err != nil {
    return
  }
  for _, p := range paths {
    defer os.Remove(p)
    fintacArgs = append(fintacArgs, p)
  }
#+end_src

#+begin_export latex
  We would usually validate the user's input before calling a program,
  but \ty{fintac} takes a bool and three arbitrary strings as input.
  So there is not much to check.
  We already know how to call a \ty{neigbors} program.
#+end_export

#+begin_src go <<Call \ty{fintac}, Pa. \ref{pa:api}>>=
  out, errMsg := callPackage(fintacArgs, fintacPack.Run)
  if len(errMsg) > 0 {
    writeServerError(w, "Error while calling package fintac: " + string(errMsg), nil)
    return
  }
#+end_src

#+begin_export latex
  We need to import \ty{fintac}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
	fintacPack "github.com/evolbioinf/neighbors/fintac"
#+end_src



#+begin_export latex
  \subsection{\ty{mrca}}
  The service \ty{mrca} taks as argument a slice of taxon IDs and
  returns their most recent common ancestor. We implement the service
  by getting the taxon ids, calculating their most recent common ancestor,
  and writing the output. If there is no most recent common ancestor, we
  return an empty data object.

  This is \ty{mrca}'s io:
  Params:
    Path:
      none
    Query:
      field_composite string
      plain_data      bool
      taxon_ids       []int *required
  Writes:
    ResponseBody[ []Partial<Taxon> ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func mrca(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Get field composite, Pa. \ref{pa:api}>>
    //<<Parse taxon ids, Pa. \ref{pa:api}>>
    //<<Execute mrca query, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  The taxon ids are stored in a query parameter as a comma delimited string.
  We need to get them, cut at each comma and parse them one-by-one.
#+end_export

#+begin_src go <<Parse taxon ids, Pa. \ref{pa:api}>>=
  valid := checkParams(w, r, "taxon_ids")
  if !valid {
    return
  }
  idsStr := r.URL.Query().Get("taxon_ids")
  var taxIds []int
  split := strings.Split(idsStr, ",")
  for _, id := range split {
    p, err := strconv.Atoi(id)
    if err != nil {
      writeBadRequestResp(w, "At least one taxon id is not an integer.")
      return
    }
    taxIds = append(taxIds, p)
  }
#+end_src

#+begin_export latex
  We call \ty{tdb}'s \ty{MRCA} function, to find the most recent common ancestor.
  Using it's id we retrieve its requested fields. If no taxa were requested, we
  respond with an empty object.
#+end_export

#+begin_src go <<Execute mrca query, Pa. \ref{pa:api}>>=
	var out ResponseBody[Taxon]
  if len(taxIds) > 0 {
	  id, err := neidb.MRCA(taxIds)
    if err != nil {
      writeServerError(w, "fn mrca - Error while executing neidb.MRCA", err)
      return
    }

  //<<Get data of taxon, Pa. \ref{pa:api}>>
  //<<Add links taxon entity, Pa. \ref{pa:api}>>
	}
#+end_src

#+begin_export latex
  We call get \ty{getTaxonData}, to get data on our taxon
  using the correct composite of fields and links.
#+end_export

#+begin_src go <<Get data of taxon, Pa. \ref{pa:api}>>=
  tax, err := getTaxonData(id, plain, fieldComposite, neidb)
  if err != nil {
    writeServerError(w, "fn mrca - Error from getTaxonData", err)
    return
  }
  out.Data = tax
#+end_src

#+begin_export latex
  \subsection{neighbors}
  The endpoint \ty{neighbors} calls the \ty{neighbors} program of the \ty{neighbors} package. 
  \ty{neighbors} finds the closest taxonomic neighbors for a set of targets.
  \ty{neighbors} takes five arguments: \ty{L}, \ty{T}, \ty{g}, \ty{l}, \ty{o} and \ty{t}.
  We need to offer these arguments as parameters via the url.

  This is \ty{neighbors}' io:
  Params:
    Path:
      none
    Query:
      assembly_levels       []string
      genomes_and_taxa      bool
      tab_output            bool
      target_ids            []int *required
      targets_only          bool
      with_genomes_seq_only bool
    Body:
      Files
    Writes:
      string
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func neighbors(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Handle arguments \ty{neighbors}, Pa. \ref{pa:api}>>
    //<<Validate user input \ty{neighbors}, Pa. \ref{pa:api}>>
    //<<Call \ty{neighbors}, Pa. \ref{pa:api}>>
    //<<Write plain output, Pa. \ref{pa:api}>>
  }
#+end_src


#+begin_export latex
  Handling the arguments is about checking the data submitted via the form
  and via the query parameters. We need to get all this data, combine and
  prepare it, so we can use it, as if all it were local.
#+end_export

#+begin_src go <<Handle arguments \ty{neighbors}, Pa. \ref{pa:api}>>=
  //<<Retrieve query parameters \ty{neighbors}, Pa. \ref{pa:api}>>
  //<<Set db path, Pa. \ref{pa:api}>>
  //<<Handle files \ty{neighbors}, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  We look for parameters defining three different kinds of 
  behaviour. The target ids are used as an input, the \ty{targets_only},
  \ty{with_genomes_seq_only} and \ty{assembly_levels} are used for filtering;
  \ty{tab_output} and \ty{genomes_and_taxa} change the output format. 
#+end_export

#+begin_src go <<Retrieve query parameters \ty{neighbors}, Pa. \ref{pa:api}>>=
  neighborsArgs := []string{"./neighbors"}
  //<<Get filter parameters, Pa. \ref{pa:api}>>
  //<<Get output parameters, Pa. \ref{pa:api}>>
  //<<Get target ids, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  Now we get and check the \ty{assembly_levels}, as well as the bools,
  i.e. \ty{targets_only} and \ty{with_genomes_seq_only}, filtering our output.
#+end_export

#+begin_src go <<Get filter parameters, Pa. \ref{pa:api}>>=
	levels := r.URL.Query().Get("assembly_levels")
  if levels != "" {
		neighborsArgs = append(neighborsArgs, "-L", levels)
  }

  tfStr := r.URL.Query().Get("targets_only")
	tf, err := strconv.ParseBool(tfStr)
  if tfStr != "" && err != nil {
    writeBadRequestResp(w, "targets_only argument is not a bool.")
    return
  } else if tf {
		neighborsArgs = append(neighborsArgs, "-o")
  }

  gsStr := r.URL.Query().Get("with_genomes_seq_only")
	gs, err := strconv.ParseBool(gsStr)
  if gsStr != "" && err != nil {
    writeBadRequestResp(w, "with_genomes_seq_only argument is not a bool.")
    return
  } else if gs {
		neighborsArgs = append(neighborsArgs, "-g")
  }
#+end_src

#+begin_export latex
  Then there are the parameters: \ty{tab_output} and \ty{genomes_and_taxa}, 
  changing the output format.
#+end_export

#+begin_src go <<Get output parameters, Pa. \ref{pa:api}>>=
	tabStr := r.URL.Query().Get("tab_output")
	tab, err := strconv.ParseBool(tabStr)
  if tabStr != "" && err != nil {
    writeBadRequestResp(w, "tab_output argument is not a bool.")
    return
  } else if tab {
		neighborsArgs = append(neighborsArgs, "-T")
  }

  gtStr := r.URL.Query().Get("genomes_and_taxa")
	gt, err := strconv.ParseBool(gtStr)
  if gtStr != "" && err != nil {
    writeBadRequestResp(w, "genomes_and_taxa argument is not a bool.")
    return
  } else if gt {
		neighborsArgs = append(neighborsArgs, "-l")
  }
#+end_src

#+begin_export latex
  The target ids are stored in a query parameter as a comma delimited string.
  We need to get them and check that they indeed are integers.
#+end_export

#+begin_src go <<Get target ids, Pa. \ref{pa:api}>>=
  targetIds := r.URL.Query().Get("target_ids")
  neighborsArgs = append(neighborsArgs, "-t", targetIds)
#+end_src

#+begin_export latex
  \ty{neighbors} expects the database parameter after setting the targets via -t or
  before specifying input files.
#+end_export

#+begin_src go <<Set db path, Pa. \ref{pa:api}>>=
  dbPath := args[0].(string)
  neighborsArgs = append(neighborsArgs , dbPath)
#+end_src

#+begin_export latex
  Files are optional in \ty{neighbors}, but using them with the \ty{t} argument
  is forbidden. So we need to check whether both are provided. This also 
  implies that different content types of a request are valid, meaning we 
  need to retrieve the provided content type before parsing.
#+end_export

#+begin_src go <<Handle files \ty{neighbors}, Pa. \ref{pa:api}>>=
	ct, err := contenttype.GetMediaType(r)
	if ct.EqualsMIME(multipartCt) {
    paths, err := filesFromFormData(w, r, 0, -1)
    if err != nil {
      return
    }

    if len(paths) > 0  && targetIds != "" {
      writeBadRequestResp(w, "Can't provide files and target_ids via url.")
      return
    }

    for _, p := range paths {
	  	neighborsArgs = append(neighborsArgs, p)
      defer os.Remove(p)
    }
	}
#+end_src

#+begin_export latex
  \ty{neighbors} takes assembly levels, a slice of integers and
  a bunch of bools as input. We can check the assembly levels as usual and write a
  function that checks a slice of integers.
#+end_export

#+begin_src go <<Validate user input \ty{neighbors}, Pa. \ref{pa:api}>>=
  valid := checkParamLevels(w, levels)
  if !valid {
    return
  }
  valid = checkParamLevels(w, targetIds)
  if !valid {
    return
  }
#+end_src

#+begin_export latex
  \ty{neighbors} takes assembly levels, a slice of integers and
  a bunch of bools as input. We can check the assembly levels as usual and write a
  function that checks a slice of integers.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func checkParamInts(w http.ResponseWriter, param string) bool {
    if param != "" {
      split := strings.Split(param, ",")
      for _, id := range split {
        _, err := strconv.Atoi(id)
        if err != nil {
          writeBadRequestResp(w, "At least one target id is not an integer.")
          return false
        }
      }
    }
    return true
  }
#+end_src

#+begin_export latex
  By now we know how to call a \ty{neigbors} program.
#+end_export

#+begin_src go <<Call \ty{neighbors}, Pa. \ref{pa:api}>>=
  out, errMsg := callPackage(neighborsArgs, neighborsPack.Run)
  if len(errMsg) > 0 {
    writeServerError(w, "fn neighbors - Error while calling package neighbors: " + string(errMsg), nil)
    return
  }
#+end_src

#+begin_export latex
  We need to import \ty{neighbors}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
	neighborsPack "github.com/evolbioinf/neighbors/neighbors"
#+end_src




#+begin_export latex
  The service \ty{path} takes as input the taxon ids of a start and an
  end node in the taxonomy, where the end is closer to the root than the
  start. It returns the array of taxon ids that form the path from the
  start to the end. If no such path exists, an empty array is returned.

  This is \ty{path}'s io:
  Params:
    Path:
      none
    Query:
      end_id          int
      field_composite string
      page            int
      page_size       int
      plain_data      bool
      start_id        int
  Writes:
    ResponseBody[ []Partial<Taxon> ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func path(w http.ResponseWriter, r *http.Request, selfNode *Node, args ...any) {
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Get field composite, Pa. \ref{pa:api}>>
    //<<Get start and end, Pa. \ref{pa:api}>>
    //<<Climb taxonomy, Pa. \ref{pa:api}>>
    //<<Add links taxon entity, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  Start and end are provided as query arguments.
#+end_export

#+begin_src go <<Get start and end, Pa. \ref{pa:api}>>=
  startStr := r.URL.Query().Get("start_id")
  start, err := strconv.Atoi(startStr)
  if err != nil {
    writeBadRequestResp(w, "start id is not an integer.")
    return
  }
  endStr := r.URL.Query().Get("end_id")
  end, err := strconv.Atoi(endStr)
  if err != nil {
    writeBadRequestResp(w, "end id is not an integer.")
    return
  }
#+end_src

#+begin_export latex
  We climb the taxonomy until we reach its end or the root, whichever comes
  first. As we accomodate paging with this endpoint, we also stop if
  go past the last entry of the current page. We need to begin at the start
  node either way, because we cant't index the path by our offset.
  Using the resulting ids for retrieving the requested taxon fields.
#+end_export

#+begin_src go <<Climb taxonomy, Pa. \ref{pa:api}>>=
  var data []Taxon
  for i := 0; (i < offset + size || size == -1) && start != end; i++ {
	  parent, err := neidb.Parent(start)

    if err != nil {
      writeServerError(w, "fn path - Error while calling neidb.Parent", err)
      return
    }
	  //<<Has the path reached the root?, Pa. \ref{pa:api}>>
	  start = parent
	  //<<Store new node on path, Pa. \ref{pa:api}>>
  }
  out := ResponseBody[[]Taxon]{Data: data}
#+end_src

#+begin_export latex
  If the path has reached the root, we empty the output slice and break
  from climbing the tree.
#+end_export

#+begin_src go <<Has the path reached the root?, Pa. \ref{pa:api}>>=
  if start == parent {
	  data = data[:0]
	  break
  }
#+end_src

#+begin_export latex
  We construct and store the new node on the path.
#+end_export

#+begin_src go <<Store new node on path, Pa. \ref{pa:api}>>=
  tax, err := getTaxonData(start, plain, fieldComposite, neidb)
  if err != nil {
    writeServerError(w, "fn path - Error from getTaxonData", err)
    return
  }
  data = append(data, tax)
#+end_src
