#+begin_export latex
  \section{api}
  \ty{api} is the backend application for neverV2.
  It implements all the endpoints defined in the
  openApi document. The underlying logic will closely
  resemble neverv1, as the backends don't differ too much.

  \subsection*{Implementation}
  The api backend provides the global RegisterRoutes function just
  like every standalone package used within neverV2. It takes as arguments
  a prefix for the routes and the filepath of the db file.
  \bpr{api}{pr:api}
#+end_export

#+begin_src go <<api.go>>=
  package apiv2
  import (
    //<<Imports, Pa. \ref{pa:api}>>
  )
  //<<Types, Pa. \ref{pa:api}>>
  //<<Methods, Pa. \ref{pa:api}>>
  //<<Variables, Pa. \ref{pa:api}>>
  //<<Content types, Pa. \ref{pa:api}>>
  func RegisterRoutes(pref, dbPath string) {
    //<<Register routes, Pa. \ref{pa:api}>>
  }
  //<<Functions, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
First off we declare the types. This is an easy task as they are already
defined within the openApi document. We can leave out a few \ty{Taxon} types
here by just using the widest \ty{Taxon} type and adding \ty{omitempty} tags
for most properties. Every type also needs a \ty{Links} attribute
which is going to be explained later on.
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type Accession struct {
  Accession string `json:"accession"`
  Level     string `json:"level"`
  Links     []Link `json:"links,omitempty"`
}
type GenomeCount struct {
  Level string `json:"level"`
  Count int    `json:"count"`
  Links []Link `json:"links,omitempty"`
}
type Rank struct {
  TaxId int    `json:"tax_id"`
  Rank  string `json:"rank"`
  Links []Link `json:"links,omitempty"`
}
type Image struct {
	Id          int    `json:"id"`
	Url         string `json:"url"`
	Attribution string `json:"attribution"`
}
type Taxon struct {
  TaxId          int           `json:"tax_id"`
  Parent         int           `json:"parent,omitempty"`
  IsLeaf         bool          `json:"is_leaf,omitempty"`
  Name           string        `json:"name,omitempty"`
  CommonName     string        `json:"common_name,omitempty"`
  Rank           string        `json:"rank,omitempty"`
  Accessions     []Accession   `json:"accessions,omitempty"`
  RawGenomeCount []GenomeCount `json:"raw_genome_counts,omitempty"`
  RecGenomeCount []GenomeCount `json:"rec_genome_counts,omitempty"`
  Images         []Image       `json:"images,omitempty"`
  Links          []Link        `json:"links,omitempty"`
}
#+end_src

#+begin_export latex
  These are the types we could infer from the api specification. All of them have some semantical
  meaning in regards of the resources we provide via the api. To really make this API a REST API it
  needs to be hypermedia driven. Therefore each type representing a resource needs to get a \ty{Links}
  attribute. This allows entities to offer further queries against themselves. The top level response
  needs to offer links as well. For this reason we wrap the response into a type with a \ty{Data} field and
  a \ty{Links} field. The \ty{Link} itself is made of four properties: a relation, a hyper reference, which
  is essentially the actual link, an action, otherwise called http method and the content types provided
  by the link. This schema for links is part of Microsofts REST API guidelines.
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type ResponseBody[T any] struct {
  Data  T    `json:"data,omitempty"`
  Links []Link `json:"links,omitempty"`
}
type Link struct {
  Rel            string   `json:"rel"`
  Href           string   `json:"href"`
  Action         string   `json:"action"`
  Types          []string `json:"types"`
}
#+end_src

#+begin_export latex
  Handling all of these links is a tedious task. So creating a data structure for working
  with them seems necessary. I thought of a link graph as a well suited structure.
  This link graph is composed of nodes, like any other graph. Each node represents a
  callable endpoint with a template URI. These nodes again contain information about
  the http method and content types. The \ty{Links} attribute is what allows these
  nodes to turn into a graph. This attribute is a map mapping strings to a list of nodes.
  The string is used to model the relation for a set of nodes. We need a set or list of nodes
  for each relation, as some might use the same name, think of the root document for instance.
  Its whole purpose is to provide the links to all services. The relation to each of them is the
  same: "service".
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type Node struct {
	Links    map[string][]Node
  Name     string
	BasePath string
	Action   string
	Types    []contenttype.MediaType
}
#+end_src

#+begin_export latex
  We are using the \ty{contenttype} package for the \ty{Types} here.
  Which means we need to import it. This package is rfc7231 compliant
  and is going to help us in terms of content negotiation.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
	"github.com/elnormous/contenttype"
#+end_src

#+begin_export latex
  With this imported we might as well define the two content types we are going
  to use. As they will be used frequently and should not be redefined over
  the course of this document, we will save them as global variables.
#+end_export

#+begin_src go <<Content types, Pa. \ref{pa:api}>>=
	var jsonCt = contenttype.MediaType{Type: "application", Subtype: "json", Parameters: contenttype.Parameters{"charset": "utf-8"}}
	var plainCt = contenttype.MediaType{Type: "text", Subtype: "plain", Parameters: contenttype.Parameters{"charset": "utf-8"}}
#+end_src

#+begin_export latex
  We also need some way of entering he graph. The root document is a perfect
  fit for this.
#+end_export

#+begin_src go <<Variables, Pa. \ref{pa:api}>>=
  var root Node
#+end_src

#+begin_export latex
  Let's also declare a global variable for the route prefix.
#+end_export

#+begin_src go <<Variables, Pa. \ref{pa:api}>>=
  var prefix string
#+end_src

#+begin_export latex
  With the types declared we may begin implementing the \ty{RouteRegistration} function.
  In this we define the Linkgraph and use it's nodes to register the endpoints.
  Luckily the endpoints are already declared within the openApi document
  But before pasting everything into \ty{RegisterRoutes}, we need to think
  about how registration should work. It is reasonable to create a function that handles
  route registration, making things easier for us in the long run. Say we want to
  add a parameter or some specific handling to all our endpoints, we can just add
  it to the registration helper. We call this function \ty{makeRoute}. The function
  needs to take a node, the one to register, as well as a function \ty{fn}
  that is executed when the path is called. \ty{fn} will be wrapped so that we may pass extra arguments.
  However it needs to accept at least the http writer and request. The function may accept more
  arguments, so we make it variadic. Those arguments need to passed from \ty{makeRoute}
  to \ty{fn} somehow, so we make \ty{makeRoute} variadic as well.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func makeRoute(node Node, fn func(http.ResponseWriter, *http.Request, ...any), args ...any) {
    http.HandleFunc(node.Action + " " + node.BasePath, func(w http.ResponseWriter, r *http.Request) {
	  		fn(w, r, args...)
	  })
  }
#+end_src

#+begin_export latex
  We import the \ty{net/http} package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "net/http"
#+end_src

#+begin_export latex
  All of the endpoints need to access the database.
  So before registering the endpoints we open a connection to
  the database using neighbors' tdb program. We will pass the connection to
  all functions that need it.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  var neidb *tdb.TaxonomyDB
  neidb, err := tdb.OpenTaxonomyDBcheck(dbPath)
  if err != nil {
    log.Fatal("apiV2: error while opening the database: ",  err.Error())
  }
#+end_src

#+begin_export latex
  We need to import the \ty{tdb} and \ty{log} packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "github.com/evolbioinf/neighbors/tdb"
  "log"
#+end_src

#+begin_export latex
  This is a good time to write the prefix to our global function.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  prefix = pref
#+end_src

#+begin_export latex
  This leaves us with the writing the link graph and the actual registration of the
  endpoints.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  //<<Initialize nodes and make routes, Pa. \ref{pa:api}>>
  //<<Link nodes, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  We know all the endpoints as they are defined in the openApi document.
#+end_export

#+begin_src go <<Initialize nodes and make routes, Pa. \ref{pa:api}>>=
  //<<Initialize \ty{rootDocument}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{accessions}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{accession}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxa}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxon}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{ancestors}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{children}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{genomeCount}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{genomeCountRec}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{parent}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{rankDistribution}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{subtree}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxonomy}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{fintac}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{mrca}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{neighbors}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{path}, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  The initialization is going to follow a very similar scheme for each of the endpoints.
  First we define its node with an empty map of links. We write down the endpoints path and
  http attributes, then we call \ty{makeRoute} using the node we just wrote. \ty{makeRoute}
  takes a function as a second argument, which handles the endpoint. These functions are yet
  to be implemented. For now we just write down some well fitting names and implement them later.
  There are a few common http attributes, that we are going to be using for a lot of the nodes.
  We should write them into variables, which makes house keeping easier in the long run.
#+end_export

#+begin_src go <<Initialize \ty{rootDocument}, Pa. \ref{pa:api}>>=
	get := "GET"
	post := "POST"

	rootDocL := Node{
		Links:    make(map[string][]Node),
    Name:     "rootDocument",
		BasePath: prefix,
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(rootDocL, rootDocument, neidb) // new
#+end_src

#+begin_export latex
  Let's register \ty{accessions}.
#+end_export

#+begin_src go <<Initialize \ty{accessions}, Pa. \ref{pa:api}>>=
	accessionsL := Node{
		Links:    make(map[string][]Node),
    Name:     "accessions",
		BasePath: prefix + "/accessions",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(accessionsL, accessions, neidb) // previously known as levels
#+end_src

#+begin_export latex
  \ty{accession} is almost the same as before.
#+end_export

#+begin_src go <<Initialize \ty{accession}, Pa. \ref{pa:api}>>=
	accessionL := Node{
		Links:    make(map[string][]Node),
    Name:     "accession",
		BasePath: prefix + "/accessions/{accession_id}",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(accessionL, accession, neidb) // new
#+end_src

#+begin_export latex
  As does \ty{taxa}.
#+end_export

#+begin_src go <<Initialize \ty{taxa}, Pa. \ref{pa:api}>>=
	taxaL := Node{
		Links:    make(map[string][]Node),
    Name:     "taxa",
		BasePath: prefix + "/taxa",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(taxaL, taxa, neidb) // previously known as taxi
#+end_src

#+begin_export latex
  \ty{taxon} is a subservice of \ty{taxa}.
#+end_export

#+begin_src go <<Initialize \ty{taxon}, Pa. \ref{pa:api}>>=
	taxonL := Node{
		Links:    make(map[string][]Node),
    Name:     "taxon",
		BasePath: prefix + "/taxa/{taxon_id}",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(taxonL, taxon, neidb) // new
#+end_src

#+begin_export latex
  \ty{ancestorsL} is another subservice of \ty{taxa}, but it provides
  plain text instead of json.
#+end_export

#+begin_src go <<Initialize \ty{ancestors}, Pa. \ref{pa:api}>>=
	ancestorsL := Node{
		Links:    make(map[string][]Node),
    Name:     "ancestors",
		BasePath: prefix + "/taxa/{taxon_id}/ancestors",
		Action:   get,
		Types:    []contenttype.MediaType{plainCt},
	}
	makeRoute(ancestorsL, ancestors, neidb) // new - calls ants program
#+end_src

#+begin_export latex
  As is \ty{children}.
#+end_export

#+begin_src go <<Initialize \ty{children}, Pa. \ref{pa:api}>>=
	childrenL := Node{
		Links:    make(map[string][]Node),
    Name:     "children",
		BasePath: prefix + "/taxa/{taxon_id}/children",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(childrenL, children, neidb) // previously just children
#+end_src

#+begin_export latex
  \ty{genomeCount} is yet another subservice of \ty{taxa}, but it does not respond with taxon
  entities.
#+end_export

#+begin_src go <<Initialize \ty{genomeCount}, Pa. \ref{pa:api}>>=
	genomeCountL := Node{
		Links:    make(map[string][]Node),
    Name:     "genomeCount",
		BasePath: prefix + "/taxa/{taxon_id}/genome_count",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(genomeCountL, genomeCount, neidb) // previously known as num_genomes
#+end_src

#+begin_export latex
  \ty{genomeCountRec} registration works just like before.
#+end_export

#+begin_src go <<Initialize \ty{genomeCountRec}, Pa. \ref{pa:api}>>=
	genomeCountRecL := Node{
		Links:    make(map[string][]Node),
    Name:     "genomeCountRec",
		BasePath: prefix + "/taxa/{taxon_id}/genome_count_recursive",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(genomeCountRecL, genomeCountRec, neidb) // previously known as num_genomes_rec
#+end_src

#+begin_export latex
  \ty{parent} is yet another subservice of \ty{taxa}. It again responds with taxon entities.
#+end_export

#+begin_src go <<Initialize \ty{parent}, Pa. \ref{pa:api}>>=
	parentL := Node{
		Links:    make(map[string][]Node),
    Name:     "parent",
		BasePath: prefix + "/taxa/{taxon_id}/parent",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(parentL, parent, neidb) // previously known as parent
#+end_src

#+begin_export latex
  \ty{rankDistribution} again provides plain text.
#+end_export

#+begin_src go <<Initialize \ty{rankDistribution}, Pa. \ref{pa:api}>>=
	rankDistL := Node{
		Links:    make(map[string][]Node),
    Name:     "rankDistribution",
		BasePath: prefix + "/taxa/{taxon_id}/rank_distribution",
		Action:   post,
		Types:    []contenttype.MediaType{plainCt},
	}
	makeRoute(rankDistL, rankDistribution, neidb) // new - calls ranks program
#+end_src

#+begin_export latex
  \ty{subtree} provides json and plain text representations.
#+end_export

#+begin_src go <<Initialize \ty{subtree}, Pa. \ref{pa:api}>>=
	subtreeL := Node{
		Links:    make(map[string][]Node),
    Name:     "subtree",
		BasePath: prefix + "/taxa/{taxon_id}/subtree",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt, plainCt},
	}
	makeRoute(subtreeL, subtree, neidb) // previously just subtree
#+end_src

#+begin_export latex
  \ty{taxonomy} is a new service. With this we are finally done registering subservices of \ty{taxa}.
#+end_export

#+begin_src go <<Initialize \ty{taxonomy}, Pa. \ref{pa:api}>>=
	taxonomyL := Node{
		Links:    make(map[string][]Node),
    Name:     "taxonomy",
		BasePath: prefix + "/taxonomy",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(taxonomyL, taxonomy, neidb) // new
#+end_src

#+begin_export latex
  \ty{fintac} is a subservice of \ty{taxonomy} providing plain text.
  Takes a path to the database, as an argument, instead of the database itself.
#+end_export

#+begin_src go <<Initialize \ty{fintac}, Pa. \ref{pa:api}>>=
	fintacL := Node{
		Links:    make(map[string][]Node),
    Name:     "fintac",
		BasePath: prefix + "/taxonomy/fintac",
		Action:   post,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(fintacL, fintac, dbPath) // new - calls fintac program
#+end_src

#+begin_export latex
  \ty{mrca} is a subservice of \ty{taxonomy} providing json.
#+end_export

#+begin_src go <<Initialize \ty{mrca}, Pa. \ref{pa:api}>>=
	mrcaL := Node{
		Links:    make(map[string][]Node),
    Name:     "mrca",
		BasePath: prefix + "/taxonomy/most_recent_common_ancestor",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(mrcaL, mrca, neidb) // previously just mrca
#+end_src

#+begin_export latex
  \ty{neighbors} is another subservice of \ty{taxonomy} providing plain text.
#+end_export

#+begin_src go <<Initialize \ty{neighbors}, Pa. \ref{pa:api}>>=
	neighborsL := Node{
		Links:    make(map[string][]Node),
    Name:     "neighbors",
		BasePath: prefix + "/taxonomy/neighbors",
		Action:   get,
		Types:    []contenttype.MediaType{plainCt},
	}
	makeRoute(neighborsL, neighbors, neidb) // new - calls neighbors program
#+end_src

#+begin_export latex
  \ty{path} is our last service.
#+end_export

#+begin_src go <<Initialize \ty{path}, Pa. \ref{pa:api}>>=
	pathL := Node{
		Links:    make(map[string][]Node),
    Name:     "path",
		BasePath: prefix + "/taxonomy/path",
		Action:   get,
		Types:    []contenttype.MediaType{jsonCt},
	}
	makeRoute(pathL, path, neidb) // previously just path
#+end_src

#+begin_export latex
  Now that we are done creating nodes and registering function we may set the links that
  turn the nodes into a graph. The following rules define which links should be part of responses.
  \begin{enumerate}
    \item Every endpoint has a link to itself.
    \item Every endpoint with services has links to its subservices.
    \item An item of a collection has a reference to itself.
    \item A collection has a link to the entities it is made out of.
    \item An entity that is part of a collection has a link to this collection.
    \item A paginated collection should reference it's next and previous page.
    \item Endpoints that provide responses with different attributes should advertise them.
  \end{enumerate}
  We can also enhance this graph with a few specific interservice connections like these:
    \begin{itemize}
    \item mrca -> path (you may want to see the path to the mrca)
    \item parent -> ancestor (view further than the direct parent)
    \item children -> subtree (view further than the direct children)
  \end{enumerate}

  While references of an entity to itself, like the \ty{self} reference or pagination references, are essential
  for the responses, they enhance this graph by any meaningful way. So we might as well omit them here and add
  them to the responses individually.
  A lot of these links will need to be slightly modified, to match the current request/ responds. We may define
  this basic graph now nevertheless.
#+end_export

#+begin_src go <<Link nodes, Pa. \ref{pa:api}>>=
  //<<Link subservices, Pa. \ref{pa:api}>>
  //<<Link collection entities, Pa. \ref{pa:api}>>
  //<<Link entity to collection, Pa. \ref{pa:api}>>
  //<<Interservice links, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  With the subservices we know that, each endpoint should be contained in the links of the \ty{rootDocument}.
  Then there \ty{accession} which is a subservice of \ty{accessions}; \ty{taxon}, \ty{ancestors}, \ty{children},
  \ty{genomeCount}, \ty{genomeCountRec}, \ty{parent}, \ty{rankDistribution} and \ty{subtree} which are subservices
  of \ty{taxa}. Lastly \ty{fintac}, \ty{mrca}, \ty{neighbors} and \ty{path} are subservices of \ty{taxonomy}.
#+end_export

#+begin_src go <<Link subservices, Pa. \ref{pa:api}>>=
	rootDocL.Links["service"] = append(rootDocL.Links["service"], accessionsL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], accessionL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], fintacL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], taxaL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], taxonL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], ancestorsL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], childrenL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], genomeCountL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], genomeCountRecL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], parentL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], rankDistL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], subtreeL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], taxonomyL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], mrcaL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], neighborsL)
	rootDocL.Links["service"] = append(rootDocL.Links["service"], pathL)
	accessionsL.Links["service"] = append(accessionsL.Links["service"], accessionL)
	taxaL.Links["service"] = append(taxaL.Links["service"], taxonL)
	taxaL.Links["service"] = append(taxaL.Links["service"], ancestorsL)
	taxaL.Links["service"] = append(taxaL.Links["service"], childrenL)
	taxaL.Links["service"] = append(taxaL.Links["service"], genomeCountL)
	taxaL.Links["service"] = append(taxaL.Links["service"], genomeCountRecL)
	taxaL.Links["service"] = append(taxaL.Links["service"], parentL)
	taxaL.Links["service"] = append(taxaL.Links["service"], rankDistL)
	taxaL.Links["service"] = append(taxaL.Links["service"], subtreeL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], fintacL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], mrcaL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], neighborsL)
	taxonomyL.Links["service"] = append(taxonomyL.Links["service"], pathL)
#+end_src

#+begin_export latex
  Now to write the entities of the collections. There are basically two entities, which
  are the basis of almost all the collections. \ty{accession} is the base entity of \ty{accessions};
  \ty{taxon} is the base entity of \ty{taxa}, \ty{ancestors}, \ty{children}, \ty{subtree}, \ty{neighbors}
  and \ty{path}.
#+end_export

#+begin_src go <<Link collection entities, Pa. \ref{pa:api}>>=
	accessionsL.Links["entities"] = append(accessionsL.Links["entities"], accessionL)
	taxaL.Links["entities"] = append(taxaL.Links["entities"], taxonL)
	ancestorsL.Links["entities"] = append(ancestorsL.Links["entities"], taxonL)
	childrenL.Links["entities"] = append(childrenL.Links["entities"], taxonL)
	subtreeL.Links["entities"] = append(subtreeL.Links["entities"], taxonL)
	neighborsL.Links["entities"] = append(neighborsL.Links["entities"], taxonL)
	pathL.Links["entities"] = append(pathL.Links["entities"], taxonL)
#+end_src

#+begin_export latex
  We now link the entities to their collections. I believe we should link them to the basic
  collection only, i.e. \ty{taxon} to \ty{taxa}, as \ty{ancestors} for example is basically a filtered
  version of \ty{taxa}. I don't see a reason to link an entity to every specialized sub collection that
  it is part of.
#+end_export

#+begin_src go <<Link entity to collection, Pa. \ref{pa:api}>>=
	accessionL.Links["part-of"] = append(accessionL.Links["part-of"], accessionsL)
	taxonL.Links["part-of"] = append(taxonL.Links["part-of"], taxaL)
#+end_src

#+begin_export latex
  Handling pagination is easy again, as we already found all the collections.
#+end_export

#+begin_src go <<Link pagination, Pa. \ref{pa:api}>>=
	accessionsL.Links["previous"] = append(accessionsL.Links["previous"], accessionsL)
	taxaL.Links["previous"] = append(taxaL.Links["previous"], taxaL)
	ancestorsL.Links["previous"] = append(ancestorsL.Links["previous"], ancestorsL)
	childrenL.Links["previous"] = append(childrenL.Links["previous"], childrenL)
	subtreeL.Links["previous"] = append(subtreeL.Links["previous"], subtreeL)
	neighborsL.Links["previous"] = append(neighborsL.Links["previous"], neighborsL)
	pathL.Links["previous"] = append(pathL.Links["previous"], pathL)

  accessionsL.Links["next"] = append(accessionsL.Links["next"], accessionsL)
	taxaL.Links["next"] = append(taxaL.Links["next"], taxaL)
	ancestorsL.Links["next"] = append(ancestorsL.Links["next"], ancestorsL)
	childrenL.Links["next"] = append(childrenL.Links["next"], childrenL)
	subtreeL.Links["next"] = append(subtreeL.Links["next"], subtreeL)
	neighborsL.Links["next"] = append(neighborsL.Links["next"], neighborsL)
	pathL.Links["next"] = append(pathL.Links["next"], pathL)
#+end_src

#+begin_export latex
  All endpoints that offer different fields with their responses, respond with a taxon entity.
  So we just need to find all that do so and may add another link to themselves.
  The services are \ty{taxa}, \ty{taxon}, \ty{ancestors}, \ty{children}, \ty{parent},
  \ty{subtree}, \ty{mrca} and \ty{path}.
#+end_export

#+begin_src go <<Link entity fields, Pa. \ref{pa:api}>>=
	taxaL.Links["more fields"] = append(taxaL.Links["more fields"], taxaL)
	taxonL.Links["more fields"] = append(taxonL.Links["more fields"], taxonL)
	ancestorsL.Links["more fields"] = append(ancestorsL.Links["more fields"], ancestorsL)
	childrenL.Links["more fields"] = append(childrenL.Links["more fields"], childrenL)
	parentL.Links["more fields"] = append(parentL.Links["more fields"], parentL)
	subtreeL.Links["more fields"] = append(subtreeL.Links["more fields"], subtreeL)
	mrcaL.Links["more fields"] = append(mrcaL.Links["more fields"], mrcaL)
	pathL.Links["more fields"] = append(pathL.Links["more fields"], pathL)
#+end_src

#+begin_export latex
  Lastly we implement the interservice links. These are straightfoward as we specified them above.
  We should set the root variable as well, now that we are done with initializing the link graph.
#+end_export

#+begin_src go <<Interservice links, Pa. \ref{pa:api}>>=
	mrcaL.Links["path"] = append(mrcaL.Links["path"], pathL)
	parentL.Links["all ancestors"] = append(parentL.Links["all ancestors"], ancestorsL)
	childrenL.Links["all descendants"] = append(childrenL.Links["all descendants"], subtreeL)
  root = rootDocL
#+end_src



#+begin_export latex
  Having delcared all the endpoints we need to begin implementing them.
  We start with the root document \ty{/}. It just provides links
  to all the endpoints provided by this api.
  This is \ty{/}'s io:
  Params:
    Path:
      none
    Query:
      none
  Writes:
    \ty{ResponseBody[nil]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func rootDocument(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[*any]{}
    selfNode := root
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Write \ty{rootDocument}'s links, Pa. \ref{pa:api}>>
    //<<Write output \ty{rootDocument}, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We use the \ty{contenttype} to check whether the server is providing a content type
  that would be accepted by the client. This is just a matter of
  calling the accept method and supplying the types, which are defined within the
  nodes.
#+end_export

#+begin_src go <<Check content types, Pa. \ref{pa:api}>>=
  _, _, err := contenttype.GetAcceptableMediaType(r, selfNode.Types)
  //<<React no match, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  If no type matches the available content types we respond with a 406 (Not Acceptable).
#+end_export

#+begin_src go <<React no match, Pa. \ref{pa:api}>>=
  if err != nil {
    w.WriteHeader(http.StatusNotAcceptable)
		w.Write([]byte("Serverd does not provide any of the accepted content types."))
    return
  }
#+end_src

#+begin_export latex
  This is a perfect application for the link graph we just created. We just iterate over
  \ty{service} links of root and parse them into the \ty{Link}, which provide json annotation.
  Parsing \ty{Node}s to \ty{Link}s is going to be common issue, so we might as well write a
  function for it. Let's call that function \ty{makeLink} for now and implement it later.
#+end_export

#+begin_src go <<Write \ty{rootDocument}'s links, Pa. \ref{pa:api}>>=
  out.Links = append(out.Links, root.makeLink("self", ""))
  for _, v := range root.Links["service"] {
    out.Links = append(out.Links, v.makeLink("service", ""))
  }
#+end_src

#+begin_export latex
  The \ty{makeLink} function takes a \ty{node}, the relation's name and a \ty{href}. If the \ty{href} is empty it uses the \ty{node}'s
  \ty{href} instead instead.
#+end_export

#+begin_src go <<Methods, Pa. \ref{pa:api}>>=
  func (node *Node) makeLink(rel, href string) Link {
    if href != "" {
      node.BasePath = href
    }
    types := []string{}
    for _, t := range node.Types {
      types = append(types, t.String())
    }
    return Link{
      Rel: rel,
      Href: node.BasePath,
      Action: node.Action,
      Types: types,
    }
  }
#+end_src

#+begin_export latex
  Writing the output is going to be a very common task. Every
  endpoint needs to do so. This function combines the steps
  that turn whatever we want to output into a manageable json.
  Before printing the output we need to prettify it, meaning
  convert it into pretty printed json.
  This is pretty much just about setting the correct indentations.
  Then before writing the response we should also specify
  that we are writing in json format. We do this by setting
  the \ty{Content-type} field of the response header. The
  \ty{net/http} package writes the \ty{Content-Length} field
  on its own, so we don't need to do that.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func writeJsonOutput(w http.ResponseWriter, out any) {
    b, err := json.MarshalIndent(out, "", "  ")
    util.Check(err)
	  w.Header().Set("Content-Type", jsonCt.String())
    fmt.Fprintf(w, "%s\n", string(b))
  }
#+end_src

#+begin_export latex
  Having implemented \ty{writeJsonOutput} we may use it to
  write the links of \tty{rootDocument}.
#+end_export

#+begin_src go <<Write output \ty{rootDocument}, Pa. \ref{pa:api}>>=
  writeJsonOutput(w, out)
#+end_src



#+begin_export latex
  The endpoint \ty{accessions} used to be called levels.
  The following sections will closely resemble neverV1
  In our implementation of \ty{accessions} we extract the accessions, get
  their levels, and write the output.
  This is \ty{accessions}' io:
  Params:
    Query:
      accession_ids []string
      page []int
      page_size []int
      plain_data bool
  Writes:
    \ty{ResponseBody[ []Accession ]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func accessions(w http.ResponseWriter, r *http.Request, args ...any) {
    selfNode := root.getService("accessions")
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Check Parameters, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Extract accessions, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Look up levels, Pa. \ref{pa:api}>>
    //<<Add links \ty{accessions}, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We need a function that makes getting nodes from the link graph easier.
  This function is \ty{getService}, which goes through all services and returns
  a pointer to a node with the correct name or nil.
#+end_export

#+begin_src go <<Methods, Pa. \ref{pa:api}>>=
  func (node *Node) getService (name string) *Node {
    services := node.Links["service"]
    idx := slices.IndexFunc(services, func(a Node) bool { return a.Name == name})

    if idx != -1 {
      return &services[idx]
    } else {
      return nil
    }
  }
#+end_src

#+begin_export latex
  We also need to import \ty{slices}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "slices"
#+end_src

#+begin_export latex
  A lot of endpoints that we are defining here allow for or even require parameters.
  We are going to define a function that a) checks whether the required parameters
  exist and b) whether they are safe. In this context I consider a parameter to be safe if it
  cannot be used for code injection.
#+end_export

#+begin_src go <<Check Parameters, Pa. \ref{pa:api}>>=
  valid := checkParams(w, r, "accession_ids")
  if !valid {
    return
  }
#+end_src

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func checkParams(w http.ResponseWriter, r *http.Request, args ...string) bool {
    for _, arg := range args {
      p := r.URL.Query().Get(arg)
      if p == "" {
        w.WriteHeader(http.StatusBadRequest)
        w.Write([]byte("Missing required parameter."))
        return false
      }
    }
    return true
  }
#+end_src

#+begin_export latex
  The function we are using for the endpoints need to be variadic
  so in order to use the parameters passed to them in an orderly fashion
  we need to assign them and do a type assertion. In this block
  assign the db.
#+end_export

#+begin_src go <<Get db from args, Pa. \ref{pa:api}>>=
  neidb := args[0].(*tdb.TaxonomyDB)
#+end_src

#+begin_export latex
  If the query parameter \ty{plain_data} is passed, we need to change the response structure.
  In order to do that we extract the parameter here and act on it later on.
#+end_export

#+begin_src go <<Get plain param, Pa. \ref{pa:api}>>=
	strPlain := r.URL.Query().Get("plain_data")
	plain, err := strconv.ParseBool(strPlain)
	if err != nil {
		plain = false
	}
#+end_src

#+begin_export latex
  Accessions are passed as a comma-delimited string.
#+end_export

#+begin_src go <<Extract accessions, Pa. \ref{pa:api}>>=
  str := r.URL.Query().Get("accession_ids")
  accessions := strings.Split(str, ",")
#+end_src

#+begin_export latex
  We also need to import \ty{strings} to use \ty{Split}
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "strings"
#+end_src

#+begin_export latex
  Extractig the offset and size about extracting the parameters page
  and page size from the url and calculating the resulting offset.
  As there are a lot of endpoints that provide these parameters, we
  should make a function that does exactly that.
#+end_export

#+begin_src go <<Extract offset and size, Pa. \ref{pa:api}>>=
  offset, size := extractPaging(r)
#+end_src

#+begin_export latex
  Extracting the parameters is done just like any other query parameter.
  We set default values if page or page size are not defined or invalid.
  For conversion we need to import \ty{strconv}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "strconv"
#+end_src

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func extractPaging(r *http.Request) (offset, size int) {
    strPage := r.URL.Query().Get("page")
    strPageSize := r.URL.Query().Get("page_size")

    if strPageSize != "" {
      cSize, err := strconv.Atoi(strPageSize)
      size = cSize
      if err != nil {
        size = -1
      }
    } else {
        size = -1
    }
    if size != -1 && strPage != "" {
      page, err := strconv.Atoi(strPage)
      if err != nil {
        offset = 0
      } else {
        offset = page * size
      }
    } else {
      offset = 0
    }
  return
  }
#+end_src

#+begin_export latex
  We look up the level of each accession and store it.
  Ensuring size and offset of the output would be easiest by
  slicing the accessions at the end. I'm explicitly deciding against
  doing that as using them in compution is more perfomant. Sadly the code
  aesthetic suffers from that decision :(
#+end_export

#+begin_src go <<Look up levels, Pa. \ref{pa:api}>>=
  var data = []Accession{}

  if size == -1 {
    size = len(accessions)
  }
  for i := offset; i < min(offset + size, len(accessions)); i++ {
    accession := accessions[i]
    level, err := neidb.Level(accession)
    if err == nil {
      acc := Accession{Accession: accession, Level: level}
      if !plain {
        //<<Add link to accession object, Pa. \ref{pa:api}>>
      }
      data = append(data, acc)
    }
  }
#+end_src

#+begin_export latex
  We convert our slice of accessions items to JSON and write it as our
  response. For this we need to import a few packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "encoding/json"
  "fmt"
  "github.com/evolbioinf/never/util"
#+end_src

#+begin_export latex
  We need further utility function for working with links. As paths saved in a node are URI templates
  we need a function that exchanges a wildcard for an actual value.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func fillTemplate(node Node, vals map[string]string) string {
    for k := range vals {
      node.BasePath = strings.Replace(node.BasePath, "{"+k+"}", vals[k], 1)
    }
    return node.BasePath
  }
#+end_src

#+begin_export latex
  Now we can write the links of the accession entity entity.
#+end_export

#+begin_src go <<Add link to accession object, Pa. \ref{pa:api}>>=
  accNode := *root.getService("accession")
  acc.Links = append(acc.Links, accNode.makeLink("self", fillTemplate(accNode, map[string]string{"accession_id": acc.Accession})))
#+end_src

#+begin_export latex
  A collection provides multiple links. It shows every of its registered endpoints, as well as
  a prev and next relations, when using pagination. Lastly a self reference is also part of the
  links.
#+end_export

#+begin_src go <<Add links \ty{accessions}, Pa. \ref{pa:api}>>=
  out := ResponseBody[[]Accession]{Data: data}
  if !plain {
		var links []Link
    //<<Add endpoint's self link, Pa. \ref{pa:api}>>
    //<<Add pagination links, Pa. \ref{pa:api}>>
    //<<Add graph links, Pa. \ref{pa:api}>>
		out.Links = links
  }
#+end_src

#+begin_export latex
  For adding the self link we just take the \ty{self} node
  to make a \ty{Link} with the requested url and append it to the
  links.
#+end_export

#+begin_src go <<Add endpoint's self link, Pa. \ref{pa:api}>>=
    links = append(links, selfNode.makeLink("self", r.URL.String()))
#+end_src

#+begin_export latex
  Appending the graph links is a matter of iterating over the
  \ty{self} nodes and turning them into links using the correct
  relation in the process.
#+end_export

#+begin_src go <<Add graph links, Pa. \ref{pa:api}>>=
		for link := range selfNode.Links {
			for _, node := range selfNode.Links[link] {
				links = append(links, node.makeLink(link, ""))
			}
		}
#+end_src

#+begin_export latex
  Lastly we write the output using the \ty{writeJsonOutput} function.
  Using the plain parameter we decide whether to output the plain data
  or the out struct including all the links.
#+end_export

#+begin_src go <<Write json output, Pa. \ref{pa:api}>>=
  if plain {
    writeJsonOutput(w, out.Data)
  } else {
    writeJsonOutput(w, out)
  }
#+end_src



#+begin_export latex
  The endpoint \ty{accession} is used to retrieve single
  resources of the accessions collection.
  This is \ty{accession}' io:
  Params:
    Path:
      none
    Query:
      plain_data bool
    Writes:
     \ty{ResponseBody[Accession]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func accession(w http.ResponseWriter, r *http.Request, args ...any) {
    selfNode := root.getService("accession")
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Look up level, Pa. \ref{pa:api}>>
    //<<Add links \ty{accession}, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  Looking up the level is the same as for an array, so we already know how to
  do that.
#+end_export

#+begin_src go <<Look up level, Pa. \ref{pa:api}>>=
  accession := r.PathValue("accession_id")
  level, err := neidb.Level(accession)
  out := ResponseBody[Accession]{}
  if err == nil {
    out.Data = Accession{Accession: accession, Level: level}
		if !plain {
      //<<Add links \ty{accession}, Pa. \ref{pa:api}>>
    }
  }
#+end_src

#+begin_src go <<Add links \ty{accession}, Pa. \ref{pa:api}>>=
  var links []Link
  //<<Add endpoint's self link, Pa. \ref{pa:api}>>
  //<<Add graph links, Pa. \ref{pa:api}>>
  out.Links = links
#+end_src



#+begin_export latex
  The enpoint \ty{taxa} takes as input the name of a taxon, whether to use
  the scientific name only, a matching mode, a page number, a page size
  and an identifier for the kind of fields that should be returned. It
  writes as response for each matching taxon the taxon ID, its parent's
  taxon ID, its scientific name and or its common name.

  This is \ty{taxa}'s io:
  Params:
    Query:
      name string
      scientific bool
      exact bool
      page []int
      page_size []int
      field_composite string
      plain_data bool
  Writes:
    ResponseBody[ []Partial<Taxon> ]
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func taxa(w http.ResponseWriter, r *http.Request, args ...any) {
    selfNode := root.getService("accession")
    //<<Check content types, Pa. \ref{pa:api}>>
    valid := checkParams(w, r, "name")
    if !valid {
      return
    }

    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Extract taxi query, Pa. \ref{pa:api}>>
    //<<Execute taxi query, Pa. \ref{pa:api}>>
    //<<Add links \ty{taxa}, Pa. \ref{pa:api}>>
    //<<Write json output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We extract the taxon name, whether or not we are matching in exact
  mode and if we are looking for just the scientific name.
  If we are \emph{not} matching in exact mode, we bracket the
  name and the blanks it contains by wildcards.
#+end_export
#+begin_src go <<Extract taxi query, Pa. \ref{pa:api}>>=
  name := r.URL.Query().Get("name")
  strExact := r.URL.Query().Get("exact")
  strScientific := r.URL.Query().Get("scientific")
  fieldComposite := r.URL.Query().Get("field_composite")

  exact, err := strconv.ParseBool(strExact)
  if err != nil {
    exact = false
  }

  scientific, err := strconv.ParseBool(strScientific)
  if err != nil {
    scientific = false
  }

  if !exact {
    name = strings.ReplaceAll(name, " ", "% %")
    name = "%" + name + "%"
  }
#+end_src

#+begin_export latex
  We iterate over the taxon IDs and for each one construct the taxon
  output and store it in our slice of taxa.
#+end_export
#+begin_src go <<Execute taxi query, Pa. \ref{pa:api}>>=
  var ids []int
  if scientific {
    ids, err = neidb.Taxids(name, size, offset)
  } else {
    ids, err = neidb.CommonTaxids(name, size, offset)
  }
  util.Check(err)
  data := []Taxon{}
  for _, id := range ids {
    //<<Construct taxon output, Pa. \ref{pa:api}>>
    //<<Store taxon output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  Getting the data of a taxon is something we are doing frequently.
  This means we write a function for this behaviour. \ty{getTaxonData}
  takes an id, whether the data should be plain, i.e. without links
  and the composite to create.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func getTaxonData(id int, plain bool, fieldComposite string) (tax Taxon, err error) {
    tax.id = id
    if fieldComposite == "accessions" {
      //<<Retrieve accessions, Pa. \ref{pa:api}>>
    }
    if fieldComposite == "rank" || fieldComposite == "wide" {
      //<<Retrieve rank fields, Pa. \ref{pa:api}>>
    }
    if fieldComposite == "mid" || fieldComposite == "wide" {
      //<<Retrieve mid fields, Pa. \ref{pa:api}>>
    }
    if fieldComposite == "wide" {
      //<<Retrieve wide fields, Pa. \ref{pa:api}>>
    }
    
    return
  }
#+end_src

#+begin_export latex
  We get the accessions specific data.
#+end_export

#+begin_src go <<Retrieve accessions, Pa. \ref{pa:api}>>=
#+end_src

#+begin_export latex
  We get the rank specific data.
#+end_export

#+begin_src go <<Retrieve rank fields, Pa. \ref{pa:api}>>=
#+end_src

#+begin_export latex
  We get the mid specific data.
#+end_export

#+begin_src go <<Retrieve mid fields, Pa. \ref{pa:api}>>=
  sciName, err := neidb.Name(id)
  util.Check(err)
  tax.Name = sciName
  comName, err := neidb.CommonName(id)
  util.Check(err)
  tax.CommonName = comName
  parent, err := neidb.Parent(id)
  util.Check(err)
  tax.Parent = parent
#+end_src

#+begin_export latex
  We get the wide specific data.
#+end_export

#+begin_src go <<Retrieve wide fields, Pa. \ref{pa:api}>>=
#+end_src


#+begin_export latex
  We get the taxon's scientific and common names and parent. Then we
  construct the corresponding taxon output.
#+end_export

#+begin_src go <<Construct taxon output, Pa. \ref{pa:api}>>=
  tax, err := getTaxonData(id, plain, fieldComposite)
  if err != nil {
    data = append(data, taxa)
  }
#+end_src



#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func taxon(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func ancestors(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func children(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func genomeCount(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func genomeCountRec(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func parent(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func rankDistribution(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func subtree(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func taxonomy(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
#+end_src



#+begin_export latex
  The endpoint \ty{fintac} executes a system call. We use this endpoint
  to call the \ty{fintac} program via this api. In order to do so we
  need to recreate the io of the program excluding the obvious \ty{-h},
  \ty{-v} and \ty{-N}, where \ty{-h} is the path to a database. \ty{fintac}
  allows to pass files as arguments, this creates the need for some new handling.
  This is \ty{accession}' io:
  Params:
    Path:
      none
    Query:
      all_splits bool
      neighbor string
      target string
      unknown string
    Writes:
      string
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func fintac(w http.ResponseWriter, r *http.Request, args ...any) {
    selfNode := root.getService("accession")
    //<<Check content types, Pa. \ref{pa:api}>>
    //<<Check request content types, Pa. \ref{pa:api}>>
    //<<Handle arguments, Pa. \ref{pa:api}>>
    //<<Call program, Pa. \ref{pa:api}>>
    //<<Write plain output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  After checking whether the client is going to accept our response format,
  we need to check, whether the request is using the correct media type. For
  this we use the \ty{conttentype} package. The expected media type is
  \ty{multipart/form-data}. We are going to use this more than once, so
  we add it to the globally defined content types
#+end_export

#+begin_src go <<Content types, Pa. \ref{pa:api}>>=
  var multipartCt = contenttype.MediaType{Type: "multipart", Subtype: "form-data"}
#+end_src

#+begin_export latex
  For checking the request type, we extract the request's media
  type, run \ty{EqualsMIME} and return a 415 (Unsupported Media Type)
  if it does not match \ty{multipart/form-data}.
#+end_export

#+begin_src go <<Check request content types, Pa. \ref{pa:api}>>=
	ct, err := contenttype.GetMediaType(r)
	if !ct.EqualsMIME(multipartCt) {
		w.WriteHeader(http.StatusUnsupportedMediaType)
		w.Write([]byte("Use multipart/form-data"))
		return
	}
#+end_src

#+begin_export latex
  Handling the arguments is about checking the data submitted via the form
  and via the query parameters. We need to get all this data, combine and
  prepare it, so we can use it, as if all it were local.
#+end_export

#+begin_src go <<Handle arguments, Pa. \ref{pa:api}>>=
  //<<Retrieve query parameters, Pa. \ref{pa:api}>>
  //<<Add db parameter, Pa. \ref{pa:api}>>
  //<<Handle files, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  \ty{fintac} takes the parameters \ty{a}, \ty{n}, \ty{t} and \ty{u}.
  We retrieve them from the query of the url and add them to the
  call arguments, if they exist.
#+end_export

#+begin_src go <<Retrieve query parameters, Pa. \ref{pa:api}>>=
	fintacArgs := []string{}
	aStr := r.URL.Query().Get("all_splits")
	a, _ := strconv.ParseBool(aStr)
	n := r.URL.Query().Get("neighbor")
	t := r.URL.Query().Get("target")
	u := r.URL.Query().Get("unknown")
	if a {
		fintacArgs = append(fintacArgs, "-a")
	}
	if n != "" {
		fintacArgs = append(fintacArgs, "-n", n)
	}
	if t != "" {
		fintacArgs = append(fintacArgs, "-t", t)
	}
	if u != "" {
		fintacArgs = append(fintacArgs, "-u", u)
	}
#+end_src

#+begin_export latex
  When calling fintac remotely we want to use the database.
  In order to do so we need to specify it via a call argument.
  The path of the database is specified as the first parameter
  passed to this function.
#+end_export

#+begin_src go <<Add db parameter, Pa. \ref{pa:api}>>=
  dbPath := args[0].(string)
	fintacArgs = append(fintacArgs, "-N", dbPath)
#+end_src

#+begin_export latex
  Handling the files is a quite tedious process, which need to do
  for at least one more service. This means we should write a function 
  for this behaviour. 
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func filesFromFormData(w http.ResponseWriter, r *http.Request) (paths []string, err error) {
      //<<Validate form, Pa. \ref{pa:api}>>
      //<<Sort files, Pa. \ref{pa:api}>>
      //<<Create temporary files, Pa. \ref{pa:api}>>
      return
  } 
#+end_src

#+begin_export latex
  There are two steps in validating the content of a multipart form.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func validateMultipartForm(w http.ResponseWriter, r *http.Request) (err error) {
      //<<Parse form data, Pa. \ref{pa:api}>>
      //<<Check for files, Pa. \ref{pa:api}>>
      return nil
  }
#+end_src

#+begin_export latex
  Accessing the data of a multipart form request, requires
  a parsing step. In this the format of provided is checked
  and loaded into memory. We may define the amount space
  we are willing to allocate for this data, I've decided
  on 3MB, the remaining data will be stored on the hard
  drive. We return a 400 (Bad Request) if the data is
  malformed.
#+end_export

#+begin_src go <<Parse form data, Pa. \ref{pa:api}>>=
	err = r.ParseMultipartForm(3_000_000)
	if err != nil {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte("Malformed multipart form request"))
		return err
	}
#+end_src

#+begin_export latex
  \ty{fintac} requires at least one file, so we should check whether
  one was provided. We return a 400 (Bad Request) if there is no
  file.
#+end_export

#+begin_src go <<Check for files, Pa. \ref{pa:api}>>=
	if len(r.MultipartForm.File) == 0 {
		w.WriteHeader(http.StatusBadRequest)
		w.Write([]byte("Provide at least one file"))
		return errors.New("no files in body")
	}
#+end_src

#+begin_export latex
  We need to import the \ty{errors} package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
	"errors"
#+end_src

#+begin_export latex
  Now we may just call the validation function to check 
  the incoming form.
#+end_export

#+begin_src go <<Validate form, Pa. \ref{pa:api}>>=
  err = validateMultipartForm(w, r)
  if err != nil {
    return
  }
#+end_src

#+begin_export latex
  We need to pass the provided files in some defined
  order. We use the keys that indicate the files to
  do so.
#+end_export

#+begin_src go <<Sort files, Pa. \ref{pa:api}>>=
	keys := []string{}
	for key := range r.MultipartForm.File {
		keys = append(keys, key)
	}
	sort.Strings(keys)
#+end_src

#+begin_export latex
  We need to import the \ty{sort} package for this.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "sort"
#+end_src

#+begin_export latex
  \ty{fintac} works with specified file names. This means 
  we have to have files to make the program call. For this I
  thought of the following: We extract the file data from 
  the request, create a temporary file and save it's path,
  write the data to this temporary file, use the paths for 
  the \ty{fintac} call and remove the temporary files afterwards.
  So these are the steps we are going to follow.
#+end_export

#+begin_src go <<Create temporary files, Pa. \ref{pa:api}>>=
  for i, key := range keys {
		files := r.MultipartForm.File[key]
		if len(files) > 0 {
	  //<<Extract request's file data, Pa. \ref{pa:api}>>
	  //<<Open temporary file, Pa. \ref{pa:api}>>
	  //<<Write to temporary file, Pa. \ref{pa:api}>>
		}
	}
#+end_src

#+begin_export latex
  We expect that each key contains exactly one file. When 
  accesing the \ty{files} variable, we get pointers to the 
  header of a file. Now working with this is rather similar
  to working with any other file. We may open the file via 
  the header, read it's data to a byte slice and close it again.
#+end_export

#+begin_src go <<Extract request's file data, Pa. \ref{pa:api}>>=
	h := *files[0]
	rf, err := h.Open()
	if err != nil {
		log.Fatal("apiv2: Error while reading file from fintac request: ", err)
	}
	b := make([]byte, h.Size)
	rf.Read(b)
	rf.Close()
#+end_src

#+begin_export latex
  In order to open a file we need to define where this file
  should be stored. This name should include the name of the 
  package, a \ty{temp} marker and postpend something making
  the filename unique. We are going to postpend a timestamp. 
  Making this file temporary is necessary
  to avoid flooding the hard drive. Sadly we can't make a 
  deferred remove call right now, as we are in a subfunction.
  This means the calling function needs to take care of the
  file removal. 
  To open/create the file we call \ty{os.Open} adding 
  the create and write only flags. The \ty{0644} defines unix
  permissions for a file. \ty{0644} means the owner may execute
  read and write operation, while everyone else has read only rights.
#+end_export

#+begin_src go <<Open temporary file, Pa. \ref{pa:api}>>=
	path := "apiv2_temp_" + strconv.Itoa(i) + strconv.Itoa(time.Now().Nanosecond())
  paths = append(paths, path)
	tf, err := os.OpenFile(path, os.O_CREATE|os.O_WRONLY, 0644)
  if err != nil {
		panic(fmt.Sprintf("Could not open %s: %s\n", path, err))
	}
#+end_src

#+begin_export latex
  We need to import the \ty{os} and \ty{time} packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "os"
  "time"
#+end_src

#+begin_export latex
  We create a new buffer storing the bytes we just read,
  write them to our temporary file and close the file afterwards.
  It's necessary to close the file right now, instead of deferring it,
  so that other processes may read it.
#+end_export

#+begin_src go <<Write to temporary file, Pa. \ref{pa:api}>>=
	buffer := bytes.NewBuffer(b)
	buffer.WriteTo(tf)
	tf.Close()
#+end_src

#+begin_export latex
  The buffers require importing the \ty{bytes} package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "bytes"
#+end_src

#+begin_export latex
  Now we can call \ty{filesFromFormData}. We also need to make a deferred call
  to \ty{os.Remove} to make the files temporary.
#+end_export

#+begin_src go <<Handle files, Pa. \ref{pa:api}>>=
  paths, err := filesFromFormData(w, r)
  if err != nil {
    return
  }
  for _, p := range paths {
    defer os.Remove(p)
    fintacArgs = append(fintacArgs, p)
  }
#+end_src

#+begin_export latex
  We make a sysCall to execute \ty{fintac}. \ty{Output}
  is a blocking command, that returns whatever was written
  to \ty{stdout} and \ty{stderr}.
#+end_export

#+begin_src go <<Call program, Pa. \ref{pa:api}>>=
	out, err := exec.Command("./fintac", fintacArgs...).Output()
	if err != nil {
		log.Fatal("apiv2: Error executing fintac: ", err)
	}
#+end_src

#+begin_export latex
  \ty{exec} is part of the \ty{os/exec} package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "os/exec"
#+end_src

#+begin_export latex
  We need to implement a new function for writing plain data.
  Let's call it \ty{writePlainOutput}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func writePlainOutput(w http.ResponseWriter, out []byte) {
    w.Header().Set("Content-Type", plainCt.String())
    fmt.Fprintf(w, "%s", out)
  }
#+end_src

#+begin_src go <<Write plain output, Pa. \ref{pa:api}>>=
  writePlainOutput(w, out)
#+end_src

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func mrca(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func neighbors(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
  func path(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    writeJsonOutput(w, out)
  }
#+end_src