#+begin_export latex
  \section{api}
  \ty{api} is the backend application for neverV2.
  It implements all the endpoints defined in the
  openApi document. The underlying logic will closely
  resemble neverv1, as the backends don't differ too much.

  \subsection*{Implementation}
  The api backend provides the global RegisterRoutes function just
  like every standalone package used within neverV2. It takes as arguments
  a prefix for the routes and the filepath of the db file.
  \bpr{api}{pr:api}
#+end_export

#+begin_src go <<api.go>>=
  package apiv2
  import (
    //<<Imports, Pa. \ref{pa:api}>>
  )
  //<<Types, Pa. \ref{pa:api}>>
  //<<Variables, Pa. \ref{pa:api}>>
  func RegisterRoutes(pref, dbPath string) {
    //<<Register routes, Pa. \ref{pa:api}>>
  }
  //<<Functions, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
First off we declare the types. This is an easy task as they are already
defined within the openApi document. Every type needs a \ty{Links} attribute
which is going to be explained later on.
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type Accession struct {
  Accession string `json:"accession"`
  Level     string `json:"level"`
  Links     []Link `json:"links,omitempty"`
}
type GenomeCount struct {
  Level string `json:"level"`
  Count int    `json:"count"`
  Links []Link `json:"links,omitempty"`
}
type TaxId struct {
  TaxId int    `json:"tax_id"`
  Links []Link `json:"links,omitempty"`
}
type Rank struct {
  TaxId int    `json:"tax_id"`
  Rank  string `json:"rank"`
  Links []Link `json:"links,omitempty"`
}
type TaxonAccessions struct {
  TaxId      int         `json:"tax_id"`
  Accessions []Accession `json:"accessions"`
  Links      []Link      `json:"links,omitempty"`
}
type TaxonMid struct {
  TaxId      int    `json:"tax_id"`
  Name       string `json:"name"`
  CommonName string `json:"common_name"`
  Parent     int    `json:"parent"`
  Links      []Link `json:"links,omitempty"`
}
type TaxonNT struct {
  TaxId      int         `json:"tax_id"`
  Type       string      `json:"type"`
  Name       string      `json:"name"`
  Accessions []Accession `json:"parent"`
  Links      []Link      `json:"links,omitempty"`
}
type Image struct {
	Id          int    `json:"id"`
	Url         string `json:"url"`
	Attribution string `json:"attribution"`
}
type TaxonInfo struct {
  TaxId          int           `json:"tax_id"`
  Parent         int           `json:"parent"`
  IsLeaf         bool          `json:"is_leaf"`
  Name           string        `json:"name"`
  CommonName     string        `json:"common_name"`
  Rank           string        `json:"rank"`
  RawGenomeCount []GenomeCount `json:"raw_genome_counts"`
  RecGenomeCount []GenomeCount `json:"rec_genome_counts"`
  Images         []Image       `json:"images"`
  Links          []Link        `json:"links,omitempty"`
}
#+end_src

#+begin_export latex
  These are the types we could infer from the api specification. All of them have some semantical
  meaning in regards of the resources we provide via the api. To really make this API a REST API it
  needs to be hypermedia driven. Therefore each type representing a resource needs to get a \ty{Links}
  attribute. This allows entities to offer further queries against themselves. The top level response
  needs to offer links as well. For this reason we wrap the response into a type with a \ty{Data} field and
  a \ty{Links} field. The \ty{Link} itself is made of four properties: a relation, a hyper reference, which
  is essentially the actual link, an action, otherwise called http method and the content types provided
  by the link. This schema for links is part of Microsofts REST API guidelines.
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type ResponseBody[T any] struct {
  Data  T    `json:"data,omitempty"`
  Links []Link `json:"links,omitempty"`
}
type Link struct {
  Rel            string   `json:"rel"`
  Href           string   `json:"href"`
  Action         string   `json:"action"`
  Types          []string `json:"types"`
}
#+end_src

#+begin_export latex
  Handling all of these links is a tedious task. So creating a data structure for working
  with them seems necessary. I thought of a link graph as a well suited structure.
  This link graph is composed of nodes, like any other graph. Each node represents a
  callable endpoint with a template URI. These nodes again contain information about
  the http method and content types. The \ty{Links} attribute is what allows these
  nodes to turn into a graph. This attribute is a map mapping strings to a list of nodes.
  The string is used to model the relation for a set of nodes. We need a set or list of nodes
  for each relation, as some might use the same name, think of the root document for instance.
  Its whole purpose is to provide the links to all services. The relation to each of them is the
  same: "service".
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:api}>>=
type Node struct {
	Links    map[string][]Node
	BasePath string
	// PathParams  []string
	// QueryParams []string
	Action string
	Types  []string
}
#+end_src

#+begin_export latex
  We also need some way of entering he graph. The root document is a perfect
  fit for this.
#+end_export

#+begin_src go <<Variables, Pa. \ref{pa:api}>>=
  var root Node
#+end_src

#+begin_export latex
  Let's also declare a global variable for the route prefix.
#+end_export

#+begin_src go <<Variables, Pa. \ref{pa:api}>>=
  var prefix string
#+end_src

#+begin_export latex
  With the types declared we may begin implementing the \ty{RouteRegistration} function.
  In this we define the Linkgraph and use it's nodes to register the endpoints.
  Luckily the endpoints are already declared within the openApi document
  But before pasting everything into \ty{RegisterRoutes}, we need to think
  about how registration should work. It is reasonable to create a function that handles
  route registration, making things easier for us in the long run. Say we want to
  add a parameter or some specific handling to all our endpoints, we can just add
  it to the registration helper. We call this function \ty{makeRoute}. The function
  needs to take a node, the one to register, as well as a function \ty{fn}
  that is executed when the path is called. \ty{fn} will be wrapped so that we may pass extra arguments.
  However it needs to accept at least the http writer and request. The function may accept more
  arguments, so we make it variadic. Those arguments need to passed from \ty{makeRoute}
  to \ty{fn} somehow, so we make \ty{makeRoute} variadic as well.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func makeRoute(node Node, fn func(http.ResponseWriter, *http.Request, ...any), args ...any) {
    http.HandleFunc(node.Action + " " + prefix + node.BasePath, func(w http.ResponseWriter, r *http.Request) {
	  		fn(w, r, args...)
	  })
  }
#+end_src

#+begin_export latex
  We import the \ty{net/http} package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "net/http"
#+end_src

#+begin_export latex
  All of the endpoints need to access the database.
  So before registering the endpoints we open a connection to
  the database using neighbors' tdb program. We will pass the connection to
  all functions that need it.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  var neidb *tdb.TaxonomyDB
  neidb, err := tdb.OpenTaxonomyDBcheck(dbPath)
  if err != nil {
    log.Fatal("apiV2: " + err.Error())
  }
#+end_src

#+begin_export latex
  We need to import the \ty{tdb} and \ty{log} packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "github.com/evolbioinf/neighbors/tdb"
  "log"
#+end_src

#+begin_export latex
  This is a good time to write the prefix to our global function.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  prefix = pref
#+end_src

#+begin_export latex
  This leaves us with the writing the link graph and the actual registration of the
  endpoints.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  //<<Initialize nodes and make routes, Pa. \ref{pa:api}>>
  //<<Link nodes, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  We know all the endpoints as they are defined in the openApi document.
#+end_export

#+begin_src go <<Register routes, Pa. \ref{pa:api}>>=
  //<<Initialize \ty{rootDocument}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{accessions}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{accession}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{fintac}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxa}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxon}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{ancestors}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{children}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{genomeCount}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{genomeCountRec}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{parent}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{ranks}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{subtree}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{taxonomy}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{neighbors}, Pa. \ref{pa:api}>>
  //<<Initialize \ty{path}, Pa. \ref{pa:api}>>
#+end_src

#+begin_export latex
  The initialization is going to follow a very similar scheme for each of the endpoints.
  First we define its node with an empty map of links. We write down the endpoints path and
  http attributes, then we call \ty{makeRoute} using the node we just wrote. \ty{makeRoute}
  takes a function as a second argument, which handles the endpoint. These functions are yet
  to be implemented. For now we just write down some well fitting names and implement them later.
  There are a few common http attributes, that we are going to be using for a lot of the nodes.
  We should write them into variables, which makes house keeping easier in the long run.
#+end_export

#+begin_src go <<Initialize \ty{rootDocument}, Pa. \ref{pa:api}>>=
	jsonT := "application/json"
	plainT := "plain/text"
	get := "GET"
	post := "POST"

	rootDocL := Node{
		Links:    make(map[string][]Node),
		BasePath: prefix,
		Action:   get,
		Types:    []string{jsonT},
	}
	makeRoute(rootDocL, rootDocument, neidb) // new
#+end_src

#+begin_export latex
  Let's register \ty{accessions}.
#+end_export

#+begin_src go <<Initialize \ty{rootDocument}, Pa. \ref{pa:api}>>=
	accessionsL := Node{
		Links:    make(map[string][]Node),
		BasePath: prefix + "/accessions",
		Action:   get,
		Types:    []string{jsonT},
	}
	makeRoute(accessionsL, accessions, neidb) // previously known as levels
#+end_src



#+begin_export latex
  We begin implementing the function for the first
  endpoint, which is the root document \ty{/}. It just provides links
  to all the endpoints provided by this api.
  This is \ty{/}'s io:
  Params:
    Path:
      none
    Query:
      none
  Writes:
    \ty{ResponseBody[nil]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func rootDocument(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[*any]{}
    //<<Write rootDocument's links, Pa. \ref{pa:api}>>
    //<<Write output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  This is a perfect application for the LinkMap we just created. We iterate over it and
  write down the relation \ty{service} for all of them.
#+end_export

#+begin_src go <<Write rootDocument's links, Pa. \ref{pa:api}>>=
  for k := range LinkMap {
    curr := LinkMap[k]
    curr.Rel = "service"
		out.Links = append(out.Links, curr)
  }

  slices.SortFunc(out.Links, func(a, b Link) int {
    return cmp.Compare(a.Href, b.Href)
  })

  out.Links[0].Rel = "self"
#+end_src

#+begin_export latex
  We need to add the \ty{slices} and \ty{cmp} packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "slices"
  "cmp"
#+end_src

#+begin_export latex
  This code block is going to be used for writing the output
  of all of our services. Before printing the output we need
  to prettify it, meaning convert it into pretty printed json.
  This is pretty much just about setting the correct indentations.
  Then before writing the response we should also specify
  that we are writing in json format. We do this by setting
  the \ty{Content-type} field of the response header. The
  \ty{net/http} package writes the \ty{Content-Length} field
  on its own, so we don't need to do that.
#+end_export

#+begin_src go <<Write output, Pa. \ref{pa:api}>>=
  b, err := json.MarshalIndent(out, "", "  ")
  util.Check(err)
	w.Header().Set("Content-Type", "application/json")
  fmt.Fprintf(w, "%s\n", string(b))
#+end_src



#+begin_export latex
  The endpoint \ty{accessions} used to be called levels.
  The following sections will closely resemble neverV1
  In our implementation of \ty{accessions} we extract the accessions, get
  their levels, and write the output.
  This is \ty{accessions}' io:
  Params:
    Query:
      accession_ids []string
      page []int
      page_size []int
      plain_data bool
  Writes:
    \ty{ResponseBody[ []Accession ]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func accessions(w http.ResponseWriter, r *http.Request, args ...any) {
    //<<Check Parameters, Pa. \ref{pa:api}>>
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Get plain param, Pa. \ref{pa:api}>>
    //<<Extract accessions, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Look up levels, Pa. \ref{pa:api}>>
    //<<Add Links \ty{accessions}, Pa. \ref{pa:api}>>
    //<<Write output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  A lot of endpoints that we are defining here allow for or even require parameters.
  We are going to define a function that a) checks whether the required parameters
  exist and b) whether they are safe. In this context I consider a parameter to be safe if it
  cannot be used for code injection.
#+end_export

#+begin_src go <<Check Parameters, Pa. \ref{pa:api}>>=
  valid := checkParams(w, r, "accession_ids")
  if !valid {
    return
  }
#+end_src

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func checkParams(w http.ResponseWriter, r *http.Request, args ...string) bool {
    for _, arg := range args {

    p := r.URL.Query().Get(arg)
      if p == "" {
        w.WriteHeader(http.StatusBadRequest)
        w.Write([]byte("Missing required parameter."))
        return false
      }
    }

    return true
  }
#+end_src

#+begin_export latex
  The function we are using for the endpoints need to be variadic
  so in order to use the parameters passed to them in an orderly fashion
  we need to assign them and do a type assertion. In this block
  assign the db.
#+end_export

#+begin_src go <<Get db from args, Pa. \ref{pa:api}>>=
  neidb := args[0].(*tdb.TaxonomyDB)
#+end_src

#+begin_export latex
  If the query parameter \ty{plain_data} is passed, we need to change the response structure.
#+end_export

#+begin_src go <<Get plain param, Pa. \ref{pa:api}>>=
	strPlain := r.URL.Query().Get("plain_data")
	plain, err := strconv.ParseBool(strPlain)
	if err != nil {
		plain = false
	}
#+end_src

#+begin_export latex
  Accessions are passed as a comma-delimited string.
#+end_export

#+begin_src go <<Extract accessions, Pa. \ref{pa:api}>>=
  str := r.URL.Query().Get("accession_ids")
  accessions := strings.Split(str, ",")
#+end_src

#+begin_export latex
  We also need to import \ty{strings} to use \ty{Split}
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "strings"
#+end_src

#+begin_export latex
  Extractig the offset and size about extracting the parameters page
  and page size from the url and calculating the resulting offset.
  As there are a lot of endpoints that provide these parameters, we
  should make a function that does exactly that.
#+end_export

#+begin_src go <<Extract offset and size, Pa. \ref{pa:api}>>=
  offset, size := extractPaging(r)
#+end_src

#+begin_export latex
  Extracting the parameters is done just like any other query parameter.
  We set default values if page or page size are not defined or invalid.
  For conversion we need to import \ty{strconv}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "strconv"
#+end_src

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func extractPaging(r *http.Request) (offset, size int) {
    strPage := r.URL.Query().Get("page")
    strPageSize := r.URL.Query().Get("page_size")

    if strPageSize != "" {
      cSize, err := strconv.Atoi(strPageSize)
      size = cSize
      if err != nil {
        size = -1
      }
    } else {
        size = -1
    }

    if size != -1 && strPage != "" {
      page, err := strconv.Atoi(strPage)
      if err != nil {
        offset = 0
      } else {
        offset = page * size
      }
    } else {
      offset = 0
    }

  return
  }
#+end_src

#+begin_export latex
  We look up the level of each accession and store it.
  Ensuring size and offset of the output would be easiest by
  slicing the accessions at the end. I'm explicitly deciding against
  doing that as using them in compution is more perfomant. Sadly the code
  aesthetic suffers from that decision :(
#+end_export

#+begin_src go <<Look up levels, Pa. \ref{pa:api}>>=
  var data = []Accession{}

  if size == -1 {
    size = len(accessions)
  }

  for i := offset; i < min(offset + size, len(accessions)); i++ {
    accession := accessions[i]
    level, err := neidb.Level(accession)
    if err == nil {
      acc := Accession{Accession: accession, Level: level}
      if !plain {
        //<<Add link to accession object, Pa. \ref{pa:api}>>
      }

      data = append(data, )
    }
  }
#+end_src

#+begin_export latex
  We convert our slice of accessions items to JSON and write it as our
  response. For this we need to import a few packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:api}>>=
  "encoding/json"
  "fmt"
  "github.com/evolbioinf/never/util"
#+end_src

#+begin_export latex
  Each entity of a collcetion should hold two links. The first link references itself.
  This may be used for ruther queries against the resource.
  The second link references the entity's collection.
#+end_export

#+begin_src go <<Add link to accession object, Pa. \ref{pa:api}>>=
  self := LinkMap["base-accession"]
  self.Rel = "self"
  self.Href = r.URL.String()

  partOf := LinkMap["base-accessions"]
  self.Rel = "partOf"

  acc.Links = []Link{self, partOf}
#+end_src

#+begin_export latex
  A collection provides multiple links. It shows every of its registered endpoints, as well as
  a prev and next relations, when using pagination. Lastly a self reference is also part of the
  links.
#+end_export

#+begin_src go <<Add Links accessions, Pa. \ref{pa:api}>>=
  var out any
  if plain {
    out = data
  } else {
    out = ResponseBody[[]Accession]{Data: data}
    self := LinkMap["base-accession"]
    self.Rel = "self"
    self.Href = r.URL.String()

    links := []Link{

    }
  }
#+end_src



#+begin_export latex
  The endpoint \ty{accession} is used to retrieve single
  resources of the accessions collection.
  This is \ty{accession}' io:
  Params:
    Path:
      none
    Query:
      plain_data bool
    Writes:
     \ty{ResponseBody[Accession]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func accession(w http.ResponseWriter, r *http.Request, args ...any) {
    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Look up level, Pa. \ref{pa:api}>>
    //<<Write output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  Looking up the level is the same as for an array, so we already know how to
  do that.
#+end_export

#+begin_src go <<Look up level, Pa. \ref{pa:api}>>=
  out := ResponseBody[Accession]{}
  accession := r.PathValue("accession_id")
  level, err := neidb.Level(accession)
  if err == nil {
		out.Data = Accession{Accession: accession, Level: level}
  }
#+end_src



#+begin_export latex
  The endpoint \ty{fintac} TODO
  This is \ty{accession}' io:
  Params:
    Path:
      none
    Query:
      none
    Writes:
     \ty{ResponseBody[string]}
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func fintac(w http.ResponseWriter, r *http.Request, args ...any) {
    out := ResponseBody[string]{Data:"Not implemented"}
    //<<Write output, Pa. \ref{pa:api}>>
  }
#+end_src



#+begin_export latex
  The enpoint \ty{taxa} takes as input the name of a taxon, whether to use
  the scientific name only, a matching mode, a page number, a page size
  and an identifier for the kind of fields that should be returned. It
  writes as response for each matching taxon the taxon ID, its parent's
  taxon ID, its scientific name and or its common name.

  This is \ty{taxa}'s io:
  Params:
    Query:
      name string
      scientific bool
      exact bool
      page []int
      page_size []int
      field_composites string
      plain_data bool
  Writes:
    []TaxonAccessions
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:api}>>=
  func taxa(w http.ResponseWriter, r *http.Request, args ...any) {
    valid := checkParams(w, r, "name")
    if !valid {
      return
    }

    //<<Get db from args, Pa. \ref{pa:api}>>
    //<<Extract offset and size, Pa. \ref{pa:api}>>
    //<<Extract taxi query, Pa. \ref{pa:api}>>
    //<<Execute taxi query, Pa. \ref{pa:api}>>
     //<<Write output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We extract the taxon name, whether or not we are matching in exact
  mode and if we are looking for just the scientific name.
  If we are \emph{not} matching in exact mode, we bracket the
  name and the blanks it contains by wildcards.
#+end_export
#+begin_src go <<Extract taxi query, Pa. \ref{pa:api}>>=
  name := r.URL.Query().Get("name")
  strExact := r.URL.Query().Get("exact")
  strScientific := r.URL.Query().Get("scientific")

  exact, err := strconv.ParseBool(strExact)
  if err != nil {
    exact = false
  }

  scientific, err := strconv.ParseBool(strScientific)
  if err != nil {
    scientific = false
  }

  if !exact {
    name = strings.ReplaceAll(name, " ", "% %")
    name = "%" + name + "%"
  }
#+end_src

#+begin_export latex
  We iterate over the taxon IDs and for each one construct the taxon
  output and store it in our slice of taxa.
#+end_export
#+begin_src go <<Execute taxi query, Pa. \ref{pa:api}>>=
  var ids []int
  if scientific {
    ids, err = neidb.Taxids(name, size, offset)
  } else {
    ids, err = neidb.CommonTaxids(name, size, offset)
  }

  util.Check(err)
  out := []TaxonMid{}
  for _, id := range ids {
    //<<Construct taxon output, Pa. \ref{pa:api}>>
    //<<Store taxon output, Pa. \ref{pa:api}>>
  }
#+end_src

#+begin_export latex
  We get the taxon's scientific and common names and parent. Then we
  construct the corresponding taxon output.
#+end_export

#+begin_src go <<Construct taxon output, Pa. \ref{pa:api}>>=
  sciName, err := neidb.Name(id)
  util.Check(err)
  comName, err := neidb.CommonName(id)
  util.Check(err)
  tout := TaxonMid{}
  parent, err := neidb.Parent(id)
  if err == nil {
    tout = TaxonMid{TaxId: id, Parent: parent,
      Name: sciName, CommonName: comName}
  }
#+end_src

#+begin_export latex
  If we just constructed an output item, we store it in the
  corresponding slice.
#+end_export

#+begin_src go <<Store taxon output, Pa. \ref{pa:api}>>=
  if err == nil {
    out = append(out, tout)
  }
#+end_src
