#+begin_export latex
  \section{Testing}
  With this we are going to test the second iteration of \ty{never}'s api.
  This is an important step, as we need to ensure that the new version actually
  works as intended. We are going to use the testing suite of the old version as
  a baseline. With this we begin testing as we did before:
  Our outline for testing \ty{never} contains hooks for imports and the
  testing logic.
#+end_export
#+begin_src go <<api_test.go>>=
  package apiv2

  import (
	  //<<Testing imports, Pa. \ref{pa:api}>>
  )

  //<<Types, Pa. \ref{pa:api}>>

  func TestApi(t *testing.T) {
	  //<<Testing, Pa. \ref{pa:api}>>
  }
#+end_src
#+begin_export latex
  We import \ty{testing}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  "testing"
#+end_src
#+begin_export latex
  We construct a set of external and library tests and run each one. External
  tests are a tuple of some command and an index for the corresponding result
  file. If the results of the first test are found in ty{r1.txt}, then the
  corresponding index is 1. Library tests are the same, but they invoke a
  function of some library, rather than a binary program.
#+end_export
#+begin_src go <<Testing, Pa. \ref{pa:api}>>=
  exTests := []ExTest{}
  libTests := []LibTest{}
  //<<Construct tests, Pa. \ref{pa:api}>>
  for _, test := range exTests {
	  //<<Run external test, Pa. \ref{pa:api}>>
  }
  for _, test := range libTests {
	  //<<Run library test, Pa. \ref{pa:api}>>
  }
#+end_src
#+begin_export latex
  We import \ty{exec}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  "os/exec"
#+end_src
#+begin_export latex
  We are also missing the tuples, so let's create that.
#+end_export
#+begin_src go <<Types, Pa. \ref{pa:api}>>=
  type ExTest struct {
    t *exec.Cmd
    r int
  }
  type LibTest struct {
    t func() string
    r int
  }
#+end_src
#+begin_export latex
  We use our program \ty{fetch} to query \ty{never}, which needs to be
  running on the local host listening at port 8080
#+end_export
#+begin_src go <<Construct tests, Pa. \ref{pa:api}>>=
  prog := "../../fetch/fetch"
	url := "http://localhost:8080/api/v2"
#+end_src
#+begin_export latex
  We send queries to each endpoint testing their responses. The endpoints are
  categorized by their url hierarchy. Let's write down the groups and then test
  all endpoints of each group. The root document is an exception, as it does not
  belong to a group.
#+end_export
#+begin_src go <<Construct tests, Pa. \ref{pa:api}>>=
  //<<Prepare queries, Pa. \ref{pa:api}>>
  //<<Test root document, Pa. \ref{pa:api}>>
  //<<Test accessions category, Pa. \ref{pa:api}>>
  //<<Test taxa category, Pa. \ref{pa:api}>>
  //<<Test taxonomy category, Pa. \ref{pa:api}>>
  //<<Test programs category, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
  A query is called by passing a URL to \ty{fetch} that is extended by
  the name of the service, possible path paramters and or a query string,
  \begin{verbatim}
  url/service/?query
  \end{verbatim}
  We implement this pattern in a template to construct the extended
  URLs.
#+end_export
#+begin_src go <<Prepare queries, Pa. \ref{pa:api}>>=
  tmpl := "%s/%s%s"
#+end_src
#+begin_export latex
  The root document is an endpoint that just responds with a list of links
  to all its subservices.
#+end_export
#+begin_src go <<Test root document, Pa. \ref{pa:api}>>=
  u := url
  exTest := ExTest{t: exec.Command(prog, u), r: 1}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
We import \ty{fmt}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  "fmt"
#+end_src
#+begin_export latex
  There are two services services in the accessions category.
#+end_export
#+begin_src go <<Test accessions category, Pa. \ref{pa:api}>>=
  //<<Test \ty{accessions}, Pa. \ref{pa:api}>>
  //<<Test \ty{accession}, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
  \ty{accessions} is a collection, which allows fetching accessions filter by
  their id. We check for two specific accessions. For this test and whenever
  possible, we use the \ty{plain_data} argument.
#+end_export
#+begin_src go <<Test \ty{accessions}, Pa. \ref{pa:api}>>=
  service := "accessions"
  u = fmt.Sprintf(tmpl, url, service, "?accession_ids=GCF_000001405.40,GCA_000002115.2&plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 2}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  \ty{accession} provides a single entity of that same collection.
#+end_export
#+begin_src go <<Test \ty{accession}, Pa. \ref{pa:api}>>=
  service = "accessions/GCF_000001405.40"
  u = fmt.Sprintf(tmpl, url, service, "?plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 3}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  Next is the \ty{taxa} category. This one provides five endpoints.
#+end_export
#+begin_src go <<Test taxa category, Pa. \ref{pa:api}>>=
  //<<Test \ty{taxa}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxon}, Pa. \ref{pa:api}>>
  //<<Test \ty{children}, Pa. \ref{pa:api}>>
  //<<Test \ty{parent}, Pa. \ref{pa:api}>>
  //<<Test \ty{subtree}, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
  \ty{taxa} is the collection of taxa and provides a set of subservices. We
  test this endpoint by looking for the dog taxon.
#+end_export
#+begin_src go <<Test \ty{taxa}, Pa. \ref{pa:api}>>=
  service = "taxa"
  u = fmt.Sprintf(tmpl, url, service, "?name=Canis+lupus+familiaris&exact=true&scientific=true&limit=1&plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 4}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  \ty{taxon} allows requesting single taxa of the collection above. We test
  this endpoint by requesting data on house cats. All endpoints responding with
  taxon entities use field composites. As they all use the same mechanism for
  getting the different fields, it suffices to test this with one endpoint,
  i.e. this one. We also only test for the default field composite as well as
  \ty{id} and \ty{rank}. The remaining composites include genome counts, which
  change too much.
#+end_export
#+begin_src go <<Test \ty{taxon}, Pa. \ref{pa:api}>>=
  service = "taxa/9685"
  u = fmt.Sprintf(tmpl, url, service, "?plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 5}
  exTests = append(exTests, exTest)
  u = fmt.Sprintf(tmpl, url, service, "?field_composite=id&plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 6}
  exTests = append(exTests, exTest)
  u = fmt.Sprintf(tmpl, url, service, "?field_composite=rank&plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 7}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  Lets look at the children of the wolf taxon for checking ty{children}.
  Here we might check limits and offset. So why don't we limit the result to
  five taxa and offset it by three.
#+end_export
#+begin_src go <<Test \ty{children}, Pa. \ref{pa:api}>>=
  service = "taxa/9612/children"
  u = fmt.Sprintf(tmpl, url, service, "?limit=5&offset=3&plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 8}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  Next up is \ty{parent}. We could test this by looking at the dogs's parent.
#+end_export
#+begin_src go <<Test \ty{parent}, Pa. \ref{pa:api}>>=
  service = "taxa/9615/parent"
  u = fmt.Sprintf(tmpl, url, service, "?plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 9}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  \ty{subtree} is the last service of this category. We use it get the subtree
  of the \ty{Homo} taxon.
#+end_export
#+begin_src go <<Test \ty{subtree}, Pa. \ref{pa:api}>>=
  service = "taxa/9605/subtree"
  u = fmt.Sprintf(tmpl, url, service, "?plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 10}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  Next up is the \ty{taxonomy} category. This one provides four endpoints.
#+end_export
#+begin_src go <<Test taxonomy category, Pa. \ref{pa:api}>>=
  //<<Test \ty{taxonomy}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxonAccessions}, Pa. \ref{pa:api}>>
  //<<Test \ty{mrca}, Pa. \ref{pa:api}>>
  //<<Test \ty{path}, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
  \ty{taxonomy} does not provide any data itself, but it responds with links to
  it's subservices.
#+end_export
#+begin_src go <<Test \ty{taxonomy}, Pa. \ref{pa:api}>>=
  service = "taxonomy"
  u = fmt.Sprintf(tmpl, url, service, "")
  exTest = ExTest{t: exec.Command(prog, u), r: 11}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  \ty{accessions} is used to get the accessions of a taxon or its children. We
  use it to look at ancestors of the common house cat. There are too many
  accessions so we limit the output.
#+end_export
#+begin_src go <<Test \ty{taxonAccessions}, Pa. \ref{pa:api}>>=
  service = "taxonomy/accessions"
  u = fmt.Sprintf(tmpl, url, service, "?taxon_ids=338152,338153&limit=5&plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 12}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  Now lets look at the most recent common ancestor of a couple of owl taxa.
#+end_export
#+begin_src go <<Test \ty{mrca}, Pa. \ref{pa:api}>>=
  service = "taxonomy/mrca"
  u = fmt.Sprintf(tmpl, url, service, "?taxon_ids=56312,28725,8825&plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 13}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  We use this result to check the path from the western barn the owl taxa to its order.
#+end_export
#+begin_src go <<Test \ty{path}, Pa. \ref{pa:api}>>=
  service = "taxonomy/path"
  u = fmt.Sprintf(tmpl, url, service, "?start_id=56312&end_id=3078114&plain_data=true")
  exTest = ExTest{t: exec.Command(prog, u), r: 14}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  That's all for the taxonomy category. We continue by testing the
  \ty{programs} category.
#+end_export
#+begin_src go <<Test programs category, Pa. \ref{pa:api}>>=
  //<<Test \ty{programs}, Pa. \ref{pa:api}>>
  //<<Test \ty{ants}, Pa. \ref{pa:api}>>
  //<<Test \ty{dree}, Pa. \ref{pa:api}>>
  //<<Test \ty{fintac}, Pa. \ref{pa:api}>>
  //<<Test \ty{neighbors}, Pa. \ref{pa:api}>>
  //<<Test \ty{ranks}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxi}, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
  \ty{programs} does not provide any data itself, but it responds with links to
  it's subservices.
#+end_export
#+begin_src go <<Test \ty{programs}, Pa. \ref{pa:api}>>=
  service = "programs"
  u = fmt.Sprintf(tmpl, url, service, "")
  exTest = ExTest{t: exec.Command(prog, u), r: 15}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  \ty{ants} gets all the ancestors of a taxon. Let's look at the ancestors
  of a crow.
#+end_export
#+begin_src go <<Test \ty{ants}, Pa. \ref{pa:api}>>=
  service = "programs/ants"
  u = fmt.Sprintf(tmpl, url, service, "?options=56312")
  exTest = ExTest{t: exec.Command(prog, u), r: 16}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  Lets draw a tree of Telluraves using the \ty{dree} endpoint.
#+end_export
#+begin_src go <<Test \ty{dree}, Pa. \ref{pa:api}>>=
  service = "programs/dree"
  u = fmt.Sprintf(tmpl, url, service, "?options=-r&options=-n&options=3073808")
  exTest = ExTest{t: exec.Command(prog, u), r: 17}
  exTests = append(exTests, exTest)
#+end_src
#+begin_export latex
  We also need to import \ty{util}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  util "github.com/evolbioinf/never/util"
#+end_src
#+begin_export latex
  We begin writing the library tests and check the \ty{fintac} endpoint.
  This should include a test for using files, \ty{stdin}, and several options,
  as well as no provided arguments.
#+end_export
#+begin_src go <<Test \ty{fintac}, Pa. \ref{pa:api}>>=
  service = "programs/fintac"
  fu := fmt.Sprintf(tmpl, url, service, "")
  e1, err := os.Open("testing/eco7k.nwk")
  util.Check(err)
  defer e1.Close()
  libTest := LibTest{t: func() string {return util.SendPostRequest(
			fu,
			[]string{"-t", "991910_", "-u", "562_"},
			[]string{"testing/eco7k.nwk"},
      []*os.File{e1},
			nil,
		)},
    r: 18}
  libTests = append(libTests, libTest)
  e2, err := os.Open("testing/eco7k.nwk")
  util.Check(err)
  defer e2.Close()
  libTest = LibTest{t: func() string {return util.SendPostRequest(
			fu,
			[]string{"-t", "991910_", "-u", "562_"},
			[]string{},
      nil,
			e2,
		)},
    r: 18}
  libTests = append(libTests, libTest)
  e3, err := os.Open("testing/eco7k.nwk")
  util.Check(err)
  defer e3.Close()
  libTest = LibTest{t: func() string {return util.SendPostRequest(
			fu,
			[]string{"-t", "991910_"},
			[]string{},
      nil,
			e3,
		)},
    r: 19}
  libTests = append(libTests, libTest)
  libTest = LibTest{t: func() string {return util.SendPostRequest(
			fu,
			[]string{},
			[]string{},
      nil,
			nil,
		)},
    r: 31}
  libTests = append(libTests, libTest)
#+end_src
#+begin_export latex
  We keep going with the library tests and check the \ty{neighbors} endpoint.
  This should include a test for using files, \ty{stdin}, and several options,
  as well as no provided arguments.
#+end_export
#+begin_src go <<Test \ty{neighbors}, Pa. \ref{pa:api}>>=
  service = "programs/neighbors"
  nu := fmt.Sprintf(tmpl, url, service, "")
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			nu,
			[]string{"-t", "9606", "-L", "complete"},
			[]string{},
		)},
    r: 21}
  libTests = append(libTests, libTest)
  t1, err := os.Open("testing/targets.txt")
  util.Check(err)
  defer t1.Close()
  libTest = LibTest{t: func() string {return util.SendPostRequest(
			nu,
			[]string{"-L", "complete"},
			[]string{"testing/targets.txt"},
      []*os.File{t1},
			nil,
		)},
    r: 21}
  libTests = append(libTests, libTest)
  t2, err := os.Open("testing/targets.txt")
  util.Check(err)
  defer t2.Close()
  libTest = LibTest{t: func() string {return util.SendPostRequest(
			nu,
			[]string{"-L", "complete"},
			[]string{},
      nil,
			t2,
		)},
    r: 21}
  libTests = append(libTests, libTest)
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			nu,
			[]string{},
			[]string{},
		)},
    r: 20}
  libTests = append(libTests, libTest)
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			nu,
			[]string{"-t", "9685", "-l"},
			[]string{},
		)},
    r: 22}
  libTests = append(libTests, libTest)
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			nu,
			[]string{"-t", "9685", "-l", "-o"},
			[]string{},
		)},
    r: 23}
  libTests = append(libTests, libTest)
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			nu,
			[]string{"-l", "-t", "9612,9615", "-T"},
			[]string{},
		)},
    r: 24}
  libTests = append(libTests, libTest)
#+end_src
#+begin_export latex
  Next up is \ty{ranks}.
#+end_export
#+begin_src go <<Test \ty{ranks}, Pa. \ref{pa:api}>>=
  service = "programs/ranks"
  ru := fmt.Sprintf(tmpl, url, service, "")
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			ru,
			[]string{"9612"},
			[]string{},
		)},
    r: 25}
  libTests = append(libTests, libTest)
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			ru,
			[]string{"-L", "chromosome", "9612"},
			[]string{},
		)},
    r: 26}
  libTests = append(libTests, libTest)
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			ru,
			[]string{"-t", "-L", "chromosome", "9612"},
			[]string{},
		)},
    r:27}
  libTests = append(libTests, libTest)
  g1, err := os.Open("testing/myGenomeList.txt")
  util.Check(err)
  defer g1.Close()
  libTest = LibTest{t: func() string {return util.SendPostRequest(
			ru,
			[]string{"-g", "testing/myGenomeList.txt", "9612"},
			[]string{},
      []*os.File{g1},
			nil,
		)},
    r:28}
  libTests = append(libTests, libTest)
    libTest = LibTest{t: func() string {return util.SendGetRequest(
			ru,
			[]string{},
			[]string{},
		)},
    r:20}
  libTests = append(libTests, libTest)
#+end_src
#+begin_export latex
  Lastly there is \ty{taxi}.
#+end_export
#+begin_src go <<Test \ty{taxi}, Pa. \ref{pa:api}>>=
  service = "programs/taxi"
  tu := fmt.Sprintf(tmpl, url, service, "")
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			tu,
			[]string{"-t", "9612"},
			[]string{},
		)},
    r: 29}
  libTests = append(libTests, libTest)
    libTest = LibTest{t: func() string {return util.SendGetRequest(
			tu,
			[]string{"homo sapiens"},
			[]string{},
		)},
    r: 30}
  libTests = append(libTests, libTest)
  libTest = LibTest{t: func() string {return util.SendGetRequest(
			tu,
			[]string{},
			[]string{},
		)},
    r:20}
  libTests = append(libTests, libTest)
#+end_src


#+begin_export latex
  We are done with writing the tests. For the external tests we just
  call \ty{t.Output} and diff the corresponding file.
#+end_export
#+begin_src go <<Run external test, Pa. \ref{pa:api}>>=
  get, err := test.t.Output()
  if err != nil {
	  t.Error(err)
  }
  f := "testing/r" + strconv.Itoa(test.r) + ".txt"
  want, err := os.ReadFile(f)
  if err != nil {
	  t.Error(err)
  }
  if !bytes.Equal(get, want) {
	  t.Errorf("%s - get:\n%s\nwant:\n%s\n", f, get, want)
  }
#+end_src
#+begin_export latex
We import \ty{strconv}, \ty{os}, and \ty{bytes}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  "strconv"
  "os"
  "bytes"
#+end_src

#+begin_export latex
  For the externallibrary tests we call the provided funciton and again diff
  the corresponding file.
#+end_export
#+begin_src go <<Run library test, Pa. \ref{pa:api}>>=
  get := test.t()
  f := "testing/r" + strconv.Itoa(test.r) + ".txt"
  want, err := os.ReadFile(f)
  if err != nil {
	  t.Error(err)
  }
  if !bytes.Equal([]byte(get), want) {
	  t.Errorf("%s - get:\n%s\nwant:\n%s\n", f, get, want)
  }
#+end_src