#+begin_export latex
\section{Testing}
With this we are going to test the second iteration of \ty{never}'s api.
This is an important step, as we need to insure that the new version actually works
as intended. Furthermore the version upgrade should result almost exclusively in syntactical changes.
To check whether this is the case we are going to use the testing suite of version as a baseline.
Changes are only made where the syntax requires it or new function were added.
With this we begin testing as we did before:
Our outline for testing \ty{never} contains hooks for imports and the
testing logic.
#+end_export
#+begin_src go <<api_test.go>>=
  package apiv2

  import (
	  //<<Testing imports, Pa. \ref{pa:api}>>
  )

  func TestApi(t *testing.T) {
	  //<<Testing, Pa. \ref{pa:api}>>
  }
#+end_src
#+begin_export latex
We import \ty{testing}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  "testing"
#+end_src
#+begin_export latex
We construct a set of tests and run each one.
#+end_export
#+begin_src go <<Testing, Pa. \ref{pa:api}>>=
  tests := []*exec.Cmd{}
  //<<Construct tests, Pa. \ref{pa:api}>>
  for i, test := range tests {
	  //<<Run test, Pa. \ref{pa:api}>>
  }
#+end_src
#+begin_export latex
We import \ty{exec}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  "os/exec"
#+end_src
#+begin_export latex
We use our program \ty{fetch} to query \ty{never}, which needs to be
running on the local host listening at port 8080
#+end_export
#+begin_src go <<Construct tests, Pa. \ref{pa:api}>>=
  prog := "../../bin/fetch"
	url := "http://localhost:8080/api/v2/"
#+end_src
#+begin_export latex
We prepare the remaining queries of \ty{never} and then use the same
logic as in the tests for \ty{fetch} in
Section~\ref{sec:testFetch}. So we classify the services tested by
query, which may consist of a single taxon ID, multiple taxon IDs, a
single name, or multiple accessions.
#+end_export
#+begin_src go <<Construct tests, Pa. \ref{pa:api}>>=
  //<<Prepare queries, Pa. \ref{pa:api}>>
  //<<Query single taxId, Pa. \ref{pa:api}>>
  //<<Query multiple taxIds, Pa. \ref{pa:api}>>
  //<<Query single name, Pa. \ref{pa:api}>>
  //<<Query multiple accessions, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
A query is called by passing a URL to \ty{fetch} that is extended by
the name of the service, possible path paramters and or a query string,
\begin{verbatim}
url/service/?query
\end{verbatim}
We implement this pattern in a template to construct the extended
URLs.
#+end_export
#+begin_src go <<Prepare queries, Pa. \ref{pa:api}>>=
  tmpl := "%s/%s%s"
#+end_src
#+begin_export latex
There are six services with a single taxon-ID as argument,
\ty{taxa/children}, \ty{taxa/images}, \ty{taxa/genome\_count}, \ty{taxa/genome\_count\_recursive}, \ty{taxa/parent},
and \ty{taxa/subtree}.
#+end_export
#+begin_src go <<Query single taxId, Pa. \ref{pa:api}>>=
  //<<Test \ty{taxa/children}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxa/genome\_count}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxa/genome\_count\_recursive}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxa/parent}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxa/subtree}, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
We test getting the children of human.
#+end_export
#+begin_src go <<Test \ty{taxa/children}, Pa. \ref{pa:api}>>=
  service := "taxa/9606/children"
  u := fmt.Sprintf(tmpl, url, service, "")
  test := exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We import \ty{fmt}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  "fmt"
#+end_src
#+begin_export latex
Since in human the number of raw genomes and the number of recursive
genomes is identical, we switch to \emph{Escherichia coli}, 562, as
our focal taxon for getting the number of genomes. We begin with the
raw number of genomes.
#+end_export
#+begin_src go <<Test \ty{taxa/genome\_count}, Pa. \ref{pa:api}>>=
  service = "taxa/562/genome-count"
  u = fmt.Sprintf(tmpl, url, service, "")
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We test getting the recursive number of genomes.
#+end_export
#+begin_src go <<Test \ty{taxa/genome\_count\_recursive}, Pa. \ref{pa:api}>>=
  u = fmt.Sprintf(tmpl, url, service + "-recursive", "")
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We test getting the parent.
#+end_export
#+begin_src go <<Test \ty{taxa/parent}, Pa. \ref{pa:api}>>=
  service = "taxa/562/parent"
  u = fmt.Sprintf(tmpl, url, service, "")
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
Since the subtree rooted on \emph{E. coli} is vast, we switch back to
human for testing \ty{taxa/subtree}.
#+end_export
#+begin_src go <<Test \ty{taxa/subtree}, Pa. \ref{pa:api}>>=
  service = "taxa/9606/subtree"
  u = fmt.Sprintf(tmpl, url, service, "")
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
There are six services that take multiple taxon-IDs as argument,
\ty{ranks}, \ty{taxa-accessions}, \ty{taxa-info}, \ty{taxa-names}, 
\ty{taxa/mrca} and \ty{taxa/path}. We test each one in turn.
#+end_export
#+begin_src go <<Query multiple taxIds, Pa. \ref{pa:api}>>=
  //<<Test \ty{ranks}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxa-accessions}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxa-info}, Pr \ref{pr:nev}>>
  //<<Test \ty{taxa-names}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxa/mrca}, Pa. \ref{pa:api}>>
  //<<Test \ty{taxa/path}, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
We carry out each test on the same set of taxa we already used in the example
printed by \ty{never}.
We look up the ranks of human (9606) and \emph{Homo} (9605).
#+end_export
#+begin_src go <<Test \ty{ranks}, Pa. \ref{pa:api}>>=
  query := "?taxon_ids=9606,9605"
  u = fmt.Sprintf(tmpl, url, "ranks", query)
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
So we test getting genome accessions on the rather
obscure bacteria \emph{Mesorhizobium ciceri} biovar biserrulae (278148)
and \emph{Aphaenogaster floridana} (602633), which have two and one
sequenced genome, respectively.
#+end_export
#+begin_src go <<Test \ty{taxa-accessions}, Pa. \ref{pa:api}>>=
  query = "?taxon_ids=278148,602633"
  u = fmt.Sprintf(tmpl, url, "taxa-accessions", query)
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We look up the taxon info for \emph{E. coli} (562) and human (9606).
#+end_export
#+begin_src go <<Test \ty{taxa-info}, Pr \ref{pr:nev}>>=
  query = "?taxon_ids=562,9606"
  u = fmt.Sprintf(tmpl, url, "taxa-info", query)
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We get the names of human (9606) and its genus, \emph{Homo} (9605).
#+end_export
#+begin_src go <<Test \ty{taxa-names}, Pa. \ref{pa:api}>>=
  query = "?taxon_ids=9606,9605"
  u = fmt.Sprintf(tmpl, url, "taxa-names", query)
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We look up the most recent common ancestor of human (9606), Denisova
(741158), and Neanderthal (63221).
#+end_export
#+begin_src go <<Test \ty{taxa/mrca}, Pa. \ref{pa:api}>>=
  u = fmt.Sprintf(tmpl, url, "/taxa/9606,741158,63221/mrca", query)
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
We get the path between human (9606) and mammals (40674).
#+end_export
#+begin_src go <<Test \ty{taxa/path}, Pa. \ref{pa:api}>>=
  u = fmt.Sprintf(tmpl, url, "taxa/9606/path/40674", "")
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
\ty{taxa} is centered on a single name.
#+end_export
#+begin_src go <<Query single name, Pa. \ref{pa:api}>>=
  //<<Test \ty{taxa}, Pa. \ref{pa:api}>>
#+end_src
#+begin_export latex
We test \ty{taxa} on ``dolph'' to simulate a user about to type
``dolphin'', and request the second page of at most 10 results.
#+end_export
#+begin_src go <<Test \ty{taxa}, Pa. \ref{pa:api}>>=
  query = "?name=dolph&page_size=10&page=2"
  u = fmt.Sprintf(tmpl, url, "taxa", query)
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
There is only one service that takes multiple genome accessions as
query, \ty{accessions}. We test it on two accessions.
#+end_export
#+begin_src go <<Query multiple accessions, Pa. \ref{pa:api}>>=
  query = "?accession_ids=GCF_000001405.40,GCA_000002115.2"
  u = fmt.Sprintf(tmpl, url, "accessions", query)
  test = exec.Command(prog, u)
  tests = append(tests, test)
#+end_src
#+begin_export latex
When we run a test, we compare the results we get to the results we
want, which are stored in files \ty{r1.txt}, \ty{r2.txt}, and so
on. If we don't get what we want, we write an error message that
includes the name of the output file that tripped us up.
#+end_export
#+begin_src go <<Run test, Pa. \ref{pa:api}>>=
  get, err := test.Output()
  if err != nil {
	  t.Error(err)
  }
  f := "r" + strconv.Itoa(i+1) + ".txt"
  want, err := os.ReadFile(f)
  if err != nil {
	  t.Error(err)
  }
  if !bytes.Equal(get, want) {
	  t.Errorf("%s - get:\n%s\nwant:\n%s\n", f, get, want)
  }
#+end_src
#+begin_export latex
We import \ty{strconv}, \ty{os}, and \ty{bytes}.
#+end_export
#+begin_src go <<Testing imports, Pa. \ref{pa:api}>>=
  "strconv"
  "os"
  "bytes"
#+end_src
