#+begin_export latex
      \section{docs}
      \ty{docs} is the frontend application for neverV2.
      It serves to document all endpoints, requests, responses and
      schemes provided by the api. Data is provided by a openAPI
      document in json format. While based on go's html templating
      package it uses basic html, css and javscript to render the docs.

      \subsection*{Implementation}
      The program \ty{docs} provides functions for registering the routes
      and obtaining the api data from the openAPI document, as
      well as types for holding the data in intermediate data structures.
      \bpr{docs}{pr:docs}
#+end_export

#+begin_src go <<docs.go>>=
  package docsv2

  import (
    //<<Imports, Pa. \ref{pa:docs}>>
  )

  //<<Types, Pa. \ref{pa:docs}>>
  //<<Embedded files, Pa. \ref{pa:docs}>>
  //<<Functions, Pa. \ref{pa:docs}>>
#+end_src

#+begin_export latex
  The first function we will be looking at is
  \ty{RegisterRoutes}. This function will be called by
  the actual webserver. This allows the \ty{docs} to register
  all its routes and setup how to handle the different frontend
  endpoints. To prevent route clashing, the functions expects a prefix
  that is prepended to all registered routes. The server also provides
  information on whether it is hosting locally and its port. We need
  this data later on to for the example requests.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:docs}>>=
  func RegisterRoutes(prefix string, local bool, port int, dbDirPath string) {
    //<<Create template, Pa. \ref{pa:docs}>>
    //<<Add template functions, Pa. \ref{pa:docs}>>
    //<<Read HTML files, Pa. \ref{pa:docs}>>
    //<<Retrieve Data, Pa. \ref{pa:docs}>>
    //<<Handle base route, Pa. \ref{pa:docs}>>
    //<<Handle static files, Pa. \ref{pa:docs}>>
    //<<Handle database files, Pa. \ref{pa:docs}>>
  }
#+end_src

#+begin_export latex
  We begin \ty{RegisterRoutes} by creating a template called app.
  For server side debugging purposes we also add some prints
  for all the actions we take.
#+end_export

#+begin_src go <<Create template, Pa. \ref{pa:docs}>>=
  fmt.Println("docsV2: Creating template")
  tmpl := template.New("app")
#+end_src

#+begin_export latex
    To be able to use those commands we need to
    import the fmt and html/template packages.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:docs}>>=
  "fmt"
  "html/template"
#+end_export

#+begin_export latex
  Functions for the templating engine are provided by a function map.
  Every function defined within that map may be used inside the HTML
  via the templating syntax. We need three utility functions for the HTML.
  The first is a simple subtraction.
  \ty{toKebab} is for rewriting the endpoints names.
  The endpoints are identified by their names in url syntax. Using those for
  css identifiers does not seem like a good idea, so we replace some characters
  to make them more css friendly.
  \ty{dict} lets us create dictionaries inside HTML. We use this to bypass the
  single parameter rule sub-templates.
#+end_export

#+begin_src go <<Add template functions, Pa. \ref{pa:docs}>>=
  fmt.Println("docsV2: Registering custom functions")
  tmpl.Funcs(template.FuncMap{
    "sub": func(a, b int) int {
      return a - b
    },
    //<<Rewrite paths to CSS IDs, Pa. \ref{pa:docs}>>
    //<<Create dict from args, Pa. \ref{pa:docs}>>
  })
#+end_export

#+begin_export latex
  Now we define \ty{toKebab}. The function is provided a variable
  amount of strings and returns a single joined string. To get
  rid of the hierarchical url structure of an endpoint we replace
  every slash with a dash which results in strings in kebab-case notation, if
  we make all characters lowercased  as well.
  Then we join the strings and delete leading dashes as well as dashes followed
  by another dash. The path parameters are enclosed by curly brackets. We remove
  those as well. If an argument is empty or just a \ty{/} we convert it to 
  \ty{em}.
#+end_export

#+begin_src go <<Rewrite paths to CSS IDs, Pa. \ref{pa:docs}>>=
	"toKebab": func(args ...string) string {
		noSlash := make([]string, len(args))
		for i, str := range args {
			noSlash[i] = strings.ReplaceAll(str, "/", "-")
      if noSlash[i] == "" ||  noSlash[i] == "-" {
        noSlash[i] = "em"
      }
		}

		joined := strings.ReplaceAll(strings.Join(noSlash, "-"), "--", "-")
		if len(joined) > 1 && joined[0] == '-' {
			joined = joined[1:]
		}

    joined = strings.ReplaceAll(joined, "{", "")
    joined = strings.ReplaceAll(joined, "}", "")

		return strings.ToLower(joined)
	},
#+end_src

#+begin_export latex
  As mentioned before, as of now go's html templating does not
  allow to pass multiple values from within a template to a
  sub-template. To bypass this we use a dict function. This
  function takes a variable amount of arguments. It uses arguments
  with an even index as a key and the following argument with an odd
  index as a value. It should fail if the amount of arguments is not
  even.
#+end_export

#+begin_src go <<Create dict from args, Pa. \ref{pa:docs}>>=
	"dict": func(args ...any) map[string]any {
		dict := make(map[string]any)
		if len(args)%2 != 0 {
			panic("Cannot create dictionary in template. Number of parameters is odd.\n")
		}

		for i := 0; i < len(args); i += 2 {
			key, ok := args[i].(string)
			if !ok {
				panic("Cannot create dictionary in template. Key argument is not a string.\n")
			}

			dict[key] = args[i+1]
		}

		return dict
	},
#+end_src

#+begin_export latex
  When reading the html files, we use the \ty{embed} package, which bundles all
  our read-only files with the resulting binary. Now reading the files is about
  extracting them from their filesystems and parsing them using \ty{ParseFS}.
#+end_export

#+begin_src go <<Read HTML files, Pa. \ref{pa:docs}>>=
  fmt.Println("docsV2: Reading html files")
  tmpl = template.Must(tmpl.ParseFS(pagesFS, "pages/*.html"))
  tmpl = template.Must(tmpl.ParseFS(componentsFS, "components/*.html", "components/*/*.html"))
#+end_src

#+begin_export latex
  The filesystems themselves need to be defined using go directives.
#+end_export

#+begin_src go <<Embedded files, Pa. \ref{pa:docs}>>=
	//go:embed pages/*
	var pagesFS embed.FS
  
	//go:embed components/*
	var componentsFS embed.FS
#+end_src

#+begin_export latex
  We need to import the \ty{embed} package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:docs}>>=
  "embed"
#+end_src

#+begin_export latex
  The next step is to retrieve the data from the openAPI document.
  For this we use the library libopenapi. This library parses a
  byte slice from an openAPI document and lets us create a \ty{DocumentModel}.
  Using this model we can retrieve the data and form it into an intermediate
  representation. The intermediate representation needs to be taylored
  to our spec and use for it within the html templating. With this in mind
  we create the types that shall hold our data.
#+end_export

#+begin_src go <<Types, Pa. \ref{pa:docs}>>=
type Content struct {
	Version     string
	Description string
	ApiVersion  string
	ServerURL   string
  Prefix      string
  DbDirPath 	string
	Title       string
  Local       bool
	Tags        []Tag
	Paths       []Path
}

type Tag struct {
	Name        string
	Description string
}

type Path struct {
	Name       string
	Operations []Operation
}

type Operation struct {
	Verb            string
	Description     string
	Tags            []string
	PathParameters  []Parameter
	QueryParameters []Parameter
	RequestBody     RequestBody
	Responses       []Response
	ExampleRequest  string
	ExampleResponse string
  Schema          string
  AcceptHeader    []string
}

type Parameter struct {
	ParamType   string
	Name        string
	Description string
	Required    bool
  Extra       string
	Example     string
	Explode     bool
	Schema      string
}

type RequestBody struct {
	Description string
	Mime        string
}

type Response struct {
	Code        int
	Description string
	Mime        string
}
#+end_src

#+begin_export latex
  Now we import the library as well as some utility packages
  and begin the retrieval process as described above.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:docs}>>=
	"strings"

	"github.com/pb33f/libopenapi"
	v3 "github.com/pb33f/libopenapi/datamodel/high/v3"
#+end_src

#+begin_export latex
  We might aswell provide the assigned prefix and the path to the databases, so
  the html pages may use them for dynamic linking. Same goes for the database
  directory and local hosting options. All of them change the documentation's 
  links.
#+end_export

#+begin_src go <<Retrieve Data, Pa. \ref{pa:docs}>>=
  content := retrieveData(local, port)
  content.Prefix = prefix
  content.DbDirPath = dbDirPath
  content.Local = local
#+end_src

#+begin_export latex
  Relative file references break whenever the binary is called from somewhere 
  outside the top level directory. We already used the \ty{embed} package 
  ealier to fix this. Let's do that again.
#+end_export

#+begin_src go <<Embedded files, Pa. \ref{pa:docs}>>=
  //go:embed static/*
  var staticFS embed.FS
#+end_src

#+begin_export latex
  Our function for retrieving data, takes the data file, a flag stating, 
  whether this is hosted locally and lastly the server's port.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:docs}>>=
  func retrieveData(local bool, port int) Content {
    //<<Create Model from library, Pa. \ref{pa:docs}>>
    //<<Parse data to Content, Pa. \ref{pa:docs}>>
  }
#+end_src

#+begin_export latex
  We begin by reading the openAPI document. The library expects a
  byte slice in either yaml or json format. With that
  raw data we create a Document which lets us build the model.
#+end_export

#+begin_src go <<Create Model from library, Pa. \ref{pa:docs}>>=
  fmt.Println("docsV2: reading api document")
  spec, _ := staticFS.ReadFile("static/api_spec.json")
  fmt.Println("docsV2: creating document")
  document, err := libopenapi.NewDocument(spec)
  if err != nil {
    panic(fmt.Sprintf("cannot create new document: %e", err))
  }

  fmt.Println("docsV2: building model")
  docModel, err := document.BuildV3Model()
  if err != nil {
    panic(fmt.Sprintf("cannot create v3 model from document: %e", err))
  }
#+end_src

#+begin_export latex
  Just like the openAPI spec allows for broad and immensely detailed and broad
  specifications so does the model created by the library. This means the Model
  is too unspecific and powerful for our purpose. We now go through it and
  parse it bit by bit into our Content structure, which is much more managable.
#+end_export

#+begin_src go <<Parse data to Content, Pa. \ref{pa:docs}>>=
  content := Content{
    ApiVersion:  docModel.Model.Version,
    Title:       docModel.Model.Info.Title,
    Version:     docModel.Model.Info.Version,
    Description: docModel.Model.Info.Description,
    ServerURL:   docModel.Model.Servers[0].URL,
  }

  //<<Parse Tags, Pa. \ref{pa:docs}>>
  //<<Parse Paths, Pa. \ref{pa:docs}>>
  return content
#+end_src

#+begin_export latex
  The tags are a rather shallow structure, we can parse them by
  iterating over a top level key of the Model.
#+end_export

#+begin_src go <<Parse Tags, Pa. \ref{pa:docs}>>=
  for _, tag := range docModel.Model.Tags {
    content.Tags = append(content.Tags, Tag{
      Name: tag.Name,
      Description: tag.Description,
    })
  }
#+end_src

#+begin_export latex
  Parsing the paths is much more complex. We can already see that by
  just looking at how deeply nested our Path type is. All the same we
  begin just like we did with the tags, just a few levels deeper.
#+end_export

#+begin_src go <<Parse Paths, Pa. \ref{pa:docs}>>=
  for pathName, pathItem := range docModel.Model.Paths.PathItems.FromOldest() {
    newPath := Path{Name: pathName}

    //<<Parse path parameters, Pa. \ref{pa:docs}>>
    //<<Parse operations, Pa. \ref{pa:docs}>>

    content.Paths = append(content.Paths, newPath)
  }
#+end_src

#+begin_export latex
  As we save both the path level and operation level parameters
  within an operation, we need to extract the path parameters before
  creating the operations. Parsing the operation's parameters
  later on follows the same procedure. So creating a function
  for that seems reasonable.
#+end_export

#+begin_src go <<Parse path parameters, Pa. \ref{pa:docs}>>=
  pathParams := extractParameters(pathItem.Parameters)
#+end_src

#+begin_export latex
  In this funciton we iterate over all the parameters.
  We need to build the schema, to access the parameters specification.
  Then we retrieve basic information about the parameter, write down
  the actual schema, possible extra information and extract examples.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:docs}>>=
func extractParameters(parameters []*v3.Parameter) []Parameter {
	var parsed []Parameter
	for _, parameter := range parameters {
		//<<Build parameter schema, Pa. \ref{pa:docs}>>
    //<<Retrieve basic parameter info, Pa. \ref{pa:docs}>>
    //<<Extract parameter schema, Pa. \ref{pa:docs}>>
    //<<Get extra information, Pa. \ref{pa:docs}>>
    //<<Extract examples, Pa. \ref{pa:docs}>>
		parsed = append(parsed, param)
	}

	return parsed
}
#+end_src


#+begin_export latex
  Building the schema is a preparation step. We do this by
  invoking the \ty{BuildSchema} function. We propagate any errors
  that might occur.
#+end_export

#+begin_src go <<Build parameter schema, Pa. \ref{pa:docs}>>=
  schema, err := parameter.Schema.BuildSchema()
	if err != nil {
		panic(fmt.Sprintf("cannot build schema: %e", err))
	}
#+end_src

#+begin_export latex
  There is basic data that describes the parameter,
  opposed to the examples or the actual schema we'll need to display.
  This data is the parameter's type, as in whether it's a query or path parameter,
  the parameter's name and its description. Checking if the parameter is required
  and whether to explode it are also trivial.
#+end_export

#+begin_src go <<Retrieve basic parameter info, Pa. \ref{pa:docs}>>=
  param := Parameter{
		ParamType:   parameter.In,
		Name:        parameter.Name,
		Description: parameter.Description,
	}

	if parameter.Required != nil {
		param.Required = *parameter.Required
	}

  if parameter.Explode != nil {
    param.Explode = *parameter.Explode
  }
#+end_src

#+begin_export latex
  Now extracting the schema we want to display later on is a bit more tricky.
  Schemas may be arbitrarily complex in theory, which makes parsing a little complex.
  We will encounter this problem later on, right we can simplify our problem. Right now
  we are working with url parameters. There schemas are quite shallow. Their datatype is
  either a primitive like an integer, string or boolean, or an arry composed of primitives.
  So in order to extract the parameter's schema we decide whether we are looking at an
  array or a primitive and handle those individually. But first we need to get the
  schema into a datastructure one can actually work with.
#+end_export

#+begin_src go <<Extract parameter schema, Pa. \ref{pa:docs}>>=
  if len(schema.Type) > 0 {
    if schema.Type[0] == "array" {
      //<<Handle array parameter schema, Pa. \ref{pa:docs}>>
    } else {
      param.Schema = schema.Type[0]
    }
  }
#+end_src

#+begin_export latex
  The underlying type of an array is for some reason deeply nested
  within this schema structure. Honestly I don't quite get what they are trying
  to do. No matter their ideas, I've found the value I'm looking for within
  the \ty{items} property under \ty{schema.Items.A.Schema().Type} using the debugger.
  This \ty{yaml.Node} structure is immensely complicated and as of now I don't know why.
  Sadly I could not find a propper documentation either. Well for further interactions
  with this we will rework the representation into something manageable. As for now we need
  to check whether this subnode \ty{A} exists and query it for its value.
#+end_export

#+begin_src go <<Handle array parameter schema, Pa. \ref{pa:docs}>>=
		if schema.Items != nil && schema.Items.A != nil {
			t := schema.Items.A.Schema().Type
			if len(t) > 0 {
				param.Schema = t[0] + "[]"
			}
		}
#+end_src

#+begin_export latex
  The example is either stored in the schema example as a value or within the
  example's content. If it's in its content, we need to loop over the content
  elements and retrieve all the values by hand.
#+end_export

#+begin_export latex
  Some parameters have extra information like default values or minima and maxima.
  These are stored inside the schema.
  In order not to crowd the parameter struct with properties that are rarely used, we store
  the extra information inside a single string. This string made up of key value pairs, e.g.
  if there is a minimum, it includes "Minimum: value".
  As stated above the extra information might include a minimum, a maximum and a default value.
  Most of our parameters don't specify any of those. None specify more the these three properties.
  The minimum and maximum properties are typed as floats, but we don't use floats in the specification.
  We convert them to integers to prevent confusion.
#+end_export

#+begin_src go <<Get extra information, Pa. \ref{pa:docs}>>=
		var vals []string
		if schema.Minimum != nil {
			vals = append(vals, fmt.Sprintf("Minimum: %d", int(*schema.Minimum)))
		}

		if schema.Maximum != nil {
			vals = append(vals, fmt.Sprintf("Maximum: %d", int(*schema.Maximum)))
		}

		if schema.Default != nil {
			vals = append(vals, fmt.Sprintf("Default: %s", schema.Default.Value))
		}

		param.Extra = strings.Join(vals, ", ")
#+end_src

#+begin_src go <<Extract examples, Pa. \ref{pa:docs}>>=
  if schema.Example != nil {
	  if schema.Example.Value != "" {
			param.Example = schema.Example.Value
		} else {
			for i, c := range schema.Example.Content {
				param.Example += c.Value
				if i < len(schema.Example.Content)-1 {
					param.Example += ","
				}
			}
		}
	}

#+end_src

#+begin_export latex
  Parsing the operation is a four step process.
  First we set the basic data like summary and the HTTP verb.
  Then we parse the operation specific parameters and append the
  path level parameters.
  Using these parameters including their default and example value
  we construct an example query.
  Lastly we parse the responses.
#+end_export

#+begin_src go <<Parse operations, Pa. \ref{pa:docs}>>=
  for verb, operation := range pathItem.GetOperations().FromOldest() {
    newOperation := Operation{
			Verb:        strings.ToUpper(verb),
			Description: operation.Description,
      Tags:        operation.Tags,
    }
	  newOperation.PathParameters = append(newOperation.PathParameters, pathParams...)

	  queryParams := extractParameters(operation.Parameters)
	  newOperation.QueryParameters = append(newOperation.QueryParameters, queryParams...)

    //<<Parse request body, Pa. \ref{pa:docs}>>
    //<<Construct example, Pa. \ref{pa:docs}>>
    //<<Parse Responses, Pa. \ref{pa:docs}>>
  	newPath.Operations = append(newPath.Operations, newOperation)
  }
#+end_src

#+begin_export latex
  We reduce parsing the request's body to reading a few fields. The body may
  be made up of lots of complex content types and further examples, but we are 
  not using those. As defined above, all we are looking for are a description,
  which is a string and a mime type. There are just a few endpoints supporting
  request bodies. This means we need to check the body's existence before 
  parsing it.
#+end_export

#+begin_src go <<Parse request body, Pa. \ref{pa:docs}>>=
  rb := operation.RequestBody
  if rb != nil && rb.Content != nil {
    bd :=	rb.Description
    ct := rb.Content.First().Key()
    newOperation.RequestBody = RequestBody{Description: bd, Mime: ct}
  }
#+end_src

#+begin_export latex
  The example is made up of all the parameters that are defined for the operation
  and provide an example field. We need to differentiate between path parameters
  and query parameters, as path parameters replace the placeholder within the
  url and query parameters are simply appended to it.
#+end_export

#+begin_src go <<Construct example, Pa. \ref{pa:docs}>>=
	examplePath := content.ServerURL

  //<<Opt. make local, Pa. \ref{pa:docs}>>

  examplePath += newPath.Name

	for _, param := range pathParams {
		examplePath = strings.ReplaceAll(examplePath, param.Name, param.Example)
	}

	examplePath = strings.ReplaceAll(examplePath, "{", "")
  examplePath = strings.ReplaceAll(examplePath, "}", "")
  //<<Remove trailing slashes, Pa. \ref{pa:docs}>>
  //<<Append query parameters, Pa. \ref{pa:docs}>>

#+end_src

#+begin_export latex
  We need to change the base url, iff the server is hosted locally.
#+end_export

#+begin_src go <<Opt. make local, Pa. \ref{pa:docs}>>=
  if local {
    examplePath = fmt.Sprintf("http://localhost:%d/api/v2", port)
  }
#+end_src

#+begin_export latex
  The example paths should not contain trailing slashes.
#+end_export

#+begin_src go <<Remove trailing slashes, Pa. \ref{pa:docs}>>=
  examplePath, _ = strings.CutSuffix(examplePath, "/")
#+end_src

#+begin_export latex
  Appending the query parameters is relatively straight forward. If there are 
  any query parameters, that have examples we append a question mark. We then
  iterate over the parameters, if they have an example value we append their
  name followed by '=' and the example value. The discriminator is defined as
  '&'. Array parameters might have an explode option. The explode options 
  says that instead of passing array items in one comma separated string, we 
  need to pass them as separate arguments, each prefixed by the parameters 
  name.
#+end_export

#+begin_src go <<Append query parameters, Pa. \ref{pa:docs}>>=
	sb := new(strings.Builder)
	for _, param := range queryParams {
		if param.Example != "" {
      if param.Explode {
				for val := range strings.SplitSeq(param.Example, ",") {
          addSingleArg(sb, param.Name, val)
        }
      } else {
        addSingleArg(sb, param.Name, param.Example)
      }
		}
	}

	newOperation.ExampleRequest = examplePath + sb.String()
#+end_src

#+begin_export latex
  We implement a function that handles prepending the correct character and
  builds the arguments according to our definition above.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:docs}>>=
  func addSingleArg(base *strings.Builder, name, value string) {
    if base.Len() == 0 {
			base.WriteRune('?')
		} else {
			base.WriteRune('&')
		}
    base.WriteString(name)
    base.WriteRune('=')
    base.WriteString(value)
  }
#+end_src

#+begin_export latex
  The response contains different data depending on which type of response we
  are currently handling. While all of them provide a code and description,
  it's just the response with code 200 that provides and example and schema.
#+end_export

#+begin_src go <<Parse Responses, Pa. \ref{pa:docs}>>=
	for strCode, response := range operation.Responses.Codes.FromOldest() {
    //<<Get response info, Pa. \ref{pa:docs}>>
    if !response.Content.IsZero() {
		//<<Act on response code, Pa. \ref{pa:docs}>>
		}

  	newOperation.Responses = append(newOperation.Responses, newResponse)
  }
#+end_src

#+begin_export latex
  The code is provided as the key for the current response. As it is a string
  and we expect an integer, we need to convert it. To do that we import
  \ty{strconv} and later use it to call \ty{Atoi}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:docs}>>=
  "strconv"
#+end_src

#+begin_export latex
  Let's get the code and set the description.
#+end_export

#+begin_src go <<Get response info, Pa. \ref{pa:docs}>>=
  code, err := strconv.Atoi(strCode)
	if err != nil {
		panic(fmt.Sprintf("cannot convert HTTP response code to int: %e", err))
	}

  newResponse := Response {
    Code: code,
    Description: response.Description,
  }

#+end_src

#+begin_export latex
  To differentiate between response codes we first check whether it is of code
  200 (OK). If it is we need to make sure that is has content. A single 
  response code may store multiple response contents, meaning we need to
  iterate over the provided map. This is also the only step were the acceptable
  content types are defined. Mime types/ content types of 200 (OK) responses
  indicate that this server accepts requests asking for these content types.
  We want to document them, which means we add them to the operations list of
  \ty{AcceptHeaders}.
#+end_export

#+begin_src go <<Act on response code, Pa. \ref{pa:docs}>>=
	for mime, contentValue := range response.Content.FromOldest() {
	  newResponse.Mime = mime
	  if newResponse.Code == 200 && contentValue != nil {
        newOperation.AcceptHeader = append(newOperation.AcceptHeader, mime)
        //<<Parse response schema, Pa. \ref{pa:docs}>>
        //<<Parse response example, Pa. \ref{pa:docs}>>
	  }
  }
#+end_src

#+begin_export latex
  Parsing the schema is rather complex. So we divide the problem into multiple
  steps. Step one is building the schema. Then we need to get a better 
  representation. The next step is to parse the new representation. Lastly we
  need to write the result into our \ty{Operation} type.
#+end_export

#+begin_src go <<Parse response schema, Pa. \ref{pa:docs}>>=
	if contentValue.Schema != nil {
    //<<Build response schema, Pa. \ref{pa:docs}>>
    //<<Change schema representation, Pa. \ref{pa:docs}>>
    //<<Parse new schema representation, Pa. \ref{pa:docs}>>
    //<<Write result to operation, Pa. \ref{pa:docs}>>
  }
#+end_src

#+begin_export latex
  We've already seen how to build the schema for the parametes.
  Building it for the response schema is the same.
#+end_export

#+begin_src go <<Build response schema, Pa. \ref{pa:docs}>>=
	schema, err := contentValue.Schema.BuildSchema()
		if err != nil {
			panic(fmt.Sprintf("cannot build schema: %e", err))
		}
#+end_src

#+begin_export latex
  To get this schema in a more manageable representation, we are going to 
  unwrap it. My idea of unwrapping an object consists of two steps:
  The first one is to use the yaml representation to create a json string, 
  essentially marshalling it. The second step is unmarshalling it, to get a 
  json object. I use this marshal and unmarshal strategy to get the json out of
  the libraries \ty{yaml.Node} format. It might be possible to do all of this
  in one go, but I don't see how, given the example's node structure. 
#+end_export

#+begin_src go <<Change schema representation, Pa. \ref{pa:docs}>>=
	schemaMarshalled, err := schema.MarshalJSONInline()
	if err != nil {
		panic(fmt.Sprintf("cannot marshal schema: %e", err))
	}

	var rawSchema map[string]any
	json.Unmarshal(schemaMarshalled, &rawSchema)
#+end_src

#+begin_export latex
  Marshalling requires \ty{encoding/json}. This package provides json
  specific utility functions. Most importantly it allows us to pretty print 
  using \ty{MarshalIndent}. So we need to import the package.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:docs}>>=
  "encoding/json"
#+end_src

#+begin_export latex
  Now to the complex part: parsing the new representation.
  We do this in a separate Function called \ty{parseResponseSchema}.
  This function takes the map we just created and returns a string in json format.
  To best handle the possibly deeply nested representation, \ty{parseResponseSchema}
  will work recursively.
  Depending on the type we are currently working with, there are three different
  cases to differentiate.
  The first one is an array, which has one subtype. The second one is an object
  which has arbitrary subtypes. Lastly there are primitive datatypes, which are the easiest.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:docs}>>=
  func parseResponseSchema(t map[string]any) string {
    //<<Get Type, Pa. \ref{pa:docs}>>
    //<<Handle cases, Pa. \ref{pa:docs}>>
  }
#+end_src

#+begin_export latex
  The type is always stored in the key "type". There is something wrong if it is not.
  We need to report that and might aswell do that by throwing an error. This type is
  a string. Again if it is not we throw an error.
#+end_export

#+begin_src go <<Get Type, Pa. \ref{pa:docs}>>=
	  r, ok := t["type"]
	  if !ok {
	  	panic("Error while parsing the schema. Key \"type\" does not exist.")
	  }

    c, ok := r.(string)
	  if !ok {
	    panic("Error while parsing the schema. Value of key \"type\" is not a string.")
	  }
#+end_src

#+begin_export latex
  We handle the cases by using a semantically fitting switch/case statement.
#+end_export

#+begin_src go <<Handle cases, Pa. \ref{pa:docs}>>=
	var res string
	switch c {
	  case "array":
	    //<<Handle array case, Pa. \ref{pa:docs}>>

    case "object":
      //<<Handle object case, Pa. \ref{pa:docs}>>

    default:
      //<<Handle default case, Pa. \ref{pa:docs}>>
	}

	return res
#+end_src

#+begin_export latex
  An array has a sibling called \ty{items} which tells us what kind of
  type is used within that array. We extract that type and call \ty{parseResponseSchema}
  on that again. To represent that this type is used within an array we pre- and postpend
  square brackets. If something goes wrong along the way, type assertions or missing keys, we just
  throw errors again.
#+end_export

#+begin_src go <<Handle array case, Pa. \ref{pa:docs}>>=
		i, ok := t["items"]
		if !ok {
	  	panic("Error while parsing the schema. Array is missing \"items\" sibling.")
		}

		n, ok := i.(map[string]any)
		if !ok {
	  	panic("Error while parsing the schema. Value of array item is not a map.")
		}

		res = fmt.Sprintf("[%s]", parseResponseSchema(n))
#+end_src

#+begin_export latex
  An object has a sibling called \ty{properties}. \ty{properties} is again a map
  where each key is the name of a property. The value of on of those keys is the
  type of that property. We begin similarly to the array, in that we extract the
  sibling and do a type assertion, throwing error when encountering invalid data,
  as always.
#+end_export

#+begin_src go <<Handle object case, Pa. \ref{pa:docs}>>=
		p, ok := t["properties"]
		if !ok {
	  	panic("Error while parsing the schema. Object is missing \"properties\" sibling.")
		}

		dt, ok := p.(map[string]any)
		if !ok {
	  	panic("Error while parsing the schema. Value of object property is not a map.")
		}

    //<<Parse object to string, Pa. \ref{pa:docs}>>
#+end_src

#+begin_export latex
  Again just like we did with the array, we need to pre- and postpend symbols
  for a valid object notation. In this case it's curly brackets. Parsing the individual
  properties begins with writing down their names. The values are again obtained by calling
  \ty{parseResponseSchema} on them.
  Each property needs to be separated by a comma. To remove the trailing comma we reslice
  the string. This probably is not super performant, but I believe that the amount of
  data we're handling allows us to do so.
#+end_export

#+begin_src go <<Parse object to string, Pa. \ref{pa:docs}>>=
	res = "{"
		for k, v := range dt {
			pv, ok := v.(map[string]any)
			if !ok {
	  	  panic("Error while parsing the schema. Value of nested object property is not a map.")
			}

			res += fmt.Sprintf("\"%s\":%s,", k, parseResponseSchema(pv))
		}

		res = res[:len(res)-1]
		res += "}"
#+end_src

#+begin_export latex
  Lastly we handle the default case. This is by far the easiest. All we need to
  do is take the given type and put it into a string literal notation i.e. pre-
  and postpend quotation marks.
#+end_export

#+begin_src go <<Handle default case, Pa. \ref{pa:docs}>>=
  res = fmt.Sprintf("\"%s\"", c)
#+end_src

#+begin_export latex
  With the schema parsing function done we return to parsing the operation.
  Here we need to call the function we just created and use the json module to
  correctly indent it. The \ty{indent} function expects a buffer from the
  \ty{bytes} package. So we need to import that first.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:docs}>>=
	"bytes"
#+end_src

#+begin_export latex
  Now we are ready to call the parse function.
#+end_export

#+begin_src go <<Parse new schema representation, Pa. \ref{pa:docs}>>=
  parsed := parseResponseSchema(rawSchema)
#+end_src

#+begin_export latex
  And write its result.
#+end_export

#+begin_src go <<Write result to operation, Pa. \ref{pa:docs}>>=
  var indented bytes.Buffer
	json.Indent(&indented, []byte(parsed), "", "  ")
	newOperation.Schema = indented.String()
#+end_src

#+begin_export latex
  To parse the example, we first check whether there is an example to begin
  with. If there is an example we take it and marshal that. The example is, for
  some reason, wrapped in an object called \ty{"value"}. Before turning it into
  our final json representation, we need to unwrap the response, to comply with
  the underlying api.
#+end_export

#+begin_src go <<Parse response example, Pa. \ref{pa:docs}>>=
	if contentValue.Examples.Len() > 0 {
		ex := contentValue.Examples.First().Value()
		marhshalled, err := ex.MarshalJSON()

		if err != nil {
			panic(fmt.Sprintf("cannot marshal example: %e", err))
		}

    //<<Unwrap response example, Pa. \ref{pa:docs}>>
	}
#+end_src

#+begin_export latex
  Unwrapping the response is again about marshalling and unmarshalling the 
  json. If the response schema is plain text, i.e. the response is a single 
  string, we need to modify the example. The plain text examples are enclosed
  in \ty{"}, to comply with json format. The actual response however is not
  enclosed by \ty{"}. So we need to remove this. Then there is a \ty{\n} 
  string, which should instead be single rune, and lastly there are 
  escaped quotation marks \ty{"}, in the strings, which need to be unescaped.
#+end_export

#+begin_src go <<Unwrap response example, Pa. \ref{pa:docs}>>=
	var wrapped map[string]any
	json.Unmarshal(marhshalled, &wrapped)
	unwrapped, err := marshal(wrapped["value"])

	if err != nil {
		panic(fmt.Sprintf("cannot unwrap example: %e", err))
	}
	
  if newOperation.Schema == `"string"` {
    rawStr := string(unwrapped)
    rawStr = rawStr[1:len(rawStr)-1]
    rawStr = strings.ReplaceAll(rawStr, `\"`, `"`)
		rawStr = strings.ReplaceAll(rawStr, "\\r\\n", "\n")
	  newOperation.ExampleResponse = rawStr
  } else {
	  newOperation.ExampleResponse = string(unwrapped)
  }
#+end_src

#+begin_export latex
  The value of \ty{ExampleResponse}, is directly passed to an html tag, that
  renders it as is. \ty{Marshal} introduces html escaping which clashes with
  the html tag we use for rendering. We quickly write a custom version for
  unmarshal using the json encoder, which avoids html escaping, but keeps 
  indentation and overall pretty printing.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:docs}>>=
  func marshal(x any) ([]byte, error) {
    buf := new(bytes.Buffer)
	  encoder := json.NewEncoder(buf)
	  encoder.SetEscapeHTML(false)
	  encoder.SetIndent("", "  ")
	  err := encoder.Encode(x)
    return buf.Bytes(), err
  }
#+end_src

#+begin_export latex
  We are now done retrieving the data. Which means we can start adding 
  handlers. The most important route is for the documentation itself. This
  documentation uses static files and links to the database directory. We need
  to server those later on as well.
#+end_export

#+begin_src go <<Handle base route, Pa. \ref{pa:docs}>>=
	http.HandleFunc(prefix, 
    func(w http.ResponseWriter, r *http.Request) { 
      defaultHandler(tmpl, &content, w, r)
    })
#+end_src

#+begin_export latex
  We also need to add an import for \ty{net/http}.
#+end_export

#+begin_src go <<Imports, Pa. \ref{pa:docs}>>=
	"net/http"
#+end_src

#+begin_export latex
  The default handler does nothing except executing the \ty{app} template for
  now.
#+end_export

#+begin_src go <<Functions, Pa. \ref{pa:docs}>>=
  func defaultHandler(tmpl *template.Template, content *Content, w http.ResponseWriter, _ *http.Request) {
    tmpl.ExecuteTemplate(w, "app.html", content)
  }
#+end_src

#+begin_export latex
  As already mentioned the frontend relies on static files. Those are mostly 
  style sheets. Serving those requires a fileserver. We again use \ty{embed} to
  keep file access when using binaries. To improve url readability and conform
  to the given prefix we make use of the stripprefix function, when registering
  the handler.
#+end_export

#+begin_src go <<Handle static files, Pa. \ref{pa:docs}>>=
  // The route within in FileServer is a local one, from my filesystem. Files may be queried and served.
  // The path before that are the ones I may use within the browser to ask for these files from the file server.
  http.Handle(prefix+"/static/", 
    http.StripPrefix(prefix, http.FileServer(http.FS(staticFS))))
#+end_src

#+begin_export latex
  We use another fileserver for for serving the databases. We don't need to 
  embed those, as the user defines the path, when calling \ty{never}.
#+end_export

#+begin_src go <<Handle database files, Pa. \ref{pa:docs}>>=
  http.Handle(prefix + "/" + dbDirPath,
    http.StripPrefix(prefix + "/" + dbDirPath, http.FileServer(http.Dir(dbDirPath))))
#+end_src
